import test from 'node:test';
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const script = fileURLToPath(new URL('../scripts/Rehearse-AssistedDelivery.mjs', import.meta.url));
function run(scenario) {
  const result = spawnSync(process.execPath, [script, scenario], { encoding: 'utf8', timeout: 15000 });
  assert.equal(result.status, 0, result.stderr);
  return JSON.parse(result.stdout);
}

test('assisted rehearsal connects actual generated bytes to partial update and recovery', () => {
  const receipt = run('interrupted');
  assert.equal(receipt.status, 'restored');
  assert.equal(receipt.syntheticOnly, true);
  assert.equal(receipt.remoteMutation, false);
  assert.equal(receipt.httpTested, false);
  assert.equal(receipt.identityVerified, false);
  assert.equal(receipt.files.length, 2);
  assert.equal(receipt.cleanupVerified, true);
  assert.equal(receipt.partialUpdateObserved, true);
  for (const file of receipt.files) {
    assert.equal(file.beforeSha256, file.finalSha256);
    assert.notEqual(file.beforeSha256, file.approvedSha256);
  }
  assert.equal(receipt.files[0].interruptedSha256, receipt.files[0].approvedSha256);
  assert.equal(receipt.files[1].interruptedSha256, receipt.files[1].beforeSha256);
  assert.equal(receipt.metrics.humanActiveMs, null);
  assert.equal(receipt.metrics.providerWaitMs, null);
  assert.equal(receipt.metrics.llmCostUsd, null);
  assert(receipt.metrics.totalExecutionMs > 0);
  assert(receipt.steps.every(step => Number.isFinite(step.elapsedMs) && step.elapsedMs >= 0));
});

for (const [scenario, expected] of [['missing-provider', 'maintainer_approval_pending'], ['expired', 'expired']]) {
  test(`assisted rehearsal stops before local publication when ${scenario}`, () => {
    const receipt = run(scenario);
    assert.equal(receipt.status, 'blocked');
    assert.equal(receipt.gate, expected);
    assert.equal(receipt.publicationAttempted, false);
    assert.equal(receipt.cleanupVerified, true);
    assert.equal(receipt.files.length, 2);
  });
}
