import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {build} from 'esbuild';
import {Miniflare,convertV4MiniflareOptions} from 'miniflare';
import {fixture,schemas,sqlStatements} from './fixtures/occurrence-operations.mjs';
import {qaAdministrationFixture} from './fixtures/qa-administrative-composition.mjs';
import {computeOccurrencePlanDigest} from '../lib/assistance-occurrence-digest.mjs';
import {computeAdministrativeResultDigest} from '../lib/assistance-administrative-closure-readback.mjs';
import {computeQaClosureBaselineRef} from '../lib/assistance-qa-closure-catalog.mjs';
const load=()=>import('../lib/assistance-private-installation-d1.mjs');
test('revocation reconciles the original provenance snapshot despite caller mutation',async()=>{const {createPrivateInstallationD1}=await load(),f=await own();try{f.migrate();const base=createPrivateInstallationD1({db:f.db});await base.write(f.input);const p=(await base.read(f.m.occurrenceId)).provenance;let changed=false;const db={...f.db,prepare:sql=>{const statement=f.db.prepare(sql);if(!sql.startsWith('SELECT a.*'))return statement;return {bind:(...args)=>({first:async()=>{const row=await statement.bind(...args).first();if(!changed){changed=true;p.intentId=crypto.randomUUID();}return row;}})};}};assert.equal(await createPrivateInstallationD1({db}).revoke(p),true);assert.equal((await base.read(f.m.occurrenceId)).revoked,true);}finally{f.cleanup();}});
test('administrative material with accessors is rejected without invoking them',async()=>{const {createPrivateInstallationD1}=await load(),f=await own();try{f.migrate();let invoked=0;const input={...f.input};Object.defineProperty(input,'intent',{enumerable:true,get(){invoked++;return f.input.intent;}});assert.equal(await createPrivateInstallationD1({db:f.db}).write(input),false);assert.equal(invoked,0);}finally{f.cleanup();}});
test('intent material is snapshotted before asynchronous digest checks',async()=>{const {createPrivateInstallationD1}=await load(),f=await own(),subtle=crypto.subtle,original=subtle.digest,descriptor=Object.getOwnPropertyDescriptor(subtle,'digest');try{f.migrate();const expected=f.input.intent.intentId;let changed=false;subtle.digest=async function(algorithm,data){const result=await original.call(this,algorithm,data);if(new TextDecoder().decode(data).includes('"contract":"afw-private-installation-intent/v1"')){changed=true;f.input.intent.intentId=crypto.randomUUID();}return result;};const actor=createPrivateInstallationD1({db:f.db});assert.equal(await actor.write(f.input),true);assert.equal(changed,true);assert.equal((await actor.read(f.m.occurrenceId)).provenance.intentId,expected);}finally{if(descriptor)Object.defineProperty(subtle,'digest',descriptor);else delete subtle.digest;f.cleanup();}});
test('an incomplete migration cannot activate the private D1 writer',async()=>{const {createPrivateInstallationD1}=await load(),f=await own();try{f.migrate();f.a.exec('DROP TRIGGER assistance_private_installation_window');assert.equal(await createPrivateInstallationD1({db:f.db}).write(f.input),false);assert.equal(f.a.prepare('SELECT count(*) n FROM assistance_occurrence_approved_plans').get().n,0);}finally{f.cleanup();}});
test('window crossing during a prewrite query prevents starting the D1 batch',async()=>{const {createPrivateInstallationD1}=await load(),f=await own();try{f.migrate();let at=f.m.startAt+1,batches=0;const db={...f.db,prepare:sql=>{const statement=f.db.prepare(sql);if(!sql.startsWith('SELECT occurrence_id FROM assistance_occurrence_approved_plans'))return statement;return {bind:(...args)=>({first:async()=>{const value=await statement.bind(...args).first();at=f.m.deadline;return value;}})};},batch:async statements=>{batches++;return f.db.batch(statements);}};assert.equal(await createPrivateInstallationD1({db,now:()=>at}).write(f.input),false);assert.equal(batches,0);}finally{f.cleanup();}});
test('D1 server time rejects a stale batch even if the private clock claims a live window',async()=>{const {createPrivateInstallationD1}=await load(),f=await own();try{f.migrate();const deadline=Date.now()-1;f.input.approval.manifest.deadline=deadline;f.input.registration.plan.closeAt=deadline;f.input.registration.approvalDigest=await computeOccurrencePlanDigest({manifest:f.input.approval.manifest,identityRef:f.input.approval.identityRef,admissionContract:'server-v1',approval:f.input.approval});f.input.registration.plan.baselineRef=await computeQaClosureBaselineRef(f.input.registration);Object.assign(f.input.intent,{recordRef:f.input.registration.plan.baselineRef,ownerRef:f.input.registration.plan.baselineRef,deadline,approvalPinsDigest:await computeAdministrativeResultDigest({registration:f.input.registration,approval:f.input.approval})});const {recordDigest:ignored,...body}=f.input.intent;void ignored;f.input.intent.recordDigest=await computeAdministrativeResultDigest(body);await assert.rejects(()=>createPrivateInstallationD1({db:f.db,now:()=>deadline-1}).write(f.input));assert.equal(f.a.prepare('SELECT count(*) n FROM assistance_occurrence_approved_plans').get().n,0);}finally{f.cleanup();}});
async function own(){const f=fixture();for(const name of ['assistance-occurrences-v2','assistance-occurrences-v2-reservation-fence'])f.a.exec(readFileSync('worker/operations/'+name+'.sql','utf8'));const approval={manifest:f.m,identityRef:'c'.repeat(64),enrollmentRef:'d'.repeat(64),serverConfigVersion:'e'.repeat(64),planRevision:1};const {registration:r}=await qaAdministrationFixture({createdAt:f.m.startAt,closeAt:f.m.deadline,expiresAt:f.m.deadline+10000});r.contract='afw-qa-closure-approval/v2';r.plan.occurrenceId=f.m.occurrenceId;r.approvalDigest=await computeOccurrencePlanDigest({manifest:f.m,identityRef:approval.identityRef,admissionContract:'server-v1',approval});r.plan.baselineRef=await computeQaClosureBaselineRef(r);const intent={contract:'afw-private-installation-intent/v1',recordRef:r.plan.baselineRef,creationRef:r.provisioning.creationRef,ownerRef:r.plan.baselineRef,reservationSequence:1,intentId:crypto.randomUUID(),approvalPinsDigest:await computeAdministrativeResultDigest({registration:r,approval}),occurrenceId:f.m.occurrenceId,deadline:f.m.deadline,preparedAt:f.m.startAt,state:'write_started',sequence:2,writeStartedAt:f.m.startAt};intent.recordDigest=await computeAdministrativeResultDigest(intent);return {...f,input:{registration:r,approval,intent},migrate(){f.a.exec(readFileSync('worker/operations/assistance-private-installation-provenance.sql','utf8'));}};}
test('D1 provenance is opt-in and records approval and ownership atomically',async()=>{const {createPrivateInstallationD1}=await load(),f=await own();try{const actor=createPrivateInstallationD1({db:f.db});assert.equal(await actor.write(f.input),false);f.migrate();assert.equal(await actor.write(f.input),true);const row=await actor.read(f.m.occurrenceId);assert.deepEqual(row.approval,f.input.approval);assert.equal(row.provenance.intentId,f.input.intent.intentId);assert.equal(row.revoked,false);assert.equal(await actor.write(f.input),false);assert.equal(f.a.prepare('SELECT count(*) n FROM assistance_private_installation_provenance').get().n,1);assert.throws(()=>f.a.exec('UPDATE assistance_private_installation_provenance SET reservation_sequence=1'));assert.throws(()=>f.a.exec('DELETE FROM assistance_private_installation_provenance'));}finally{f.cleanup();}});
test('failed second D1 statement leaves no orphan approval or provenance',async()=>{const {createPrivateInstallationD1}=await load(),f=await own();try{f.migrate();f.a.exec("CREATE TRIGGER synthetic_reject_provenance BEFORE INSERT ON assistance_private_installation_provenance BEGIN SELECT RAISE(ABORT,'synthetic reject'); END;");await assert.rejects(()=>createPrivateInstallationD1({db:f.db}).write(f.input));assert.equal(f.a.prepare('SELECT count(*) n FROM assistance_occurrence_approved_plans').get().n,0);assert.equal(f.a.prepare('SELECT count(*) n FROM assistance_private_installation_provenance').get().n,0);}finally{f.cleanup();}});
test('lost D1 commit ACK is read back without repeating a batch',async()=>{const {createPrivateInstallationD1}=await load(),f=await own();try{f.migrate();let batches=0;const db={...f.db,batch:async statements=>{batches++;await f.db.batch(statements);throw Error('synthetic lost D1 ACK');}},actor=createPrivateInstallationD1({db});await assert.rejects(()=>actor.write(f.input));assert.equal((await actor.read(f.m.occurrenceId)).provenance.intentId,f.input.intent.intentId);assert.equal(batches,1);}finally{f.cleanup();}});
test('wrong primary intent is rejected and conditional revocation preserves another owner',async()=>{const {createPrivateInstallationD1}=await load(),f=await own();try{f.migrate();const actor=createPrivateInstallationD1({db:f.db}),bad=structuredClone(f.input);bad.intent.occurrenceId=crypto.randomUUID();const {recordDigest:ignored,...body}=bad.intent;void ignored;bad.intent.recordDigest=await computeAdministrativeResultDigest(body);assert.equal(await actor.write(bad),false);assert.equal(await actor.write(f.input),true);const row=await actor.read(f.m.occurrenceId),wrong={...row.provenance,intentId:crypto.randomUUID()};assert.equal(await actor.revoke(wrong),false);assert.equal((await actor.read(f.m.occurrenceId)).revoked,false);assert.equal(await actor.revoke(row.provenance),true);assert.equal((await actor.read(f.m.occurrenceId)).revoked,true);assert.equal(f.a.prepare('SELECT count(*) n FROM assistance_private_installation_provenance').get().n,1);}finally{f.cleanup();}});
test('native D1 rolls back a failed batch, preserves lost ACK ownership through restart and revokes only its own provenance',async()=>{
 const f=await own(),input=f.input;f.cleanup();const built=await build({stdin:{resolveDir:process.cwd(),contents:`
 import {createPrivateInstallationD1} from './lib/assistance-private-installation-d1.mjs';
 const input=${JSON.stringify(input)};
 // Local synthetic test-only writer, no deployed handler or authority.
 export default {async fetch(request,env){const path=new URL(request.url).pathname,actor=createPrivateInstallationD1({db:env.DB});let result;try{if(path==='/write'||path==='/lost-ack')result=await actor.write(input);else if(path==='/revoke-wrong'){const r=await actor.read(input.intent.occurrenceId);result=await actor.revoke({...r.provenance,intentId:crypto.randomUUID()});}else if(path==='/revoke-own')result=await actor.revoke((await actor.read(input.intent.occurrenceId)).provenance);else result=await actor.read(input.intent.occurrenceId);}catch{result={fixture:'unavailable'};}return Response.json(result,{status:path==='/lost-ack'?503:200});}};
 `},bundle:true,write:false,format:'esm',platform:'browser'});const options={modules:true,compatibilityDate:'2026-09-07',script:built.outputFiles[0].text,d1Databases:['DB']},runtime=new Miniflare(convertV4MiniflareOptions(options));
 try{let db=await runtime.getD1Database('DB');for(const name of [...schemas,'assistance-occurrences-v2','assistance-occurrences-v2-reservation-fence','assistance-private-installation-provenance'])for(const sql of sqlStatements(readFileSync('worker/operations/'+name+'.sql','utf8')))await db.prepare(sql).run();const s=input.approval.manifest.signal;await db.prepare('INSERT INTO assistance_supervision_events VALUES(?,?,?,?,?,?,?)').bind(s.eventId,s.projectRef,s.revision,s.kind,s.topic,s.observedAt,Date.now()).run();await db.prepare("CREATE TRIGGER synthetic_reject_provenance BEFORE INSERT ON assistance_private_installation_provenance BEGIN SELECT RAISE(ABORT,'synthetic rejection'); END;").run();const call=async path=>{const response=await runtime.dispatchFetch('https://synthetic.invalid'+path);assert.equal(response.status,path==='/lost-ack'?503:200);return response.json();};assert.deepEqual(await call('/write'),{fixture:'unavailable'});assert.equal((await db.prepare('SELECT count(*) n FROM assistance_occurrence_approved_plans').first()).n,0);await db.prepare('DROP TRIGGER synthetic_reject_provenance').run();await call('/lost-ack');await runtime.setOptions(convertV4MiniflareOptions({...options,bindings:{RESTART:'true'}}));db=await runtime.getD1Database('DB');assert.equal((await call('/read')).provenance.intentId,input.intent.intentId);assert.equal(await call('/revoke-wrong'),false);assert.equal((await call('/read')).revoked,false);assert.equal(await call('/revoke-own'),true);assert.equal((await call('/read')).revoked,true);assert.equal((await db.prepare('SELECT count(*) n FROM assistance_occurrence_approved_plans').first()).n,1);assert.equal((await db.prepare('SELECT count(*) n FROM assistance_private_installation_provenance').first()).n,1);assert.equal((await db.prepare('SELECT count(*) n FROM assistance_occurrence_plan_revocations').first()).n,1);}finally{await runtime.dispose();}
});
