import test from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {manifest} from './fixtures/occurrence-operations.mjs';
import {qaAdministrationFixture} from './fixtures/qa-administrative-composition.mjs';
import {computeOccurrencePlanDigest} from '../lib/assistance-occurrence-digest.mjs';
import {computeQaClosureBaselineRef,isQaProvisioningReservation} from '../lib/assistance-qa-closure-catalog.mjs';
const load=()=>import('../lib/assistance-private-provider-observation.mjs');
async function fixture(){
 const m={...manifest(),startAt:1000,deadline:2000},approval={manifest:m,identityRef:'c'.repeat(64),enrollmentRef:'d'.repeat(64),serverConfigVersion:'e'.repeat(64),planRevision:1};
 const {registration,results}=await qaAdministrationFixture({createdAt:1000,closeAt:2000,expiresAt:12000});registration.contract='afw-qa-closure-approval/v2';registration.plan.occurrenceId=m.occurrenceId;registration.approvalDigest=await computeOccurrencePlanDigest({manifest:m,identityRef:approval.identityRef,admissionContract:'server-v1',approval});registration.plan.baselineRef=await computeQaClosureBaselineRef(registration);
 const r=registration.resources,root='/accounts/'+r.accountId,appPath=root+'/access/apps/'+r.applicationId;
 const provider={applicationDomain:'operations-manager.agentfriendlyweb.dev/assistance/custody/confirm',applicationAudience:'f'.repeat(64)};
 results.application={id:r.applicationId,type:'self_hosted',domain:provider.applicationDomain,aud:provider.applicationAudience};results.policy={id:r.policyId,decision:'non_identity',include:[{service_token:{token_id:r.tokenId}}],exclude:[],require:[]};
 const source={registration,approval,provider},calls=[];let clock=1500;
 const request=async input=>{calls.push(input);let value;if(input.path===appPath)value=results.application;else if(input.path===root+'/access/service_tokens')return {success:true,result:[structuredClone(results.token)],result_info:{page:1,per_page:100,count:1,total_count:1,total_pages:1}};else if(input.path===appPath+'/policies')return {success:true,result:[structuredClone(results.policy)],result_info:{page:1,per_page:100,count:1,total_count:1,total_pages:1}};else value=input.path.includes('/service_tokens/')?results.token:input.path.endsWith('/settings')?results.settings:input.path.endsWith('/schedules')?results.schedules:results.policy;return {success:true,result:structuredClone(value)};};
 return {source,ref:registration.plan.baselineRef,results,calls,request,now:()=>clock,setTime:t=>{clock=t;},readPins:async()=>structuredClone(source)};
}
test('fixed GET reader observes actual responses twice without returning authority or raw identity',async()=>{const f=await fixture(),{createPrivateProviderObservation}=await load(),reader=createPrivateProviderObservation(f);const value=await reader.read(f.ref);assert.equal(value.state,'observed');assert.equal(value.recordRef,f.ref);assert.equal(value.token.createdAt,1000);assert.equal(value.token.expiresAt,12000);assert.equal(f.calls.length,14);assert.ok(f.calls.every(c=>c.method==='GET'&&c.signal instanceof AbortSignal));assert.equal(isQaProvisioningReservation(value,f.ref),false);assert.ok(!JSON.stringify(value).includes('synthetic-placeholder'));assert.ok(!JSON.stringify(value).includes('client_secret_version'));assert.equal(await reader.read('0'.repeat(64)),null);});
test('missing or inconsistent pagination never implies a complete inventory',async()=>{for(const change of [r=>{delete r.result_info;},r=>{r.result_info.total_count=2;},r=>{r.result_info.total_pages=5;},r=>{r.result.push(r.result[0]);r.result_info.count=2;r.result_info.total_count=2;}]){const f=await fixture(),{createPrivateProviderObservation}=await load(),request=async c=>{const r=await f.request(c);if(c.query)change(r);return r;};assert.equal(await createPrivateProviderObservation({...f,request}).read(f.ref),null);}});
test('complete second page is requested with the same fixed target and budget',async()=>{const f=await fixture(),{createPrivateProviderObservation}=await load();const request=async c=>{const r=await f.request(c);if(c.path.endsWith('/service_tokens')){r.result=c.query.page===1?[{...structuredClone(f.results.token),id:'99999999-9999-4999-8999-999999999999'}]:[structuredClone(f.results.token)];r.result_info={page:c.query.page,per_page:100,count:1,total_count:2,total_pages:2};}return r;};const value=await createPrivateProviderObservation({...f,request}).read(f.ref);assert.equal(value.inventory.tokenCount,2);assert.equal(f.calls.length,16);assert.equal(f.calls.filter(c=>c.query?.page===2).length,2);});
test('identity, application or effective policy mismatches fail closed',async()=>{for(const change of [f=>{f.results.token.enabled=false;},f=>{f.results.token.created_at=new Date(999).toISOString();},f=>{f.results.application.aud='0'.repeat(64);},f=>{f.results.policy.include.push({everyone:{}});},f=>{f.results.token.client_secret='do-not-return';}]){const f=await fixture(),{createPrivateProviderObservation}=await load();change(f);assert.equal(await createPrivateProviderObservation(f).read(f.ref),null);}});
test('source or observed metadata changes between passes are not accepted',async()=>{for(const drift of ['source','settings']){const f=await fixture(),{createPrivateProviderObservation}=await load();let calls=0;const request=async c=>{if(++calls===8){if(drift==='source')f.source.approval.planRevision++;else f.results.settings.bindings.push({name:'CHANGED',type:'plain_text',text:'true'});}return f.request(c);};assert.equal(await createPrivateProviderObservation({...f,request}).read(f.ref),null);}});
test('deadline and backwards clocks deny continuation',async()=>{for(const clock of [2000,1400]){const f=await fixture(),{createPrivateProviderObservation}=await load(),request=async c=>{const r=await f.request(c);f.setTime(clock);return r;};assert.equal(await createPrivateProviderObservation({...f,request}).read(f.ref),null);assert.equal(f.calls.length,1);}});
test('timeout cancels in-flight work and never resumes additional GETs',async()=>{const f=await fixture(),{createPrivateProviderObservation}=await load();let release,signal;const request=async c=>{f.calls.push(c);signal=c.signal;return new Promise(resolve=>{release=resolve;});};const reader=createPrivateProviderObservation({...f,request,timeoutMs:1000});assert.equal(await reader.read(f.ref),null);assert.equal(signal.aborted,true);release({success:true,result:f.results.token});await new Promise(resolve=>setTimeout(resolve,10));assert.equal(f.calls.length,1);});
test('real loopback HTTP transport carries fixed GETs and aborts a stalled read',async()=>{
 const f=await fixture(),{createPrivateProviderObservation}=await load();let stalled=false,requests=0;
 const server=createServer(async(req,res)=>{requests++;if(stalled)return;const url=new URL(req.url,'http://127.0.0.1');assert.equal(req.method,'GET');const value=await f.request({method:req.method,path:url.pathname,...(url.search?{query:Object.fromEntries([...url.searchParams].map(([k,v])=>[k,Number(v)]))}:{})});res.setHeader('Content-Type','application/json');res.end(JSON.stringify(value));});
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
 try{const origin='http://127.0.0.1:'+server.address().port,request=async c=>{const url=new URL(c.path,origin);for(const [k,v]of Object.entries(c.query??{}))url.searchParams.set(k,String(v));return (await fetch(url,{method:c.method,signal:c.signal})).json();};assert.equal((await createPrivateProviderObservation({...f,request}).read(f.ref)).state,'observed');assert.equal(requests,14);stalled=true;assert.equal(await createPrivateProviderObservation({...f,request,timeoutMs:1000}).read(f.ref),null);assert.equal(requests,15);}finally{server.closeAllConnections();await new Promise(resolve=>server.close(resolve));}
});
test('provider reader composes with the body-bounded fixed-origin custody transport',async()=>{const f=await fixture(),{createPrivateProviderObservation}=await load(),{createPrivateProviderGetTransport}=await import('../lib/assistance-private-provider-get-transport.mjs');const request=createPrivateProviderGetTransport({resources:f.source.registration.resources,readCredential:async()=> 'synthetic-admin-custody',fetchImpl:async(url,init)=>{const target=new URL(url);assert.equal(target.origin,'https://api.cloudflare.com');assert.equal(init.redirect,'manual');const path=target.pathname.replace('/client/v4',''),query=target.search?Object.fromEntries([...target.searchParams].map(([k,v])=>[k,Number(v)])):undefined;return Response.json(await f.request({method:init.method,path,signal:init.signal,...(query?{query}:{})}));}});assert.equal((await createPrivateProviderObservation({...f,request}).read(f.ref)).state,'observed');assert.equal(f.calls.length,14);});
test('actual point GET missing name is reconciled only against independently listed metadata',async()=>{for(const changed of [false,true]){const f=await fixture(),{createPrivateProviderObservation}=await load(),request=async c=>{const r=await f.request(c);if(c.path.includes('/service_tokens/'))delete r.result.name;if(changed&&c.path.endsWith('/service_tokens'))r.result[0].name='different-listed-name';return r;};const value=await createPrivateProviderObservation({...f,request}).read(f.ref);if(changed)assert.equal(value,null);else assert.equal(value.state,'observed');}});
