import test from 'node:test';
import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {Miniflare,convertV4MiniflareOptions} from 'miniflare';
import {createPrivateExecutionCorrelation} from '../lib/assistance-private-execution-correlation.mjs';
import {manifest} from './fixtures/occurrence-operations.mjs';
import {qaAdministrationFixture} from './fixtures/qa-administrative-composition.mjs';
import {computeOccurrencePlanDigest} from '../lib/assistance-occurrence-digest.mjs';
import {computeQaClosureBaselineRef,isQaProvisioningReservation} from '../lib/assistance-qa-closure-catalog.mjs';
const load=()=>import('../lib/assistance-private-original-execution-reader.mjs');
async function fixture(){
 const m={...manifest(),startAt:1000000,deadline:1020000},approval={manifest:m,identityRef:'c'.repeat(64),enrollmentRef:'d'.repeat(64),serverConfigVersion:'e'.repeat(64),planRevision:1};const {registration}=await qaAdministrationFixture({createdAt:1000000,closeAt:1020000,expiresAt:1030000});registration.contract='afw-qa-closure-approval/v2';registration.plan.occurrenceId=m.occurrenceId;registration.approvalDigest=await computeOccurrencePlanDigest({manifest:m,identityRef:approval.identityRef,admissionContract:'server-v1',approval});registration.plan.baselineRef=await computeQaClosureBaselineRef(registration);
 const threadId='11111111-1111-4111-8111-111111111111',turnId='22222222-2222-4222-8222-222222222222',cwd='/workspace/agent-friendly-web',ref=registration.plan.baselineRef,receipt={contract:'afw-private-custody-challenge/v1',state:'confirmed',recordRef:ref,receiptRef:'f'.repeat(64),issuedAt:1003000,deadline:1020000,consumedAt:1004000};
 const command='node scripts/afw-private-challenge-client.mjs confirm '+ref+' '+m.startAt+' '+m.deadline;
 const commandDigest=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(command))),v=>v.toString(16).padStart(2,'0')).join('');
 const pins={registration,approval,cloud:{threadId,environmentId:'ccarenv_synthetic',cwd,commandDigest}};
 const item=(id,cmd,text)=>({type:'commandExecution',id,command:cmd,cwd,status:'completed',exitCode:0,durationMs:0,output:{text,truncated:false}});
 const probes=[['head','git rev-parse HEAD',m.sourceRevision+'\n'],['origin','git remote get-url origin','https://github.com/tokenizartinfo-ops/agent-friendly-web.git\n'],['clean','git status --porcelain --untracked-files=all','']];
 const items=[...probes.map(([id,cmd,out])=>item('exec-before-'+id,cmd,out)),item('exec-challenge',command,JSON.stringify(receipt)+'\n'),...probes.map(([id,cmd,out])=>item('exec-after-'+id,cmd,out))];
 const original={schemaVersion:1,thread:{id:threadId,kind:'codex',hostId:'durable',cwd:'/workspace'},turns:[{id:turnId,status:'completed',error:null,startedAt:1001,completedAt:1005,items}]};let clock=1006000;const requests=[];
 return {pins,original,receipt,ref,input:{recordRef:ref,turnId,commandItemId:'exec-challenge'},requests,options:{now:()=>clock,readPins:async()=>structuredClone(pins),readThread:async input=>{requests.push(input);return structuredClone(original);}},setTime:t=>{clock=t;}};
}
test('original command and Git traces project receipt locator without accepting stdout as publication authority',async()=>{const f=await fixture(),{createPrivateOriginalExecutionReader}=await load(),result=await createPrivateOriginalExecutionReader(f.options).read(f.input);assert.equal(result.source,'official-thread-command');assert.equal(result.sourceRevision,f.pins.approval.manifest.sourceRevision);assert.equal(result.receiptRef,f.receipt.receiptRef);assert.equal(result.turnStartedAt,1001000);assert.equal(result.turnCompletedAt,1005000);assert.equal(isQaProvisioningReservation(result,f.ref),false);assert.ok(!JSON.stringify(result).includes('publicationId'));assert.equal(f.requests.length,1);assert.equal(f.requests[0].threadId,f.pins.cloud.threadId);assert.ok(f.requests[0].signal instanceof AbortSignal);});
test('incomplete, mismatched, forged or truncated originals never project execution',async()=>{for(const mutate of [f=>{f.original.thread.hostId='local';},f=>{f.original.turns[0].error={message:'private'};},f=>{f.original.turns[0].items[0].output.text='0'.repeat(40);},f=>{f.original.turns[0].items[6].output.text=' M changed\n';},f=>{f.original.turns[0].items[0].command="echo '"+f.pins.approval.manifest.sourceRevision+"'";},f=>{f.original.turns[0].items[3].output.truncated=true;},f=>{delete f.original.turns[0].items[3].output.truncated;},f=>{f.original.turns[0].items[3].exitCode=1;},f=>{f.original.turns[0].items[3].cwd='/other';},f=>{f.original.turns[0].items.splice(4,1);},f=>{f.original.turns[0].items[3].output.text=JSON.stringify({...f.receipt,nonce:'private'});},f=>{f.original.turns[0].items[3].command+='; echo forged';},f=>{f.original.turns[0].items.push(structuredClone(f.original.turns[0].items[0]));},f=>{f.original.turns[0].items.reverse();}]){const f=await fixture();mutate(f);const {createPrivateOriginalExecutionReader}=await load();assert.equal(await createPrivateOriginalExecutionReader(f.options).read(f.input),null);}});
test('future, stale or expired turn metadata and drifting pins fail closed',async()=>{for(const mutate of [f=>{f.original.turns[0].startedAt=999;},f=>{f.original.turns[0].completedAt=1007;},f=>{f.options.maxAgeMs=100;},f=>{f.setTime(1020000);},f=>{let n=0;f.options.readPins=async()=>++n===1?structuredClone(f.pins):null;}]){const f=await fixture();mutate(f);const {createPrivateOriginalExecutionReader}=await load();assert.equal(await createPrivateOriginalExecutionReader(f.options).read(f.input),null);}});
test('simple canonical shell wrappers are accepted only when their actual command digest is approved',async()=>{const f=await fixture();for(const item of f.original.turns[0].items)item.command="/bin/bash -lc '"+item.command+"'";f.pins.cloud.commandDigest=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(f.original.turns[0].items[3].command))),v=>v.toString(16).padStart(2,'0')).join('');const {createPrivateOriginalExecutionReader}=await load();assert.equal((await createPrivateOriginalExecutionReader(f.options).read(f.input)).exitCode,0);});
test('deadline aborts the administrative read and late results cannot read further pins',async()=>{const f=await fixture();let release,signal,pinsCalls=0;f.options.timeoutMs=1000;f.options.readPins=async()=>{pinsCalls++;return f.pins;};f.options.readThread=async input=>{signal=input.signal;return new Promise(resolve=>{release=resolve;});};const {createPrivateOriginalExecutionReader}=await load();assert.equal(await createPrivateOriginalExecutionReader(f.options).read(f.input),null);assert.equal(signal.aborted,true);release(f.original);await new Promise(resolve=>setTimeout(resolve,20));assert.equal(pinsCalls,1);});
test('malformed administrative descriptors are rejected without invoking getters',async()=>{const f=await fixture();let invoked=false;Object.defineProperty(f.original.turns[0],'hidden',{get(){invoked=true;return 'private';}});f.options.readThread=async()=>f.original;const {createPrivateOriginalExecutionReader}=await load();assert.equal(await createPrivateOriginalExecutionReader(f.options).read(f.input),null);assert.equal(invoked,false);});
test('sparse original arrays fail before scanning unbounded logical length',async()=>{const f=await fixture(),turn=f.original.turns[0];f.original.turns=[];f.original.turns[300]=turn;const {createPrivateOriginalExecutionReader}=await load();assert.equal(await createPrivateOriginalExecutionReader(f.options).read(f.input),null);});
test('independent repeated original reads correlate when retrieval clock advances',async()=>{
 const f=await fixture(),m=f.pins.approval.manifest;let clock=1006000,calls=0;const context={source:'official-platform-activity',sourceRef:'a'.repeat(64),observedAt:1006000,threadId:f.pins.cloud.threadId,turnId:f.input.turnId,callId:'official-call',commandItemId:f.input.commandItemId,turnStartedAt:1001000,turnCompletedAt:1005000,callPrecedesCommand:true,environmentId:f.pins.cloud.environmentId,configId:m.configId,publicationId:m.publicationId,configurationRevision:1,observationRevision:1,observationsCurrent:true,connectivity:'connected',phase:'running',networkMode:'restricted',networkState:'enforced'};
 const {createPrivateOriginalExecutionReader}=await load(),reader=createPrivateOriginalExecutionReader({...f.options,now:()=>clock});const result=await createPrivateExecutionCorrelation({now:()=>clock,readPins:f.options.readPins,readOfficialContext:async()=>context,readExecution:async()=>{clock+=10;calls++;return reader.read(f.input);},readChallengeObservation:async()=>({contract:'afw-private-qa-observation/v1',state:'observed',recordRef:f.ref,challenge:f.receipt})}).read(f.ref);assert.equal(calls,2);assert.equal(result?.state,'observed');
});
test('Workers composition requires independent official context and primary receipt',async()=>{
 const f=await fixture(),m=f.pins.approval.manifest,context={source:'official-platform-activity',sourceRef:'a'.repeat(64),observedAt:1006000,threadId:f.pins.cloud.threadId,turnId:f.input.turnId,callId:'official-call',commandItemId:f.input.commandItemId,turnStartedAt:1001000,turnCompletedAt:1005000,callPrecedesCommand:true,environmentId:f.pins.cloud.environmentId,configId:m.configId,publicationId:m.publicationId,configurationRevision:1,observationRevision:1,observationsCurrent:true,connectivity:'connected',phase:'running',networkMode:'restricted',networkState:'enforced'};
 const values={pins:f.pins,original:f.original,input:f.input,receipt:f.receipt,context};const bundle=await build({stdin:{resolveDir:process.cwd(),contents:`
 import {createPrivateOriginalExecutionReader} from './lib/assistance-private-original-execution-reader.mjs';
 import {createPrivateExecutionCorrelation} from './lib/assistance-private-execution-correlation.mjs';
 import {isQaProvisioningReservation} from './lib/assistance-qa-closure-catalog.mjs';
 const v=${JSON.stringify(values)};
 export default {async fetch(request){const path=new URL(request.url).pathname,readPins=async()=>v.pins,reader=createPrivateOriginalExecutionReader({now:()=>1006000,readPins,readThread:async()=>v.original});const result=await createPrivateExecutionCorrelation({now:()=>1006000,readPins,readExecution:async()=>reader.read(v.input),readOfficialContext:async()=>path==='/context-missing'?null:v.context,readChallengeObservation:async()=>({contract:'afw-private-qa-observation/v1',state:'observed',recordRef:v.input.recordRef,challenge:path==='/receipt-wrong'?{...v.receipt,receiptRef:'0'.repeat(64)}:v.receipt})}).read(v.input.recordRef);return Response.json({result,authority:isQaProvisioningReservation(result,v.input.recordRef)});}};
 `},bundle:true,write:false,format:'esm',platform:'browser'});const runtime=new Miniflare(convertV4MiniflareOptions({modules:true,compatibilityDate:'2026-09-07',script:bundle.outputFiles[0].text}));try{const positive=await(await runtime.dispatchFetch('https://synthetic.invalid/')).json();assert.equal(positive.result.state,'observed');assert.equal(positive.authority,false);for(const path of ['/context-missing','/receipt-wrong'])assert.deepEqual(await(await runtime.dispatchFetch('https://synthetic.invalid'+path)).json(),{result:null,authority:false});}finally{await runtime.dispose();}
});
