import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {generateKeyPair,SignJWT} from 'jose';
import {operationsDb} from './fixtures/operations-db.mjs';
import {projectAssistanceSignal} from '../lib/assistance-supervision-contract.mjs';
import {recordAssistanceEvent} from '../lib/assistance-supervision-delivery.mjs';
import {createOperationsServiceControls} from '../lib/operations-service-controls.mjs';
const {privateKey,publicKey}=await generateKeyPair('RS256'),now=Date.now();
const config={enabled:true,origin:'https://operations-manager.agentfriendlyweb.dev',teamDomain:'test.cloudflareaccess.com',audience:'operations-only',clientId:'synthetic-operations.access'};
async function fixture(){const f=operationsDb();for(const name of ['consumer-state','notice-reservations','dossier-supervision','assistance-supervision','assistance-supervision-runs'])f.sqlite.exec(readFileSync('worker/operations/'+name+'.sql','utf8'));const signal=await projectAssistanceSignal({id:'help-'+'a'.repeat(64),projectId:'qa-project',type:'assistance_requested',createdAt:new Date(now).toISOString(),payload:{contract:'afw.assistance-request.v1',requestId:crypto.randomUUID(),expectedRevision:3,topic:'orientation'}},'synthetic-assistance-service-secret-minimum-32');await recordAssistanceEvent(f.db,signal,now);const env={AFW_ASSISTANCE_SUPERVISION_ENABLED:'true',AFW_OPERATIONS_SHARED_ASSISTANCE_BUDGET_ENABLED:'true',AFW_OPERATIONS_WINDOW_EXPIRES_AT:new Date(now+30000).toISOString(),AFW_ASSISTANCE_PROJECT_REFS:JSON.stringify([signal.projectRef])};const token=await new SignJWT({type:'app',common_name:config.clientId}).setProtectedHeader({alg:'RS256'}).setIssuer('https://'+config.teamDomain).setAudience(config.audience).setSubject('').setExpirationTime('5m').sign(privateKey);const handle=(change={},limiter={limit:async()=>({success:true})})=>createOperationsServiceControls({db:f.db,config,keySet:publicKey,now:()=>now,limiter,noticeEnv:{...env,...change}});const request=(path,body,jwt=token)=>new Request(config.origin+path,{method:body?'POST':'GET',headers:{'Cf-Access-Jwt-Assertion':jwt,...(body?{'content-type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});return{...f,signal,handle,request};}
test('service lists only enrolled opaque help and completes a bounded review receipt',async()=>{const f=await fixture(),h=f.handle();assert.deepEqual(await(await h(f.request('/assistance'))).json(),{signals:[f.signal]});const c=await h(f.request('/assistance/claim',{eventId:f.signal.eventId,requestId:crypto.randomUUID()}));assert.equal(c.status,200);const {reservation}=await c.json();assert.equal(reservation.expiresAt,now+30000);assert.deepEqual(await(await h(f.request('/assistance/finish',{runId:reservation.runId,outcome:'reviewed'}))).json(),{outcome:'reviewed'});assert.deepEqual(await(await h(f.request('/assistance'))).json(),{signals:[]});});
test('identity, registration, window, budget opt-in and exact bodies fail closed',async()=>{const f=await fixture();for(const change of [{AFW_ASSISTANCE_SUPERVISION_ENABLED:'false'},{AFW_OPERATIONS_SHARED_ASSISTANCE_BUDGET_ENABLED:'false'},{AFW_ASSISTANCE_PROJECT_REFS:'[]'},{AFW_OPERATIONS_WINDOW_EXPIRES_AT:new Date(now).toISOString()},{AFW_DOSSIER_SUPERVISION_ENABLED:'true'}])assert.equal((await f.handle(change)(f.request('/assistance'))).status,404);const h=f.handle();assert.equal((await h(f.request('/assistance',undefined,'forged'))).status,401);assert.equal((await h(f.request('/incidents'))).status,404);assert.equal((await h(f.request('/dossiers'))).status,404);assert.equal((await h(f.request('/assistance/claim',{eventId:f.signal.eventId,requestId:crypto.randomUUID(),notes:'private'}))).status,400);assert.equal((await h(f.request('/assistance/finish',{runId:crypto.randomUUID(),outcome:'resolved'}))).status,400);assert.equal((await h(new Request(f.request('/assistance'),{headers:{origin:'https://agentfriendlyweb.dev'}}))).status,403);assert.equal(f.sqlite.prepare('SELECT count(*) n FROM assistance_supervision_runs').get().n,0);});
test('window withdrawn during limiter await yields no claim',async()=>{const f=await fixture();const env={AFW_ASSISTANCE_SUPERVISION_ENABLED:'true',AFW_OPERATIONS_SHARED_ASSISTANCE_BUDGET_ENABLED:'true',AFW_ASSISTANCE_PROJECT_REFS:JSON.stringify([f.signal.projectRef]),AFW_OPERATIONS_WINDOW_EXPIRES_AT:new Date(now+30000).toISOString()};const h=createOperationsServiceControls({db:f.db,config,keySet:publicKey,now:()=>now,noticeEnv:env,limiter:{limit:async()=>{env.AFW_ASSISTANCE_SUPERVISION_ENABLED='false';return{success:true};}}});assert.equal((await h(f.request('/assistance/claim',{eventId:f.signal.eventId,requestId:crypto.randomUUID()}))).status,404);assert.equal(f.sqlite.prepare('SELECT count(*) n FROM assistance_supervision_runs').get().n,0);});
