import test from 'node:test';
import assert from 'node:assert/strict';
import {manifest} from './fixtures/occurrence-operations.mjs';
import {qaAdministrationFixture} from './fixtures/qa-administrative-composition.mjs';
import {computeOccurrencePlanDigest} from '../lib/assistance-occurrence-digest.mjs';
import {computeQaClosureBaselineRef,isQaProvisioningReservation} from '../lib/assistance-qa-closure-catalog.mjs';
const load=()=>import('../lib/assistance-private-evidence-journal.mjs');
async function fixture(){const m={...manifest(),startAt:1000,deadline:2000},approval={manifest:m,identityRef:'c'.repeat(64),enrollmentRef:'d'.repeat(64),serverConfigVersion:'e'.repeat(64),planRevision:1};const {registration}=await qaAdministrationFixture({createdAt:1000,closeAt:2000,expiresAt:12000});registration.contract='afw-qa-closure-approval/v2';registration.plan.occurrenceId=m.occurrenceId;registration.approvalDigest=await computeOccurrencePlanDigest({manifest:m,identityRef:approval.identityRef,admissionContract:'server-v1',approval});registration.plan.baselineRef=await computeQaClosureBaselineRef(registration);let values=new Map(),queue=Promise.resolve(),clock=1500;const storage={transaction(fn){const p=queue.then(async()=>{const pending=new Map(values);const result=await fn({get:async key=>structuredClone(pending.get(key)),put:async(key,value)=>pending.set(key,structuredClone(value))});values=pending;return result;});queue=p.catch(()=>{});return p;}};return {pins:{registration,approval},ref:registration.plan.baselineRef,storage,now:()=>clock,setTime:t=>{clock=t;}};}
const evidence=(patch={})=>({kind:'creation',sourceRef:'a'.repeat(64),contentDigest:'b'.repeat(64),observedAt:1400,supersedes:null,...patch});
const headKey=f=>'afw-private-evidence-journal/v1:head:'+f.ref;
const entryKey=(f,sequence)=>'afw-private-evidence-journal/v1:entry:'+f.ref+':'+sequence;
async function mutate(f,key,change){await f.storage.transaction(async tx=>{const value=await tx.get(key);change(value);await tx.put(key,value);});}
test('budget accepts entry 32 and rejects entry 33 without changing history',async()=>{const f=await fixture(),{createPrivateEvidenceJournal}=await load(),actor=createPrivateEvidenceJournal({...f,readPins:async()=>f.pins});for(let sequence=0;sequence<32;sequence++)assert.equal((await actor.append(f.ref,sequence,evidence())).sequence,sequence+1);const before=await actor.history(f.ref);assert.equal(await actor.append(f.ref,32,evidence()),null);assert.deepEqual(await actor.history(f.ref),before);});
test('malformed persisted metadata and broken chain fail closed',async()=>{for(const [type,change] of [['head',h=>{h.extra=true;}],['entry',e=>{e.evidence.contentDigest='f'.repeat(64);}],['entry',e=>{e.previousEntryRef='f'.repeat(64);}]]){const f=await fixture(),{createPrivateEvidenceJournal}=await load(),actor=createPrivateEvidenceJournal({...f,readPins:async()=>f.pins});await actor.append(f.ref,0,evidence());await mutate(f,type==='head'?headKey(f):entryKey(f,1),change);assert.equal(await actor.history(f.ref),null);assert.equal(await actor.append(f.ref,1,evidence()),null);assert.equal(await actor.withdraw(f.ref,1),false);}});
test('append rejects stored head creation time inconsistent with pinned source',async()=>{const f=await fixture(),{createPrivateEvidenceJournal}=await load(),actor=createPrivateEvidenceJournal({...f,readPins:async()=>f.pins});await actor.append(f.ref,0,evidence());await mutate(f,headKey(f),h=>{h.createdAt=999;});const before=await actor.history(f.ref);assert.equal(await actor.append(f.ref,1,evidence()),null);assert.deepEqual(await actor.history(f.ref),before);});
test('historical append after expiry grants no authority and withdrawal remains terminal',async()=>{const f=await fixture(),{createPrivateEvidenceJournal}=await load(),actor=createPrivateEvidenceJournal({...f,readPins:async()=>f.pins});f.setTime(13000);const receipt=await actor.append(f.ref,0,evidence({observedAt:12500}));assert.equal(receipt.state,'recorded');assert.equal(isQaProvisioningReservation(receipt,f.ref),false);assert.equal(await actor.withdraw(f.ref,1),true);assert.equal(await actor.append(f.ref,1,evidence()),null);});
test('backwards live clock and future persisted withdrawal fail closed',async()=>{const f=await fixture(),{createPrivateEvidenceJournal}=await load(),actor=createPrivateEvidenceJournal({...f,readPins:async()=>f.pins});await actor.append(f.ref,0,evidence());f.setTime(1600);assert.equal(await actor.withdraw(f.ref,1),true);f.setTime(1550);assert.equal(await actor.history(f.ref),null);const restarted=createPrivateEvidenceJournal({...f,readPins:async()=>f.pins});assert.equal(await restarted.history(f.ref),null);});
test('CAS append retains originals and correction linkage without certifying references',async()=>{const f=await fixture(),{createPrivateEvidenceJournal}=await load(),actor=createPrivateEvidenceJournal({...f,readPins:async()=>f.pins});const results=await Promise.all([actor.append(f.ref,0,evidence()),actor.append(f.ref,0,evidence({sourceRef:'d'.repeat(64)}))]);assert.equal(results.filter(Boolean).length,1);const first=results.find(Boolean);assert.equal(first.state,'recorded');assert.equal(isQaProvisioningReservation(first,f.ref),false);assert.equal(await actor.append(f.ref,0,evidence()),null);const corrected=await actor.append(f.ref,1,evidence({sourceRef:'e'.repeat(64),supersedes:first.entryRef}));assert.equal(corrected.sequence,2);const history=await actor.history(f.ref);assert.equal(history.entries.length,2);assert.equal(history.entries[0].entryRef,first.entryRef);assert.equal(history.entries[1].previousEntryRef,first.entryRef);assert.equal(history.entries[1].evidence.supersedes,first.entryRef);});
test('malformed or sensitive additions and unrelated corrections never append',async()=>{const f=await fixture(),{createPrivateEvidenceJournal}=await load(),actor=createPrivateEvidenceJournal({...f,readPins:async()=>f.pins});for(const e of [evidence({nonce:'secret'}),evidence({kind:'unrecognized'}),evidence({observedAt:999}),evidence({observedAt:1501}),evidence({supersedes:'c'.repeat(64)})])assert.equal(await actor.append(f.ref,0,e),null);assert.equal(await actor.history(f.ref),null);const first=await actor.append(f.ref,0,evidence());assert.equal(await actor.append(f.ref,1,evidence({kind:'inventory',supersedes:first.entryRef})),null);assert.equal((await actor.history(f.ref)).sequence,1);});
test('withdrawal is terminal and historical reads survive expiry and cleared source',async()=>{const f=await fixture(),{createPrivateEvidenceJournal}=await load();let source=f.pins;const actor=createPrivateEvidenceJournal({...f,readPins:async()=>source});await actor.append(f.ref,0,evidence());assert.equal(await actor.withdraw(f.ref,0),false);assert.equal(await actor.withdraw(f.ref,1),true);assert.equal(await actor.append(f.ref,1,evidence()),null);f.setTime(3000);source=null;const h=await actor.history(f.ref);assert.equal(h.state,'withdrawn');assert.equal(h.entries.length,1);});
test('source drift and a recreated actor with future persisted dates fail closed',async()=>{const f=await fixture(),{createPrivateEvidenceJournal}=await load();let calls=0;const drifting=createPrivateEvidenceJournal({...f,readPins:async()=>{const p=structuredClone(f.pins);if(calls++)p.approval.planRevision++;return p;}});assert.equal(await drifting.append(f.ref,0,evidence()),null);assert.equal(await drifting.history(f.ref),null);const stable=createPrivateEvidenceJournal({...f,readPins:async()=>f.pins});await stable.append(f.ref,0,evidence());f.setTime(1200);const restarted=createPrivateEvidenceJournal({...f,readPins:async()=>f.pins});assert.equal(await restarted.history(f.ref),null);assert.equal(await restarted.withdraw(f.ref,1),false);});
