import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFile} from 'node:fs/promises';
import {projectAssistanceSignal} from '../lib/assistance-supervision-contract.mjs';
const bridge=await import('../lib/assistance-supervision-delivery.mjs').catch(()=>({}));
const now=Date.parse('2026-10-06T17:25:20.817Z'),secret='synthetic-assistance-delivery-secret-minimum-32';
const event={id:'help-'+'a'.repeat(64),projectId:'qa-project',type:'assistance_requested',createdAt:new Date(now).toISOString(),payload:{contract:'afw.assistance-request.v1',requestId:'71821ff8-cf57-41b6-8a4f-58c034e36a2f',expectedRevision:3,topic:'orientation'}};
const required=name=>{assert.equal(typeof bridge[name],'function',name+' implements assistance delivery');return bridge[name];};
function database(sql){const sqlite=new DatabaseSync(':memory:');sqlite.exec(sql);const stmt=(s,a=[])=>({bind:(...v)=>stmt(s,v),first:async()=>sqlite.prepare(s).get(...a)||null,all:async()=>({results:sqlite.prepare(s).all(...a)}),run:async()=>({meta:{changes:sqlite.prepare(s).run(...a).changes}})});return{sqlite,db:{prepare:s=>stmt(s)}};}
async function fixture(){required('createAssistanceProducer');const ledger=database(await readFile('worker/operations/assistance-supervision.sql','utf8'));const source=database('CREATE TABLE site_projects(id TEXT,user_id TEXT);CREATE TABLE project_events(id TEXT,project_id TEXT,user_id TEXT,type TEXT,payload_json TEXT,created_at TEXT);'+await readFile('worker/operations/assistance-delivery-receipts.sql','utf8'));source.sqlite.prepare('INSERT INTO site_projects VALUES(?,?)').run('qa-project','qa-owner');const insert=(id=event.id,owner='qa-owner',payload=event.payload)=>source.sqlite.prepare('INSERT INTO project_events VALUES(?,?,?,?,?,?)').run(id,event.projectId,owner,event.type,JSON.stringify(payload),event.createdAt);insert();const packet=await projectAssistanceSignal(event,secret);const env={AFW_ASSISTANCE_SUPERVISION_ENABLED:'true',AFW_OPERATIONS_WINDOW_EXPIRES_AT:new Date(now+60000).toISOString(),AFW_ASSISTANCE_SIGNING_SECRET:secret,AFW_ASSISTANCE_PROJECT_REFS:JSON.stringify([packet.projectRef]),AFW_ASSISTANCE_ENROLLMENTS:JSON.stringify([{projectId:event.projectId,ownerId:'qa-owner',since:new Date(now-1).toISOString()}]),OPERATIONS_DB:ledger.db,ASSISTANCE_SOURCE_DB:source.db};return {ledger,source,packet,env,insert};}
test('two requests at one revision are delivered independently without private content',async()=>{const f=await fixture();f.insert('help-'+'b'.repeat(64),'qa-owner',{...event.payload,requestId:'81821ff8-cf57-41b6-8a4f-58c034e36a2f'});let body='';const ingress=required('createAssistanceIngress')({now:()=>now});f.env.ASSISTANCE_RECEIVER={fetch:async r=>{body+=await r.clone().text();return ingress.fetch(r,f.env);}};const producer=bridge.createAssistanceProducer({now:()=>now});assert.equal((await producer.run(f.env)).delivered,2);assert.equal((await producer.run(f.env)).delivered,0);assert.doesNotMatch(body,/qa-project|qa-owner|help-|71821ff8/);assert.equal(f.ledger.sqlite.prepare('SELECT count(*) n FROM assistance_supervision_events').get().n,2);assert.equal(f.source.sqlite.prepare('SELECT count(*) n FROM assistance_delivery_receipts').get().n,2);});
test('lost response leaves source unacknowledged and replay recovers one receiver event',async()=>{const f=await fixture();let lose=true;const ingress=required('createAssistanceIngress')({now:()=>now});f.env.ASSISTANCE_RECEIVER={fetch:async r=>{const response=await ingress.fetch(r,f.env);if(lose){lose=false;throw Error('lost');}return response;}};const producer=bridge.createAssistanceProducer({now:()=>now});assert.equal((await producer.run(f.env)).delivered,0);assert.equal(f.source.sqlite.prepare('SELECT count(*) n FROM assistance_delivery_receipts').get().n,0);assert.equal((await producer.run(f.env)).delivered,1);assert.equal(f.ledger.sqlite.prepare('SELECT count(*) n FROM assistance_supervision_events').get().n,1);assert.equal(f.source.sqlite.prepare('SELECT payload_json FROM project_events').get().payload_json,JSON.stringify(event.payload));});
test('owner, flag, registration and expired window fence all source reads and transport',async()=>{const f=await fixture();let calls=0;f.env.ASSISTANCE_RECEIVER={fetch:async()=>{calls++;throw Error('unexpected');}};for(const change of [{AFW_ASSISTANCE_SUPERVISION_ENABLED:'false'},{AFW_ASSISTANCE_ENROLLMENTS:'[]'},{AFW_OPERATIONS_WINDOW_EXPIRES_AT:new Date(now).toISOString()},{AFW_ASSISTANCE_ENROLLMENTS:JSON.stringify([{projectId:'qa-project',ownerId:'foreign',since:new Date(now-1).toISOString()}])}])await bridge.createAssistanceProducer({now:()=>now}).run({...f.env,...change});assert.equal(calls,0);});
test('forged signature, browser origin and unregistered project do not persist',async()=>{const f=await fixture();const ingress=required('createAssistanceIngress')({now:()=>now});const sign=required('signedAssistanceRequest');const request=await sign(f.packet,secret,now);assert.equal((await ingress.fetch(new Request(request,{headers:{...Object.fromEntries(request.headers),'x-afw-signature':'0'.repeat(64)}}),f.env)).status,401);assert.equal((await ingress.fetch(new Request(await sign(f.packet,secret,now),{headers:{...Object.fromEntries(request.headers),origin:'https://agentfriendlyweb.dev'}}),f.env)).status,403);assert.equal((await ingress.fetch(await sign(f.packet,secret,now),{...f.env,AFW_ASSISTANCE_PROJECT_REFS:'[]'})).status,403);assert.equal(f.ledger.sqlite.prepare('SELECT count(*) n FROM assistance_supervision_events').get().n,0);});
test('closing during transport or source query prevents further delivery acknowledgement',async()=>{const f=await fixture();let clock=now;const ingress=required('createAssistanceIngress')({now:()=>clock});f.env.ASSISTANCE_RECEIVER={fetch:async r=>{const response=await ingress.fetch(r,f.env);clock=now+60001;return response;}};assert.equal((await bridge.createAssistanceProducer({now:()=>clock}).run(f.env)).delivered,0);assert.equal(f.source.sqlite.prepare('SELECT count(*) n FROM assistance_delivery_receipts').get().n,0);});
test('unexpected response cannot acknowledge delivery; collision cannot rewrite a receipt',async()=>{const f=await fixture();f.env.ASSISTANCE_RECEIVER={fetch:async()=>Response.json({version:'afw-assistance-receipt-v1',eventId:'0'.repeat(64),duplicate:false},{status:202})};assert.equal((await bridge.createAssistanceProducer({now:()=>now}).run(f.env)).delivered,0);assert.equal(f.source.sqlite.prepare('SELECT count(*) n FROM assistance_delivery_receipts').get().n,0);const record=required('recordAssistanceEvent');await record(f.ledger.db,f.packet,now);await assert.rejects(record(f.ledger.db,{...f.packet,topic:'delivery'},now),/collision/);});
test('malformed source payload and foreign event owner cannot become signals',async()=>{const f=await fixture();f.source.sqlite.prepare('UPDATE project_events SET user_id=?').run('foreign');f.insert('help-'+'c'.repeat(64),'qa-owner',{...event.payload,notes:'PRIVATE'});let calls=0;f.env.ASSISTANCE_RECEIVER={fetch:async()=>{calls++;throw Error('unexpected');}};await bridge.createAssistanceProducer({now:()=>now}).run(f.env);assert.equal(calls,0);});
test('ownership changed after selection prevents transport; changed during delivery prevents ack',async()=>{const f=await fixture();const original=f.source.db.prepare;f.env.ASSISTANCE_SOURCE_DB={prepare:sql=>{const stmt=original(sql);if(!sql.startsWith('SELECT e.id'))return stmt;return{bind:(...args)=>{const bound=stmt.bind(...args);return{all:async()=>{const rows=await bound.all();f.source.sqlite.prepare('UPDATE site_projects SET user_id=?').run('foreign');return rows;}};}};}};let calls=0;f.env.ASSISTANCE_RECEIVER={fetch:async()=>{calls++;throw Error('unexpected');}};await bridge.createAssistanceProducer({now:()=>now}).run(f.env);assert.equal(calls,0);const g=await fixture();const ingress=bridge.createAssistanceIngress({now:()=>now});g.env.ASSISTANCE_RECEIVER={fetch:async r=>{const response=await ingress.fetch(r,g.env);g.source.sqlite.prepare('UPDATE site_projects SET user_id=?').run('foreign');return response;}};assert.equal((await bridge.createAssistanceProducer({now:()=>now}).run(g.env)).delivered,0);assert.equal(g.source.sqlite.prepare('SELECT count(*) n FROM assistance_delivery_receipts').get().n,0);});
test('delivery batch is bounded across runs and does not permanently skip later requests',async()=>{const f=await fixture();for(const letter of ['b','c','d','e'])f.insert('help-'+letter.repeat(64),'qa-owner',{...event.payload,requestId:crypto.randomUUID()});const ingress=bridge.createAssistanceIngress({now:()=>now});f.env.ASSISTANCE_RECEIVER={fetch:r=>ingress.fetch(r,f.env)};const producer=bridge.createAssistanceProducer({now:()=>now});assert.equal((await producer.run(f.env)).delivered,3);assert.equal((await producer.run(f.env)).delivered,2);assert.equal((await producer.run(f.env)).delivered,0);});
test('invalid route, method, media type and excessive body stay bounded and write nothing',async()=>{const f=await fixture();const ingress=bridge.createAssistanceIngress({now:()=>now});const signed=await bridge.signedAssistanceRequest(f.packet,secret,now);for(const [request,status] of [[new Request('https://operations.agentfriendlyweb.dev/assistance-events?extra=1',{method:'POST'}),404],[new Request('https://operations.agentfriendlyweb.dev/assistance-events'),405],[new Request(signed,{headers:{...Object.fromEntries(signed.headers),'content-type':'text/plain'}}),415],[new Request(signed,{body:'x'.repeat(2048)}),503]])assert.equal((await ingress.fetch(request,f.env)).status,status);assert.equal(f.ledger.sqlite.prepare('SELECT count(*) n FROM assistance_supervision_events').get().n,0);await assert.rejects(bridge.recordAssistanceEvent(f.ledger.db,{...f.packet,observedAt:new Date(now+300001).toISOString()},now));});
test('journal type or timestamp changed during delivery cannot be acknowledged',async()=>{for(const change of ["type='project_updated'","created_at='2026-10-07T00:00:00.000Z'"]){const f=await fixture();const ingress=bridge.createAssistanceIngress({now:()=>now});f.env.ASSISTANCE_RECEIVER={fetch:async r=>{const response=await ingress.fetch(r,f.env);f.source.sqlite.exec('UPDATE project_events SET '+change);return response;}};assert.equal((await bridge.createAssistanceProducer({now:()=>now}).run(f.env)).delivered,0);assert.equal(f.source.sqlite.prepare('SELECT count(*) n FROM assistance_delivery_receipts').get().n,0);}});
