import test from 'node:test';
import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {Miniflare,convertV4MiniflareOptions} from 'miniflare';
import {manifest} from './fixtures/occurrence-operations.mjs';
import {qaAdministrationFixture} from './fixtures/qa-administrative-composition.mjs';
import {computeOccurrencePlanDigest} from '../lib/assistance-occurrence-digest.mjs';
import {computeQaClosureBaselineRef,isQaProvisioningReservation} from '../lib/assistance-qa-closure-catalog.mjs';
const load=()=>import('../lib/assistance-private-execution-correlation.mjs');
async function fixture(){
 const m={...manifest(),startAt:1000,deadline:12000},approval={manifest:m,identityRef:'c'.repeat(64),enrollmentRef:'d'.repeat(64),serverConfigVersion:'e'.repeat(64),planRevision:1};
 const {registration}=await qaAdministrationFixture({createdAt:1000,closeAt:12000,expiresAt:23000});registration.contract='afw-qa-closure-approval/v2';registration.plan.occurrenceId=m.occurrenceId;registration.approvalDigest=await computeOccurrencePlanDigest({manifest:m,identityRef:approval.identityRef,admissionContract:'server-v1',approval});registration.plan.baselineRef=await computeQaClosureBaselineRef(registration);
 const threadId='11111111-1111-4111-8111-111111111111',turnId='22222222-2222-4222-8222-222222222222',ref=registration.plan.baselineRef,receiptRef='f'.repeat(64);
 const pins={registration,approval,cloud:{threadId,environmentId:'ccarenv_synthetic',cwd:'/workspace',commandDigest:'9'.repeat(64)}};
 const context={source:'official-platform-activity',sourceRef:'1'.repeat(64),observedAt:5000,threadId,turnId,callId:'exec-synthetic-context',commandItemId:'exec-synthetic-command',turnStartedAt:1800,turnCompletedAt:4500,callPrecedesCommand:true,environmentId:pins.cloud.environmentId,configId:m.configId,publicationId:m.publicationId,configurationRevision:6,observationRevision:6,observationsCurrent:true,connectivity:'connected',phase:'running',networkMode:'restricted',networkState:'enforced'};
 const execution={source:'official-thread-command',sourceRef:'2'.repeat(64),observedAt:5000,threadId,turnId,commandItemId:'exec-synthetic-command',commandDigest:pins.cloud.commandDigest,cwd:'/workspace',turnStartedAt:1800,turnCompletedAt:4500,exitCode:0,sourceRevision:m.sourceRevision,origin:'https://github.com/tokenizartinfo-ops/agent-friendly-web.git',checkoutClean:true,recordRef:ref,receiptRef};
 const observation={contract:'afw-private-qa-observation/v1',state:'observed',recordRef:ref,challenge:{contract:'afw-private-custody-challenge/v1',state:'confirmed',recordRef:ref,receiptRef,issuedAt:3000,deadline:12000,consumedAt:4000}};
 let clock=5500;const calls=[];const options={now:()=>clock,maxAgeMs:10000,readPins:async()=>{calls.push('pins');return structuredClone(pins);},readOfficialContext:async()=>{calls.push('context');return structuredClone(context);},readExecution:async()=>{calls.push('execution');return structuredClone(execution);},readChallengeObservation:async()=>{calls.push('challenge');return structuredClone(observation);}};
 return {pins,context,execution,observation,ref,options,calls,setTime:t=>{clock=t;}};
}
test('private correlation matches independent originals and primary receipt without provisioning authority',async()=>{const f=await fixture(),{createPrivateExecutionCorrelation}=await load(),value=await createPrivateExecutionCorrelation(f.options).read(f.ref);assert.equal(value.state,'observed');assert.equal(value.recordRef,f.ref);assert.equal(value.receiptRef,f.observation.challenge.receiptRef);assert.deepEqual(value.sourceRefs,{context:f.context.sourceRef,execution:f.execution.sourceRef});assert.equal(isQaProvisioningReservation(value,f.ref),false);assert.equal(f.calls.length,10);assert.ok(!JSON.stringify(value).includes('commandItemId'));});
test('missing, mismatched, sensitive or untrusted-source metadata never correlates',async()=>{for(const mutate of [f=>{f.context.source='client-report';},f=>{f.execution.source='stdout';},f=>{f.context.turnId='33333333-3333-4333-8333-333333333333';},f=>{f.context.environmentId='ccarenv_other';},f=>{f.context.threadId='33333333-3333-4333-8333-333333333333';},f=>{f.context.publicationId='cecfgver_other';},f=>{f.context.configurationRevision++;},f=>{f.execution.sourceRevision='0'.repeat(40);},f=>{f.execution.commandDigest='0'.repeat(64);},f=>{f.execution.checkoutClean=false;},f=>{f.execution.exitCode=1;},f=>{f.execution.cwd='/other';},f=>{f.execution.receiptRef='0'.repeat(64);},f=>{f.observation.challenge.state='withdrawn';},f=>{f.observation.challenge=null;},f=>{f.execution.nonce='secret';},f=>{delete f.context.callId;}]){const f=await fixture();mutate(f);const {createPrivateExecutionCorrelation}=await load();assert.equal(await createPrivateExecutionCorrelation(f.options).read(f.ref),null);}});
test('stale, future, expired or incompatible primary and turn dates fail closed',async()=>{for(const mutate of [f=>{f.options.maxAgeMs=1000;},f=>{f.context.observedAt=1600;},f=>{f.context.observedAt=6000;},f=>{f.execution.turnCompletedAt=3500;},f=>{f.execution.turnStartedAt=3500;},f=>{f.context.observedAt=3500;},f=>{f.execution.observedAt=4400;},f=>{f.observation.challenge.deadline--;},f=>{f.observation.challenge.consumedAt=12000;},f=>{f.setTime(12000);}]){const f=await fixture();mutate(f);const {createPrivateExecutionCorrelation}=await load();assert.equal(await createPrivateExecutionCorrelation(f.options).read(f.ref),null);}});
test('drift or withdrawal on the second snapshot cannot return accepted correlation',async()=>{for(const source of ['readPins','readOfficialContext','readExecution','readChallengeObservation']){const f=await fixture(),original=f.options[source];let calls=0;f.options[source]=async()=>{const value=await original();if(++calls===2){if(source==='readPins')return null;if(source==='readChallengeObservation')value.challenge.state='withdrawn';else value.sourceRef='0'.repeat(64);}return value;};const {createPrivateExecutionCorrelation}=await load();assert.equal(await createPrivateExecutionCorrelation(f.options).read(f.ref),null);}});
test('a stalled administrative reader is aborted and late completion dispatches no further sources',async()=>{const f=await fixture();let release,signal;f.options.timeoutMs=50;f.options.readOfficialContext=async input=>{signal=input.signal;return new Promise(resolve=>{release=resolve;});};const {createPrivateExecutionCorrelation}=await load();assert.equal(await createPrivateExecutionCorrelation(f.options).read(f.ref),null);assert.equal(signal.aborted,true);release(f.context);await new Promise(resolve=>setTimeout(resolve,20));assert.deepEqual(f.calls,['pins']);});
test('hidden metadata is rejected without invoking accessors; withdrawal during final source read is observed',async()=>{const {createPrivateExecutionCorrelation}=await load();const f=await fixture();let invoked=false;Object.defineProperty(f.context,'secret',{get(){invoked=true;return 'private';},enumerable:false});f.options.readOfficialContext=async()=>f.context;assert.equal(await createPrivateExecutionCorrelation(f.options).read(f.ref),null);assert.equal(invoked,false);const g=await fixture(),read=g.options.readChallengeObservation;let withdrawn=false;g.options.readPins=async()=>withdrawn?null:structuredClone(g.pins);g.options.readChallengeObservation=async()=>{const result=await read();withdrawn=true;return result;};assert.equal(await createPrivateExecutionCorrelation(g.options).read(g.ref),null);});
test('Workers runtime enforces correlation and rejects primary withdrawal without authority',async()=>{const f=await fixture(),values={pins:f.pins,context:f.context,execution:f.execution,observation:f.observation,ref:f.ref};const bundle=await build({stdin:{resolveDir:process.cwd(),contents:`
 import {createPrivateExecutionCorrelation} from './lib/assistance-private-execution-correlation.mjs';
 import {isQaProvisioningReservation} from './lib/assistance-qa-closure-catalog.mjs';
 const values=${JSON.stringify(values)};
 export default {async fetch(request){const withdrawn=new URL(request.url).pathname==='/withdrawn';const result=await createPrivateExecutionCorrelation({now:()=>5500,maxAgeMs:10000,readPins:async()=>values.pins,readOfficialContext:async()=>values.context,readExecution:async()=>values.execution,readChallengeObservation:async()=>withdrawn?{...values.observation,challenge:{...values.observation.challenge,state:'withdrawn'}}:values.observation}).read(values.ref);return Response.json({result,authority:isQaProvisioningReservation(result,values.ref)});}};
 `},bundle:true,write:false,format:'esm',platform:'browser'});const runtime=new Miniflare(convertV4MiniflareOptions({modules:true,compatibilityDate:'2026-09-07',script:bundle.outputFiles[0].text}));try{const accepted=await(await runtime.dispatchFetch('https://synthetic.invalid/')).json();assert.equal(accepted.result.state,'observed');assert.equal(accepted.authority,false);assert.deepEqual(await(await runtime.dispatchFetch('https://synthetic.invalid/withdrawn')).json(),{result:null,authority:false});}finally{await runtime.dispose();}});
