import test from 'node:test';
import assert from 'node:assert/strict';
import {qaAdministrationFixture} from './fixtures/qa-administrative-composition.mjs';
import {createQaAdministrativeClosureActions} from '../lib/assistance-qa-administrative-composition.mjs';
import {createIndependentClosureCoordinator} from '../lib/assistance-independent-closure.mjs';
import {createAdministrativeGetTransport} from '../lib/assistance-administrative-get-transport.mjs';
import {createServiceIdentityTransport} from '../lib/assistance-service-identity-transport.mjs';
const unknown={verified:false,state:'unknown'};
test('both private transports cancel a stalled inventory body at their parent deadline',async()=>{for(const kind of ['administrative','identity']){const f=await qaAdministrationFixture();let cancelled=false;const options={readCredential:async()=> 'synthetic-private-placeholder',timeoutMs:1000,fetchImpl:async url=>{if(new URL(url).pathname.endsWith('/access/service_tokens'))return new Response(new ReadableStream({cancel(){cancelled=true;}}),{headers:{'Content-Type':'application/json'}});const token=structuredClone(f.results.token);delete token.name;return Response.json({success:true,result:token});}};const transport=kind==='administrative'?createAdministrativeGetTransport({...options,resources:f.registration.resources}):createServiceIdentityTransport({...options,identity:{accountId:f.registration.resources.accountId,tokenId:f.registration.resources.tokenId,name:f.results.token.name,exclusiveQa:true},closeAt:f.registration.plan.closeAt,now:f.options.now});assert.deepEqual(await transport({method:'GET',path:'/accounts/'+f.registration.resources.accountId+'/access/service_tokens/'+f.results.token.id}),{success:false});assert.equal(cancelled,true,kind+' fallback body cancelled');}});
async function fixture(change=()=>{}){const f=await qaAdministrationFixture();const original=f.options.fetchImpl;f.options.fetchImpl=async(url,init)=>{const target=new URL(url);if(target.pathname.endsWith('/access/service_tokens')){f.calls.push({path:target.pathname,method:init.method,query:target.search});const payload={success:true,result:[structuredClone(f.results.token)],result_info:{page:1,per_page:100,count:1,total_count:1,total_pages:1}};change(payload,f);return Response.json(payload);}const response=await original(url,init);if(init.method==='GET'&&target.pathname.includes('/access/service_tokens/')){const payload=await response.json();delete payload.result.name;return Response.json(payload);}return response;};return f;}
test('whole administrative closure verifies nameless point GET against listed metadata',async()=>{const f=await fixture(),actions=await createQaAdministrativeClosureActions(f.options);assert.deepEqual(await actions.restoreAdministration(f.registration.plan),{verified:true,state:'restored'});assert.equal(f.calls.filter(c=>c.method==='PUT').length,1);assert.ok(f.calls.some(c=>c.query==='?page=1&per_page=100'));assert.deepEqual(await actions.readIssuedReceipt({...f.registration.plan,step:'restoreAdministration'}),{verified:true,state:'restored'});assert.equal(f.calls.filter(c=>c.method==='PUT').length,1);});
test('name, version, state and incomplete or duplicate inventory differences never issue PUT',async()=>{for(const change of [p=>{p.result[0].name='changed-by-owner';},p=>{p.result[0].client_secret_version++;},p=>{p.result[0].enabled=false;},p=>{delete p.result_info;},p=>{p.result_info.total_count=2;},p=>{p.result.push(p.result[0]);p.result_info.count=2;p.result_info.total_count=2;}]){const f=await fixture(change),a=await createQaAdministrativeClosureActions(f.options);assert.deepEqual(await a.restoreAdministration(f.registration.plan),unknown);assert.equal(f.calls.filter(c=>c.method==='PUT').length,0);}});
test('withdrawal during inventory read blocks the subsequent provider write',async()=>{const f=await fixture((_p,f)=>f.setApproved(false)),a=await createQaAdministrativeClosureActions(f.options);assert.deepEqual(await a.restoreAdministration(f.registration.plan),unknown);assert.equal(f.calls.filter(c=>c.method==='PUT').length,0);});
test('lost PUT acknowledgment reconciles nameless metadata without a second write',async()=>{const f=await fixture();f.loseAck();let values=new Map(),tail=Promise.resolve();const storage={transaction(fn){const job=tail.then(async()=>{const draft=new Map(structuredClone([...values]));const value=await fn({get:async k=>structuredClone(draft.get(k)),put:async(k,v)=>draft.set(k,structuredClone(v))});values=draft;return value;});tail=job.catch(()=>{});return job;}};const make=async()=>createIndependentClosureCoordinator({storage,plan:f.registration.plan,now:f.options.now,revokePlan:async()=>({verified:true,state:'revoked'}),closeLedger:async()=>({verified:true,state:'stopped'}),...await createQaAdministrativeClosureActions(f.options)});assert.deepEqual(await(await make()).tick(),{state:'intervention_required',step:'restoreAdministration'});assert.equal(f.calls.filter(c=>c.method==='PUT').length,1);assert.deepEqual(await(await make()).tick(),{state:'intervention_required',step:'restoreAdministration'});assert.deepEqual(await(await make()).reconcile(),{state:'complete',step:null});assert.equal(f.calls.filter(c=>c.method==='PUT').length,1);});
test('second inventory page is read completely before resolving the exact token',async()=>{const f=await fixture(),original=f.options.fetchImpl;f.options.fetchImpl=async(url,init)=>{const response=await original(url,init),target=new URL(url);if(!target.pathname.endsWith('/access/service_tokens'))return response;const page=Number(target.searchParams.get('page'));return Response.json({success:true,result:page===1?[{id:'99999999-9999-4999-8999-999999999999'}]:[structuredClone(f.results.token)],result_info:{page,per_page:100,count:1,total_count:2,total_pages:2}});};assert.deepEqual(await(await createQaAdministrativeClosureActions(f.options)).restoreAdministration(f.registration.plan),{verified:true,state:'restored'});assert.ok(f.calls.some(c=>c.query==='?page=2&per_page=100'));});
