import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {Miniflare,convertV4MiniflareOptions} from 'miniflare';
import {generateKeyPair,SignJWT} from 'jose';
import {manifest,observation,schemas,sqlStatements} from './fixtures/occurrence-operations.mjs';
import {createOccurrenceHttpAdapter,computeOccurrenceServerConfigVersion} from '../lib/assistance-occurrence-http.mjs';
import {computeOccurrencePlanDigest} from '../lib/assistance-occurrence-digest.mjs';
import {createOccurrenceApprovalCatalog} from '../lib/assistance-occurrence-approvals.mjs';
import {runAssistanceHttpOccurrence} from '../lib/assistance-http-occurrence.mjs';
test('native standalone six-HTTP runner terminal, replay/legacy veto and revoked claim atomic rollback',async()=>{
 const runtime=new Miniflare(convertV4MiniflareOptions({modules:true,compatibilityDate:'2026-09-07',script:'export default {fetch(){return new Response(null,{status:404});}}',d1Databases:{DB:'http-occurrence-native',OTHER:'http-occurrence-native'}}));
 try{const db=await runtime.getD1Database('DB'),other=await runtime.getD1Database('OTHER');for(const name of schemas)for(const sql of sqlStatements(readFileSync('worker/operations/'+name+'.sql','utf8')))await db.prepare(sql).run();for(const name of ['assistance-occurrences-v2','assistance-occurrences-v2-reservation-fence']){const parts=sqlStatements(readFileSync('worker/operations/'+name+'.sql','utf8'));const drop=parts.find(s=>s.startsWith('DROP TRIGGER')),pin=parts.find(s=>s.startsWith('INSERT INTO assistance_occurrence_'));await db.batch([...(drop?[drop]:[]),...parts.filter(s=>s!==drop&&s!==pin),pin].map(s=>db.prepare(s)));}
 const {privateKey,publicKey}=await generateKeyPair('RS256'),m=manifest(),origin='https://operations-manager.agentfriendlyweb.dev';
 const policy={mode:'QA_OCCURRENCE_EXCLUSIVE',auth:{enabled:true,origin,teamDomain:'test.cloudflareaccess.com',audience:'qa-native',clientId:'synthetic-native.access'},principalRef:'c'.repeat(64),enrollments:[{enrollmentRef:'d'.repeat(64),projectRef:m.signal.projectRef}],serverConfigVersion:'0'.repeat(64),admissionRevision:1,serverDeadline:m.serverDeadline,qaBindingRef:'f'.repeat(64)};policy.serverConfigVersion=await computeOccurrenceServerConfigVersion(policy);
 const jwt=await new SignJWT({type:'app',common_name:policy.auth.clientId}).setProtectedHeader({alg:'RS256'}).setIssuer('https://'+policy.auth.teamDomain).setAudience(policy.auth.audience).setSubject('').setExpirationTime('5m').sign(privateKey),catalog=createOccurrenceApprovalCatalog({db:other});
 const approval=model=>({manifest:model,identityRef:policy.principalRef,enrollmentRef:policy.enrollments[0].enrollmentRef,serverConfigVersion:policy.serverConfigVersion,planRevision:1});
 const signal=async model=>db.prepare('INSERT INTO assistance_supervision_events VALUES(?,?,?,?,?,?,?)').bind(model.signal.eventId,model.signal.projectRef,model.signal.revision,model.signal.kind,model.signal.topic,model.signal.observedAt,Date.now()).run();await signal(m);assert.equal(await catalog.approve(approval(m)),true);
 let effective=policy;const options={db,readPolicy:()=>effective,keySet:publicKey,limiter:{limit:async()=>({success:true})}},handler=createOccurrenceHttpAdapter(options),requests=[];
 const send=async req=>{requests.push(new URL(req.url).pathname);const headers=new Headers(req.headers);headers.set('Cf-Access-Jwt-Assertion',jwt);return handler(new Request(req,{headers}));};
 const result=await runAssistanceHttpOccurrence({manifest:m,planDigest:await computeOccurrencePlanDigest({manifest:m,identityRef:policy.principalRef,admissionContract:'server-v1',approval:approval(m)}),preflight:async()=>({...observation(m,Date.now()-100),checkoutClean:true}),env:{AFW_OPERATIONS_ACCESS_CLIENT_ID:'synthetic-id',AFW_OPERATIONS_ACCESS_CLIENT_SECRET:'synthetic-secret'},fetchImpl:send});assert.equal(result.status,'completed');assert.equal(requests.length,6);assert.equal(result.outcome,'intervention_required');assert.equal((await other.prepare('SELECT count(*) n FROM assistance_supervision_runs').first()).n,1);
 const req=(suffix,body)=>new Request(origin+'/assistance/occurrences/'+suffix,{method:'POST',headers:{'content-type':'application/json','Cf-Access-Jwt-Assertion':jwt},body:JSON.stringify(body)});
 assert.equal((await handler(req('claim',{occurrenceId:m.occurrenceId,expectedSequence:3}))).status,409);assert.equal((await handler(new Request(origin+'/assistance',{headers:{'Cf-Access-Jwt-Assertion':jwt}}))).status,404);
 const m2={...m,occurrenceId:crypto.randomUUID(),requestId:crypto.randomUUID(),signal:{...m.signal,eventId:'1'.repeat(64),revision:11}};await signal(m2);assert.equal(await catalog.approve(approval(m2)),true);for(const [phase,seq] of [['create',undefined],['list',1],['admit-claim',2]])assert.equal((await handler(req(phase,{occurrenceId:m2.occurrenceId,...(seq?{expectedSequence:seq}:{})}))).status,200,'setup '+phase);
 const queued={prepare:s=>other.prepare(s),batch:async ss=>{assert.equal(await catalog.revoke({occurrenceId:m2.occurrenceId,reason:'security_denied'}),true);return other.batch(ss);}};const revoked=createOccurrenceHttpAdapter({...options,db:queued});assert.equal((await revoked(req('claim',{occurrenceId:m2.occurrenceId,expectedSequence:3}))).status,409);assert.equal((await db.prepare('SELECT count(*) n FROM assistance_supervision_runs').first()).n,1);assert.equal((await db.prepare('SELECT max(sequence) n FROM assistance_occurrence_journal WHERE occurrence_id=?').bind(m2.occurrenceId).first()).n,3);
 const stopDb={prepare:s=>{const stmt=other.prepare(s);if(s.startsWith('SELECT * FROM assistance_occurrence_journal'))return {bind:(...v)=>{const bound=stmt.bind(...v);return {first:async()=>{const row=await bound.first();effective={...policy,mode:'QA_OFF'};return row;}};}};return stmt;},batch:ss=>other.batch(ss)};
 assert.equal((await createOccurrenceHttpAdapter({...options,db:stopDb})(req('stop',{occurrenceId:m2.occurrenceId,reason:'operator_closed'}))).status,409);assert.equal((await db.prepare("SELECT count(*) n FROM assistance_occurrence_journal WHERE occurrence_id=? AND state='stopped'").bind(m2.occurrenceId).first()).n,0);effective=policy;assert.equal((await handler(req('stop',{occurrenceId:m2.occurrenceId,reason:'operator_closed'}))).status,200);

 }finally{await runtime.dispose();}
});
