import test from 'node:test';
import assert from 'node:assert/strict';
import {Miniflare,convertV4MiniflareOptions} from 'miniflare';
import {readFileSync} from 'node:fs';
import {manifest,observation,schemas,sqlStatements} from './fixtures/occurrence-operations.mjs';
import {createOccurrenceApprovalCatalog} from '../lib/assistance-occurrence-approvals.mjs';
import {createOccurrenceOperations} from '../lib/assistance-occurrence-operations.mjs';
test('native two-client server admission, revocation after lookup rollback and independent stop',async()=>{
 const runtime=new Miniflare(convertV4MiniflareOptions({modules:true,compatibilityDate:'2026-09-07',script:'export default {fetch(){return new Response(null,{status:404});}}',d1Databases:{DB:'server-admission-native',OTHER:'server-admission-native'}}));
 try{const db=await runtime.getD1Database('DB'),other=await runtime.getD1Database('OTHER');for(const name of schemas)for(const sql of sqlStatements(readFileSync('worker/operations/'+name+'.sql','utf8')))await db.prepare(sql).run();
 // sqlite_master ordering in native loader: tables before triggers. Install explicit migration in one batch with marker INSERT last.
 const statements=sqlStatements(readFileSync('worker/operations/assistance-occurrences-v2.sql','utf8'));const marker=statements.find(s=>s.startsWith('INSERT INTO assistance_occurrence_schema'));await db.batch([...statements.filter(s=>s!==marker),marker].map(s=>db.prepare(s)));
 // Fixture parser groups triggers last: drop old trigger first and commit marker after replacement.
 const fence=sqlStatements(readFileSync('worker/operations/assistance-occurrences-v2-reservation-fence.sql','utf8'));const drop=fence.find(s=>s.startsWith('DROP TRIGGER')),pin=fence.find(s=>s.startsWith('INSERT INTO assistance_occurrence_reservation_fence'));await db.batch([drop,...fence.filter(s=>s!==drop&&s!==pin),pin].map(s=>db.prepare(s)));
 const m=manifest(),identityRef='c'.repeat(64),enrollmentRef='d'.repeat(64),serverConfigVersion='e'.repeat(64),approval={manifest:m,identityRef,enrollmentRef,serverConfigVersion,planRevision:1};
 await db.prepare('INSERT INTO assistance_supervision_events VALUES(?,?,?,?,?,?,?)').bind(m.signal.eventId,m.signal.projectRef,m.signal.revision,m.signal.kind,m.signal.topic,m.signal.observedAt,Date.now()).run();
 const c=createOccurrenceApprovalCatalog({db:other});assert.equal(await c.approve(approval),true);
 const options=database=>({db:database,manifest:m,identityRef,admissionContract:'server-v1',approval,readServerAdmission:async()=>({contractVersion:'afw-server-admission-v1',identityRef,enrollmentRef,serverConfigVersion,planRevision:1,admissionRevision:1,observedAt:Date.now()-100,schemaVersion:2})});
 const alias={...m,occurrenceId:crypto.randomUUID(),requestId:crypto.randomUUID()};const cloudAlias=createOccurrenceOperations({db:other,manifest:alias,identityRef,preflight:async()=>observation(alias,Date.now())});assert.equal(await cloudAlias.create(),false);assert.equal((await db.prepare('SELECT count(*) n FROM assistance_occurrences').first()).n,0);
 const a=createOccurrenceOperations(options(db)),b=createOccurrenceOperations(options(other));assert.equal((await Promise.all([a.create(),b.create()])).filter(Boolean).length,1);assert.deepEqual(await a.list({expectedSequence:1}),[m.signal]);await a.admit({expectedSequence:2,phase:'claim'});
 const delayed={prepare:s=>db.prepare(s),batch:async ss=>{assert.equal(await c.revoke({occurrenceId:m.occurrenceId,reason:'security_denied'}),true);return db.batch(ss);}};
 assert.equal(await createOccurrenceOperations(options(delayed)).claim({expectedSequence:3}),null);assert.equal((await db.prepare('SELECT count(*) n FROM assistance_supervision_runs').first()).n,0);assert.equal((await db.prepare('SELECT max(sequence) n FROM assistance_occurrence_journal').first()).n,3);assert.equal(await b.close({reason:'operator_closed'}),true);assert.equal((await c.read(m.occurrenceId)).revoked,true);assert.equal(await cloudAlias.create(),false);
 const m2={...m,occurrenceId:crypto.randomUUID(),requestId:crypto.randomUUID(),signal:{...m.signal,eventId:'f'.repeat(64),projectRef:'1'.repeat(64)}};await db.prepare('INSERT INTO assistance_supervision_events VALUES(?,?,?,?,?,?,?)').bind(m2.signal.eventId,m2.signal.projectRef,m2.signal.revision,m2.signal.kind,m2.signal.topic,m2.signal.observedAt,Date.now()).run();const cloud=createOccurrenceOperations({db,manifest:m2,identityRef,preflight:async()=>observation(m2,Date.now())});assert.equal(await cloud.create(),true);assert.equal(await c.approve({...approval,manifest:m2}),false);assert.equal(await cloud.close({reason:'operator_closed'}),true);
 }finally{await runtime.dispose();}
});
test('native migration denies work on historical alias but preserves independent close',async()=>{
 const runtime=new Miniflare(convertV4MiniflareOptions({modules:true,compatibilityDate:'2026-09-07',script:'export default {fetch(){return new Response(null,{status:404});}}',d1Databases:{DB:'historical-alias-native'}}));
 try{const db=await runtime.getD1Database('DB');for(const name of schemas)for(const sql of sqlStatements(readFileSync('worker/operations/'+name+'.sql','utf8')))await db.prepare(sql).run();const v2=sqlStatements(readFileSync('worker/operations/assistance-occurrences-v2.sql','utf8'));const marker=v2.find(s=>s.startsWith('INSERT INTO assistance_occurrence_schema'));await db.batch([...v2.filter(s=>s!==marker),marker].map(s=>db.prepare(s)));
 const m=manifest();await db.prepare('INSERT INTO assistance_supervision_events VALUES(?,?,?,?,?,?,?)').bind(m.signal.eventId,m.signal.projectRef,m.signal.revision,m.signal.kind,m.signal.topic,m.signal.observedAt,Date.now()).run();const {approvalColumns,approvalValues}=await import('../lib/assistance-occurrence-approvals.mjs');await db.prepare(`INSERT INTO assistance_occurrence_approved_plans(${approvalColumns.join(',')}) VALUES(${approvalColumns.map(()=>'?').join(',')})`).bind(...approvalValues({manifest:m,identityRef:'c'.repeat(64),enrollmentRef:'d'.repeat(64),serverConfigVersion:'e'.repeat(64),planRevision:1})).run();const alias={...m,occurrenceId:crypto.randomUUID(),requestId:crypto.randomUUID()};const cloud=createOccurrenceOperations({db,manifest:alias,identityRef:'c'.repeat(64),preflight:async()=>observation(alias,Date.now()-100)});assert.equal(await cloud.create(),true);
 const fence=sqlStatements(readFileSync('worker/operations/assistance-occurrences-v2-reservation-fence.sql','utf8'));const drop=fence.find(s=>s.startsWith('DROP TRIGGER')),pin=fence.find(s=>s.startsWith('INSERT INTO assistance_occurrence_reservation_fence'));await db.batch([drop,...fence.filter(s=>s!==drop&&s!==pin),pin].map(s=>db.prepare(s)));assert.equal(await cloud.list({expectedSequence:1}),null);assert.equal(await cloud.close({reason:'operator_closed'}),true);assert.equal((await db.prepare('SELECT count(*) n FROM assistance_supervision_runs').first()).n,0);
 }finally{await runtime.dispose();}
});
