import test from 'node:test';
import assert from 'node:assert/strict';
const load=()=>import('../lib/assistance-private-admin-bootstrap.mjs');
const ref='a'.repeat(64),params={operation:'register',recordRef:ref};
function fixture(){let control={enabled:true,recordRef:ref,closeAt:2000},calls=0,steps=0,hook;const options={readControl:()=>control,now:()=>1000,readRegistered:async()=>true,register:async r=>{calls++;assert.equal(r,ref);if(hook)await hook();return true;}};const step={do:async(name,config,fn)=>{steps++;assert.equal(config.retries.limit,0);assert.equal(config.timeout,'20 seconds');return fn();}};return{options,step,calls:()=>calls,steps:()=>steps,change:v=>control={...control,...v},hook:v=>hook=v};}
test('only exact operator request under live control can register once',async()=>{const f=fixture(),{createPrivateAdminBootstrap}=await load();assert.deepEqual(await createPrivateAdminBootstrap(f.options).run(params,f.step),{contract:'afw-private-admin-bootstrap/v1',state:'registered'});assert.equal(f.calls(),1);assert.equal(f.steps(),1);});
test('disabled missing expired and foreign control never call actor',async()=>{const{createPrivateAdminBootstrap}=await load();for(const change of[{enabled:false},{recordRef:'b'.repeat(64)},{closeAt:1000}]){const f=fixture();f.change(change);assert.equal((await createPrivateAdminBootstrap(f.options).run(params,f.step)).state,'unavailable');assert.equal(f.calls(),0);}const f=fixture();assert.equal((await createPrivateAdminBootstrap(f.options).run({...params,pins:{}},f.step)).state,'unavailable');assert.equal(f.calls(),0);});
test('uncertain acknowledgment is terminal without retry or recovery mutation',async()=>{const f=fixture(),{createPrivateAdminBootstrap}=await load();f.hook(()=>{throw Error('lost ACK');});assert.equal((await createPrivateAdminBootstrap(f.options).run(params,f.step)).state,'unavailable');assert.equal(f.calls(),1);assert.equal(f.steps(),1);});
test('control withdrawn after actor writes suppresses successful result',async()=>{const f=fixture(),{createPrivateAdminBootstrap}=await load();f.hook(()=>f.change({enabled:false}));assert.equal((await createPrivateAdminBootstrap(f.options).run(params,f.step)).state,'unavailable');assert.equal(f.calls(),1);});

test('cached step success does not authorize a withdrawn current registration',async()=>{const f=fixture(),{createPrivateAdminBootstrap}=await load();f.options.readRegistered=async()=>false;const step={do:async()=>true};assert.equal((await createPrivateAdminBootstrap(f.options).run(params,step)).state,'unavailable');assert.equal(f.calls(),0);});
