import test from 'node:test';
import assert from 'node:assert/strict';
import {fixture} from './fixtures/occurrence-operations.mjs';
import {qaAdministrationFixture} from './fixtures/qa-administrative-composition.mjs';
import {computeOccurrencePlanDigest} from '../lib/assistance-occurrence-digest.mjs';
import {computeQaClosureBaselineRef} from '../lib/assistance-qa-closure-catalog.mjs';
const load=()=>import('../lib/assistance-private-qa-preregistration.mjs');
async function setup(){
 const f=fixture(),approval={manifest:f.m,identityRef:'c'.repeat(64),enrollmentRef:'d'.repeat(64),serverConfigVersion:'e'.repeat(64),planRevision:1};
 const {registration:r}=await qaAdministrationFixture({createdAt:f.m.startAt,closeAt:f.m.deadline,expiresAt:f.m.deadline+10000});r.contract='afw-qa-closure-approval/v2';r.plan.occurrenceId=f.m.occurrenceId;r.approvalDigest=await computeOccurrencePlanDigest({manifest:f.m,identityRef:approval.identityRef,admissionContract:'server-v1',approval});r.plan.baselineRef=await computeQaClosureBaselineRef(r);
 let source={registration:r,approval},clock=f.m.startAt,values=new Map(),hook;
 const storage={transaction:async fn=>{const draft=new Map(structuredClone([...values]));const out=await fn({get:async k=>structuredClone(draft.get(k)),put:async(k,v)=>{draft.set(k,structuredClone(v));await hook?.();}});values=draft;return out;}};
 return {r,approval,options:{storage,readPreregistration:()=>source,now:()=>clock},get values(){return values;},source:v=>{source=v;},clock:v=>{clock=v;},hook:v=>{hook=v;},cleanup:f.cleanup};
}
test('operator pins persist before any catalog and cannot be replaced or supplied by caller',async()=>{
 const f=await setup();try{const {createPrivateQaPreregistration}=await load(),h=createPrivateQaPreregistration(f.options);assert.equal(await h.register({registration:'forged'}),true);assert.deepEqual(await h.read(),{registration:f.r,approval:f.approval});const restarted=createPrivateQaPreregistration(f.options);assert.equal(await restarted.register(),false);assert.deepEqual(await restarted.read(),await h.read());}finally{f.cleanup();}
});
test('withdrawal and expiry close admission but preserve validated closure pins',async()=>{
 const f=await setup();try{const {createPrivateQaPreregistration}=await load(),h=createPrivateQaPreregistration(f.options);assert.equal(await h.register(),true);f.clock(f.r.plan.closeAt);assert.equal(await h.read(),null);assert.deepEqual(await h.readForClosure(),{registration:f.r,approval:f.approval});assert.equal(await h.withdraw(),true);f.source(null);const restarted=createPrivateQaPreregistration(f.options);assert.equal(await restarted.read(),null);assert.equal(await restarted.register(),false);assert.deepEqual(await restarted.readForClosure(),{registration:f.r,approval:f.approval});}finally{f.cleanup();}
});
test('missing or mismatched trusted source never registers and mutation during write rolls back',async()=>{
 const f=await setup();try{const {createPrivateQaPreregistration}=await load();f.source({registration:f.r,approval:{...f.approval,identityRef:'f'.repeat(64)}});assert.equal(await createPrivateQaPreregistration(f.options).register(),false);assert.equal(f.values.size,0);f.source({registration:f.r,approval:f.approval});f.hook(()=>f.source(null));assert.equal(await createPrivateQaPreregistration(f.options).register(),false);assert.equal(f.values.size,0);}finally{f.cleanup();}
});
test('lost registration acknowledgement does not permit replacement and late reads fail closed',async()=>{
 const f=await setup();try{const {createPrivateQaPreregistration}=await load(),base=f.options.storage,uncertain=createPrivateQaPreregistration({...f.options,storage:{transaction:async fn=>{await base.transaction(fn);throw Error('lost ack');}}});assert.equal(await uncertain.register(),false);const h=createPrivateQaPreregistration(f.options);assert.equal(await h.register(),false);assert.deepEqual(await h.readForClosure(),{registration:f.r,approval:f.approval});f.clock(f.r.plan.closeAt);assert.equal(await h.read(),null);}finally{f.cleanup();}
});

test('withdrawal during transaction acknowledgement cannot return active pins',async()=>{const f=await setup();try{const {createPrivateQaPreregistration}=await load(),h=createPrivateQaPreregistration(f.options);assert.equal(await h.register(),true);let raced=false;const base=f.options.storage,late=createPrivateQaPreregistration({...f.options,storage:{transaction:async fn=>{const value=await base.transaction(fn);if(!raced){raced=true;await h.withdraw();}return value;}}});assert.equal(await late.read(),null);assert.deepEqual(await h.readForClosure(),{registration:f.r,approval:f.approval});}finally{f.cleanup();}});

test('source withdrawal after final storage acknowledgement cannot return active pins',async()=>{const f=await setup();try{const {createPrivateQaPreregistration}=await load(),h=createPrivateQaPreregistration(f.options);assert.equal(await h.register(),true);let calls=0;const base=f.options.storage,late=createPrivateQaPreregistration({...f.options,storage:{transaction:async fn=>{const value=await base.transaction(fn);if(++calls===2)f.source(null);return value;}}});assert.equal(await late.read(),null);}finally{f.cleanup();}});

test('asynchronous source and accessor then never create trusted pins or invoke getters',async()=>{const f=await setup();try{const {createPrivateQaPreregistration}=await load();let invoked=0;const raw={registration:f.r,approval:f.approval};Object.defineProperty(raw,'then',{enumerable:true,get(){invoked++;return undefined;}});f.source(raw);assert.equal(await createPrivateQaPreregistration(f.options).register(),false);assert.equal(invoked,0);f.source(Promise.resolve({registration:f.r,approval:f.approval}));assert.equal(await createPrivateQaPreregistration(f.options).register(),false);assert.equal(f.values.size,0);}finally{f.cleanup();}});

async function originalsSetup(){
 const f=await setup(),{createPrivateQaPreregistration}=await load(),{createPrivateCustodyChallenge}=await import('../lib/assistance-private-custody-challenge.mjs');const cloud={threadId:'11111111-1111-4111-8111-111111111111',environmentId:'ccarenv_synthetic',cwd:'/workspace',commandDigest:'9'.repeat(64)};let control={enabled:true,operatorRef:'8'.repeat(64),cloud};f.options.readOriginalControl=()=>control;f.options.storage.get=async key=>Array.isArray(key)?new Map(key.filter(k=>f.values.has(k)).map(k=>[k,structuredClone(f.values.get(k))])):structuredClone(f.values.get(key));const actor=createPrivateQaPreregistration(f.options),start=f.r.provisioning.createdAt;assert.equal(await actor.register(),true);const challenge=createPrivateCustodyChallenge({...f.options,readInstallation:()=>({registration:f.r,approval:f.approval}),readServiceIdentity:()=>({principalRef:f.approval.identityRef,expiresAt:f.r.provisioning.expiresAt})});f.clock(start+100);const issued=await challenge.issue();f.clock(start+200);const receipt=await challenge.consume({nonce:issued.nonce});assert.ok(receipt);f.clock(start+400);const turnId='22222222-2222-4222-8222-222222222222';const context={source:'official-platform-activity',sourceRef:'1'.repeat(64),observedAt:start+300,threadId:cloud.threadId,turnId,callId:'exec-synthetic-context',commandItemId:'exec-synthetic-command',turnStartedAt:start,turnCompletedAt:start+250,callPrecedesCommand:true,environmentId:cloud.environmentId,configId:f.approval.manifest.configId,publicationId:f.approval.manifest.publicationId,configurationRevision:6,observationRevision:6,observationsCurrent:true,connectivity:'connected',phase:'running',networkMode:'restricted',networkState:'enforced'},execution={source:'official-thread-command',sourceRef:'2'.repeat(64),observedAt:start+300,threadId:cloud.threadId,turnId,commandItemId:'exec-synthetic-command',commandDigest:cloud.commandDigest,cwd:cloud.cwd,turnStartedAt:start,turnCompletedAt:start+250,exitCode:0,sourceRevision:f.approval.manifest.sourceRevision,origin:'https://github.com/tokenizartinfo-ops/agent-friendly-web.git',checkoutClean:true,recordRef:f.r.plan.baselineRef,receiptRef:receipt.receiptRef};return {...f,actor,challenge,originals:{context,execution},control:value=>{control=value;}};
}
test('operator originals correlate with real local primary challenge and persist without refreshing',async()=>{const f=await originalsSetup();try{assert.equal(await f.actor.appendOperatorObservation(f.r.plan.baselineRef,0,f.originals),true);const first=await f.actor.readOperatorObservation();assert.equal(first.correlation.state,'observed');assert.deepEqual(first.originals,f.originals);assert.equal(await f.actor.appendOperatorObservation(f.r.plan.baselineRef,0,f.originals),true);assert.deepEqual(await f.actor.readOperatorHistory(),await f.actor.readOperatorHistory());const changed=structuredClone(f.originals);changed.execution.sourceRef='3'.repeat(64);assert.equal(await f.actor.appendOperatorObservation(f.r.plan.baselineRef,0,changed),false);assert.equal(await f.challenge.withdraw(),true);assert.equal(await f.actor.readOperatorObservation(),null);assert.ok(await f.actor.readOperatorHistory());}finally{f.cleanup();}});

test('operator originals reject disabled, foreign, extra or contradictory inputs without persistence',async()=>{for(const mode of ['disabled','foreign','receipt','secret','sequence','accessor']){const f=await originalsSetup();try{let called=0;if(mode==='disabled')f.control(null);if(mode==='receipt')f.originals.execution.receiptRef='0'.repeat(64);if(mode==='secret')f.originals.execution.secret='forbidden';if(mode==='accessor')Object.defineProperty(f.originals.context,'hidden',{enumerable:false,get(){called++;return 'forbidden';}});assert.equal(await f.actor.appendOperatorObservation(mode==='foreign'?'9'.repeat(64):f.r.plan.baselineRef,mode==='sequence'?1:0,f.originals),false,mode);assert.equal(await f.actor.readOperatorHistory(),null);assert.equal(called,0);}finally{f.cleanup();}}});
test('operator original withdrawal or expiry during transaction rolls back and ACK loss never replaces originals',async()=>{for(const mode of ['withdraw','expiry','ack']){const f=await originalsSetup();try{if(mode!=='ack')f.hook(()=>{if(mode==='withdraw')f.control(null);else f.clock(f.r.plan.closeAt);});const {createPrivateQaPreregistration}=await load(),base=f.options.storage,actor=mode==='ack'?createPrivateQaPreregistration({...f.options,storage:{...base,transaction:async fn=>{await base.transaction(fn);throw Error('lost ACK');}}}):f.actor;assert.equal(await actor.appendOperatorObservation(f.r.plan.baselineRef,0,f.originals),false,mode);if(mode==='ack'){const old=await f.actor.readOperatorHistory();assert.ok(old);const changed=structuredClone(f.originals);changed.context.sourceRef='3'.repeat(64);assert.equal(await f.actor.appendOperatorObservation(f.r.plan.baselineRef,0,changed),false);assert.deepEqual(await f.actor.readOperatorHistory(),old);}else assert.equal(await f.actor.readOperatorHistory(),null);}finally{f.cleanup();}}});

test('original admission rejects primary withdrawal during final observation acknowledgement',async()=>{for(const operation of ['read','append'])for(const target of ['challenge','preregistration']){const f=await originalsSetup();try{const {createPrivateQaPreregistration}=await load();if(operation==='read')assert.equal(await f.actor.appendOperatorObservation(f.r.plan.baselineRef,0,f.originals),true);let calls=0;const base=f.options.storage,actor=createPrivateQaPreregistration({...f.options,storage:{...base,transaction:async fn=>{const value=await base.transaction(fn);if(++calls===2)assert.equal(await (target==='challenge'?f.challenge:f.actor).withdraw(),true);return value;}}});assert.equal(operation==='read'?await actor.readOperatorObservation():await actor.appendOperatorObservation(f.r.plan.baselineRef,0,f.originals),operation==='read'?null:false,`${operation}/${target}`);assert.ok(await f.actor.readOperatorHistory());}finally{f.cleanup();}}});
