import test from 'node:test';
import assert from 'node:assert/strict';
import {fixture,observation,time} from './fixtures/occurrence-operations.mjs';
const implementation=await import('../lib/assistance-occurrence-operations.mjs').catch(()=>({}));
const withFixture=fn=>async()=>{assert.equal(typeof implementation.createOccurrenceOperations,'function','internal operations contract missing');const f=fixture();let current=time;const make=(db=f.db,preflight=async()=>observation(f.m,current))=>implementation.createOccurrenceOperations({db,manifest:f.m,identityRef:'c'.repeat(64),preflight,now:()=>current});try{await fn({...f,make,setTime:t=>current=t});}finally{f.cleanup();}};
async function claimReady(f){const x=f.make();assert.equal(await x.create(),true);assert.deepEqual(await x.list({expectedSequence:1}),[f.m.signal]);assert.equal(await x.admit({expectedSequence:2,phase:'claim'}),true);return x;}
test('real claim and terminal outcome correlate journal/run and reject lost responses from new connection',withFixture(async f=>{const x=await claimReady(f);const r=await x.claim({expectedSequence:3});assert.equal(r.eventId,f.m.signal.eventId);assert.equal(r.requestId,f.m.requestId);assert.equal(r.expiresAt,f.m.deadline);assert.equal(await f.make(f.other).claim({expectedSequence:3}),null);assert.equal(f.a.prepare('SELECT count(*) n FROM assistance_supervision_runs').get().n,1);await x.admit({expectedSequence:4,phase:'finish'});assert.equal(await x.finish({expectedSequence:5}),'intervention_required');assert.equal(await f.make(f.other).finish({expectedSequence:5}),null);const run=f.a.prepare('SELECT * FROM assistance_supervision_runs').get(),j=f.a.prepare('SELECT * FROM assistance_occurrence_journal ORDER BY sequence DESC LIMIT 1').get();assert.equal(run.outcome,j.outcome);assert.equal(run.run_id,j.run_id);assert.equal(j.state,'completed');assert.equal(j.attempts,3);assert.equal(j.controls,3);assert.throws(()=>f.a.exec('DELETE FROM assistance_occurrence_effect_checks'));}));
test('shared budget zero-row claim rolls back admission, journal and run together',withFixture(async f=>{const x=await claimReady(f);for(let i=0;i<3;i++)f.a.prepare('INSERT INTO dossier_supervision_runs(run_id,request_id,event_id,started_at,expires_at,outcome,completed_at) VALUES(?,?,?,?,?,?,?)').run(crypto.randomUUID(),crypto.randomUUID(),String(i).repeat(64),time-2000,time-1000,'reviewed',time-1500);await assert.rejects(x.claim({expectedSequence:3}),/Occurrence storage unavailable/);assert.equal(f.a.prepare('SELECT max(sequence) n FROM assistance_occurrence_journal').get().n,3);assert.equal(f.a.prepare('SELECT count(*) n FROM assistance_supervision_runs').get().n,0);assert.equal(f.a.prepare("SELECT count(*) n FROM assistance_occurrence_effect_checks WHERE phase='claim'").get().n,0);await x.close({reason:'ambiguous_response'});}));
test('concurrent real claims and finish calls produce one run/effect each',withFixture(async f=>{const a=await claimReady(f),b=f.make(f.other);const r=await Promise.all([a.claim({expectedSequence:3}),b.claim({expectedSequence:3})]);assert.equal(r.filter(Boolean).length,1);await a.admit({expectedSequence:4,phase:'finish'});const done=await Promise.all([a.finish({expectedSequence:5}),b.finish({expectedSequence:5})]);assert.equal(done.filter(Boolean).length,1);assert.equal(f.a.prepare('SELECT count(*) n FROM assistance_supervision_runs').get().n,1);assert.equal(f.a.prepare('SELECT count(*) n FROM assistance_occurrence_effect_checks').get().n,3);}));
test('finish zero-row effect aborts completed journal and never invents outcome',withFixture(async f=>{const x=await claimReady(f);const r=await x.claim({expectedSequence:3});await x.admit({expectedSequence:4,phase:'finish'});f.a.prepare("UPDATE assistance_supervision_runs SET outcome='reviewed',completed_at=? WHERE run_id=?").run(time,r.runId);await assert.rejects(x.finish({expectedSequence:5}),/Occurrence storage unavailable/);assert.equal(f.a.prepare('SELECT max(sequence) n FROM assistance_occurrence_journal').get().n,5);assert.equal(f.a.prepare('SELECT outcome FROM assistance_supervision_runs').get().outcome,'reviewed');}));
test('newer signal at claim denies effect; newer signal after claim produces exact superseded terminal',withFixture(async f=>{const x=await claimReady(f);const r=await x.claim({expectedSequence:3});assert.ok(r);await x.admit({expectedSequence:4,phase:'finish'});f.a.prepare('INSERT INTO assistance_supervision_events VALUES(?,?,?,?,?,?,?)').run('d'.repeat(64),f.m.signal.projectRef,11,'assistance_requested','orientation',f.m.signal.observedAt,time);assert.equal(await x.finish({expectedSequence:5}),'superseded');assert.equal(f.a.prepare('SELECT outcome FROM assistance_supervision_runs').get().outcome,'superseded');assert.equal(f.a.prepare('SELECT outcome FROM assistance_occurrence_journal ORDER BY sequence DESC LIMIT 1').get().outcome,'superseded');}));
test('closure during preflight blocks real claim and exact lease/window margin blocks finish',withFixture(async f=>{const x=await claimReady(f);const racing=f.make(f.db,async()=>{await f.make(f.other).close({reason:'operator_closed'});return observation(f.m);});assert.equal(await racing.claim({expectedSequence:3}),null);assert.equal(f.a.prepare('SELECT count(*) n FROM assistance_supervision_runs').get().n,0);assert.equal(await x.claim({expectedSequence:3}),null);}));
test('lease deadline margin and missing list signal stop without consumption or business effect',withFixture(async f=>{const x=await claimReady(f);const r=await x.claim({expectedSequence:3});await x.admit({expectedSequence:4,phase:'finish'});f.setTime(r.expiresAt-10000);assert.equal(await x.finish({expectedSequence:5}),null);assert.equal(f.a.prepare('SELECT max(sequence) n FROM assistance_occurrence_journal').get().n,5);assert.equal(f.a.prepare('SELECT outcome FROM assistance_supervision_runs').get().outcome,null);assert.equal(await x.close({reason:'window_expired'}),true);}));
test('new signal before finish admission must close reservation as superseded, not leave it hanging',withFixture(async f=>{const x=await claimReady(f);await x.claim({expectedSequence:3});f.a.prepare('INSERT INTO assistance_supervision_events VALUES(?,?,?,?,?,?,?)').run('d'.repeat(64),f.m.signal.projectRef,11,'assistance_requested','orientation',f.m.signal.observedAt,time);assert.equal(await x.admit({expectedSequence:4,phase:'finish'}),true);assert.equal(await x.finish({expectedSequence:5}),'superseded');}));
test('real clock crossing between journal and claim effect rolls back the entire transaction',withFixture(async f=>{
 const deadline=Date.now()+11000,m={...f.m,deadline,tokenExpiresAt:deadline,serverDeadline:deadline};
 const make=db=>implementation.createOccurrenceOperations({db,manifest:m,identityRef:'c'.repeat(64),preflight:async()=>observation(m,Date.now()),now:Date.now});
 const a=make(f.db);await a.create();await a.list({expectedSequence:1});await a.admit({expectedSequence:2,phase:'claim'});
 const delayed={prepare:f.db.prepare,async batch(statements){f.a.exec('BEGIN IMMEDIATE');try{const results=[statements[0].execute()];await new Promise(resolve=>setTimeout(resolve,Math.max(0,deadline-10000-Date.now()+75)));for(const s of statements.slice(1))results.push(s.execute());f.a.exec('COMMIT');return results;}catch(e){f.a.exec('ROLLBACK');throw e;}}};
 await assert.rejects(make(delayed).claim({expectedSequence:3}),/Occurrence storage unavailable/);
 assert.equal(f.a.prepare('SELECT count(*) n FROM assistance_supervision_runs').get().n,0);assert.equal(f.a.prepare('SELECT max(sequence) n FROM assistance_occurrence_journal').get().n,3);
}));
test('terminal listed event fails postcondition with admission rolled back',withFixture(async f=>{const x=f.make();await x.create();f.a.prepare('INSERT INTO assistance_supervision_runs(run_id,request_id,event_id,started_at,expires_at,outcome,completed_at) VALUES(?,?,?,?,?,?,?)').run(crypto.randomUUID(),crypto.randomUUID(),f.m.signal.eventId,time-2000,time-1000,'reviewed',time-1500);await assert.rejects(x.list({expectedSequence:1}),/Occurrence storage unavailable/);assert.equal(f.a.prepare('SELECT max(sequence) n FROM assistance_occurrence_journal').get().n,1);assert.equal(f.a.prepare('SELECT count(*) n FROM assistance_occurrence_effect_checks').get().n,0);}));
test('newer signal during claim preflight denies old claim with zero runs',withFixture(async f=>{const a=await claimReady(f);const stale=f.make(f.db,async()=>{f.b.prepare('INSERT INTO assistance_supervision_events VALUES(?,?,?,?,?,?,?)').run('d'.repeat(64),f.m.signal.projectRef,11,'assistance_requested','orientation',f.m.signal.observedAt,time);return observation(f.m);});assert.equal(await stale.claim({expectedSequence:3}),null);assert.equal(f.a.prepare('SELECT count(*) n FROM assistance_supervision_runs').get().n,0);assert.equal(f.a.prepare('SELECT max(sequence) n FROM assistance_occurrence_journal').get().n,3);await a.close({reason:'operator_closed'});}));
test('caller cannot request personalized outcome or supply SQL through operation inputs',withFixture(async f=>{const x=await claimReady(f);await x.claim({expectedSequence:3});await x.admit({expectedSequence:4,phase:'finish'});assert.equal(await x.finish({expectedSequence:5,outcome:'reviewed'}),null);assert.equal(await x.finish({expectedSequence:5,sql:'arbitrary'}),null);assert.equal(f.a.prepare('SELECT max(sequence) n FROM assistance_occurrence_journal').get().n,5);assert.equal(await x.finish({expectedSequence:5}),'intervention_required');}));
