import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {fixture} from './fixtures/occurrence-operations.mjs';
import {createOccurrenceOperations} from '../lib/assistance-occurrence-operations.mjs';
const catalogModule=await import('../lib/assistance-occurrence-approvals.mjs').catch(()=>({}));
const migration='worker/operations/assistance-occurrences-v2.sql';
const identityRef='c'.repeat(64),enrollmentRef='d'.repeat(64),serverConfigVersion='e'.repeat(64);
export function approval(m){return {manifest:m,identityRef,enrollmentRef,serverConfigVersion,planRevision:1};}
// Synthetic fixture delivery margin100ms absorbs cross-clock millisecond skew; production fences unchanged.
export function admission(){return {contractVersion:'afw-server-admission-v1',identityRef,enrollmentRef,serverConfigVersion,planRevision:1,admissionRevision:1,observedAt:Date.now()-100,schemaVersion:2};}
export function serverOptions(f,more={}){return {db:f.db,manifest:f.m,identityRef,admissionContract:'server-v1',approval:approval(f.m),readServerAdmission:async()=>admission(),...more};}
function setup(){const f=fixture();assert.equal(typeof catalogModule.createOccurrenceApprovalCatalog,'function');f.a.exec(readFileSync(migration,'utf8'));f.a.exec(readFileSync('worker/operations/assistance-occurrences-v2-reservation-fence.sql','utf8'));return f;}
test('server admission uses exact own-state DTO with no cloud assertions and real approvals',async()=>{
 const f=setup();try{const catalog=catalogModule.createOccurrenceApprovalCatalog({db:f.db});assert.equal(await catalog.approve(approval(f.m)),true);const ops=createOccurrenceOperations(serverOptions(f));assert.equal(await ops.create(),true);assert.deepEqual(await ops.list({expectedSequence:1}),[f.m.signal]);assert.equal(await ops.admit({expectedSequence:2,phase:'claim'}),true);const run=await ops.claim({expectedSequence:3});assert.ok(run);await ops.admit({expectedSequence:4,phase:'finish'});assert.equal(await ops.finish({expectedSequence:5}),'intervention_required');}finally{f.cleanup();}
});
test('revocation after trusted lookup rolls back consumption and all run effects',async()=>{
 const f=setup();try{const c=catalogModule.createOccurrenceApprovalCatalog({db:f.other});await c.approve(approval(f.m));const ops=createOccurrenceOperations(serverOptions(f));await ops.create();await ops.list({expectedSequence:1});await ops.admit({expectedSequence:2,phase:'claim'});
 const delayed={prepare:s=>f.db.prepare(s),batch:async statements=>{await c.revoke({occurrenceId:f.m.occurrenceId,reason:'security_denied'});return f.db.batch(statements);}};
 assert.equal(await createOccurrenceOperations(serverOptions(f,{db:delayed})).claim({expectedSequence:3}),null);assert.equal(f.a.prepare('SELECT count(*) n FROM assistance_supervision_runs').get().n,0);assert.equal(f.a.prepare('SELECT max(sequence) n FROM assistance_occurrence_journal').get().n,3);assert.equal(await ops.close({reason:'operator_closed'}),true);
 }finally{f.cleanup();}
});
test('server mode refuses missing migration, unknown/mixed providers and malformed approval',async()=>{
 const f=fixture();try{assert.equal(await createOccurrenceOperations(serverOptions(f)).create(),false);for(const more of [{admissionContract:'server-v2'},{preflight:async()=>({})},{approval:{...approval(f.m),secret:'forbidden'}},{approval:{...approval(f.m),enrollmentRef:'invalid'}}])assert.throws(()=>createOccurrenceOperations(serverOptions(f,more)),/Invalid occurrence/);
 assert.throws(()=>createOccurrenceOperations({...serverOptions(f),admissionContract:'cloud-v1',preflight:async()=>({})}),/Invalid occurrence/);
 }finally{f.cleanup();}
});
test('exact server DTO rejects extras, wrong refs/config/version/revision and stale/future dates',async()=>{
 const f=setup();try{await catalogModule.createOccurrenceApprovalCatalog({db:f.db}).approve(approval(f.m));for(const change of [{networkEnforced:true},{contractVersion:'cloud-v1'},{schemaVersion:1},{serverConfigVersion:'f'.repeat(64)},{identityRef:'f'.repeat(64)},{enrollmentRef:'f'.repeat(64)},{planRevision:2},{admissionRevision:0},{admissionRevision:1.5},{observedAt:Date.now()-31000},{observedAt:Date.now()+10000}])assert.equal(await createOccurrenceOperations(serverOptions(f,{readServerAdmission:async()=>({...admission(),...change})})).create(),false);assert.equal(f.a.prepare('SELECT count(*) n FROM assistance_occurrences').get().n,0);}finally{f.cleanup();}
});
test('catalog exact read, uniqueness, immutable schema and revocations prohibit resurrection',async()=>{
 const f=setup();try{const c=catalogModule.createOccurrenceApprovalCatalog({db:f.db});const a=approval(f.m);assert.equal(await c.approve(a),true);assert.deepEqual((await c.read(f.m.occurrenceId)).approval,a);assert.equal(await c.approve({...a,manifest:{...f.m,occurrenceId:crypto.randomUUID(),requestId:crypto.randomUUID()}}),false);assert.equal(await c.revoke({occurrenceId:f.m.occurrenceId,reason:'operator_closed'}),true);assert.equal((await c.read(f.m.occurrenceId)).revoked,true);assert.equal(await c.revoke({occurrenceId:f.m.occurrenceId,reason:'security_denied'}),false);assert.equal(await c.approve({...a,planRevision:2}),false);for(const name of ['approved_plans','plan_revocations','schema']){const table=name==='schema'?'assistance_occurrence_schema':'assistance_occurrence_'+name;assert.throws(()=>f.a.exec(`DELETE FROM ${table}`),/Immutable/);}assert.throws(()=>f.a.exec(readFileSync(migration,'utf8')),/already exists/);assert.equal(await createOccurrenceOperations(serverOptions(f)).create(),false);}finally{f.cleanup();}
});
test('revocation before create batch leaves no header or journal and before admit preserves consumed',async()=>{
 for(const phase of ['create','admit']){const f=setup();try{const c=catalogModule.createOccurrenceApprovalCatalog({db:f.other});await c.approve(approval(f.m));const ops=createOccurrenceOperations(serverOptions(f));if(phase==='admit'){await ops.create();await ops.list({expectedSequence:1});}const db={prepare:s=>f.db.prepare(s),batch:async ss=>{await c.revoke({occurrenceId:f.m.occurrenceId,reason:'operator_closed'});return f.db.batch(ss);}};const delayed=createOccurrenceOperations(serverOptions(f,{db}));assert.equal(phase==='create'?await delayed.create():await delayed.admit({expectedSequence:2,phase:'claim'}),false);assert.equal(f.a.prepare('SELECT count(*) n FROM assistance_occurrences').get().n,phase==='create'?0:1);assert.equal(f.a.prepare('SELECT max(sequence) n FROM assistance_occurrence_journal').get().n,phase==='create'?null:2);}finally{f.cleanup();}}
});
test('two server clients race same approval once and expired revoked stop preserves history',async()=>{
 const f=setup();try{const c=catalogModule.createOccurrenceApprovalCatalog({db:f.db});await c.approve(approval(f.m));const a=createOccurrenceOperations(serverOptions(f)),b=createOccurrenceOperations(serverOptions(f,{db:f.other}));assert.equal((await Promise.all([a.create(),b.create()])).filter(Boolean).length,1);await a.list({expectedSequence:1});await c.revoke({occurrenceId:f.m.occurrenceId,reason:'window_expired'});const expired=createOccurrenceOperations(serverOptions(f,{now:()=>f.m.deadline+1,readServerAdmission:async()=>{throw Error('unavailable');}}));assert.equal(await expired.close({reason:'window_expired'}),true);assert.equal(await b.close({reason:'operator_closed'}),false);assert.equal(f.a.prepare('SELECT count(*) n FROM assistance_occurrence_journal').get().n,4);}finally{f.cleanup();}
});
test('server catalog requires actual schema and exact signal including observation date bounds',async()=>{
 const f=fixture();try{assert.equal(await catalogModule.createOccurrenceApprovalCatalog({db:f.db}).approve(approval(f.m)),false);}finally{f.cleanup();}
 const g=setup();try{const c=catalogModule.createOccurrenceApprovalCatalog({db:g.db});await assert.rejects(c.approve({...approval(g.m),manifest:{...g.m,signal:{...g.m.signal,privateText:'forbidden'}}}),/Invalid/); }finally{g.cleanup();}
});

test('catalog denies approval of a fabricated revision of an existing event',async()=>{
 const f=setup();try{const c=catalogModule.createOccurrenceApprovalCatalog({db:f.db});assert.equal(await c.approve({...approval(f.m),manifest:{...f.m,signal:{...f.m.signal,revision:11}}}),false);assert.equal(f.a.prepare('SELECT count(*) n FROM assistance_occurrence_approved_plans').get().n,0);}finally{f.cleanup();}
});
test('missing approval and approved cloud downgrade fail without header history',async()=>{
 const f=setup();try{assert.equal(await createOccurrenceOperations(serverOptions(f)).create(),false);await catalogModule.createOccurrenceApprovalCatalog({db:f.db}).approve(approval(f.m));const {observation}=await import('./fixtures/occurrence-operations.mjs');assert.equal(await createOccurrenceOperations({db:f.db,manifest:f.m,identityRef:'c'.repeat(64),preflight:async()=>observation(f.m,Date.now())}).create(),false);assert.equal(f.a.prepare('SELECT count(*) n FROM assistance_occurrences').get().n,0);}finally{f.cleanup();}
});
test('lost server responses cannot replay or change admission revision',async()=>{
 const f=setup();try{await catalogModule.createOccurrenceApprovalCatalog({db:f.db}).approve(approval(f.m));const a=createOccurrenceOperations(serverOptions(f));await a.create();await a.list({expectedSequence:1});assert.equal(await createOccurrenceOperations(serverOptions(f,{db:f.other})).list({expectedSequence:1}),null);assert.equal(await createOccurrenceOperations(serverOptions(f,{readServerAdmission:async()=>({...admission(),admissionRevision:2})})).admit({expectedSequence:2,phase:'claim'}),false);assert.equal(f.a.prepare('SELECT max(sequence) n FROM assistance_occurrence_journal').get().n,2);}finally{f.cleanup();}
});
test('revocation fences list, finish admission and terminal effect after their lookup',async()=>{
 for(const phase of ['list','admitFinish','finish']){const f=setup();try{const c=catalogModule.createOccurrenceApprovalCatalog({db:f.other});await c.approve(approval(f.m));const a=createOccurrenceOperations(serverOptions(f));assert.equal(await a.create(),true,'setup create');if(phase!=='list'){assert.deepEqual(await a.list({expectedSequence:1}),[f.m.signal],'setup list');assert.equal(await a.admit({expectedSequence:2,phase:'claim'}),true,'setup admit claim');assert.ok(await a.claim({expectedSequence:3}),'setup claim');if(phase==='finish')assert.equal(await a.admit({expectedSequence:4,phase:'finish'}),true,'setup admit finish');}const seq=f.a.prepare('SELECT max(sequence) n FROM assistance_occurrence_journal').get().n;
 const db={prepare:s=>f.db.prepare(s),batch:async ss=>{await c.revoke({occurrenceId:f.m.occurrenceId,reason:'security_denied'});return f.db.batch(ss);}};const b=createOccurrenceOperations(serverOptions(f,{db}));assert.equal(phase==='list'?await b.list({expectedSequence:1}):phase==='finish'?await b.finish({expectedSequence:5}):await b.admit({expectedSequence:4,phase:'finish'}),phase==='admitFinish'?false:null);assert.equal(f.a.prepare('SELECT max(sequence) n FROM assistance_occurrence_journal').get().n,seq);if(phase!=='list')assert.equal(f.a.prepare('SELECT outcome FROM assistance_supervision_runs').get().outcome,null);assert.equal(await a.close({reason:'ambiguous_response'}),true);
 }finally{f.cleanup();}}
});
test('SQL constraints and mapping immutable; direct journal SQL cannot evade revocation',async()=>{
 const f=setup();try{const c=catalogModule.createOccurrenceApprovalCatalog({db:f.db});await c.approve(approval(f.m));const a=createOccurrenceOperations(serverOptions(f));await a.create();assert.throws(()=>f.a.exec("UPDATE assistance_occurrence_contracts SET server_config_version='"+'f'.repeat(64)+"'"),/Immutable/);assert.throws(()=>f.a.exec("UPDATE assistance_occurrence_schema SET version=2"),/Immutable/);await c.revoke({occurrenceId:f.m.occurrenceId,reason:'security_denied'});assert.throws(()=>f.a.exec("INSERT INTO assistance_occurrence_journal SELECT occurrence_id,2,'"+crypto.randomUUID()+"',identity_ref,manifest_digest,phase,'consumed',attempts,controls,CAST(unixepoch('subsec')*1000 AS INTEGER),observation_at,observation_revision,run_id,lease_expires_at,NULL,NULL FROM assistance_occurrence_journal WHERE sequence=1"),/Occurrence denied/);assert.equal(f.a.prepare('SELECT max(sequence) n FROM assistance_occurrence_journal').get().n,1);}finally{f.cleanup();}
});
test('approval cannot convert an existing cloud occurrence or block its independent close',async()=>{
 const f=setup();try{const {observation}=await import('./fixtures/occurrence-operations.mjs');const cloud=createOccurrenceOperations({db:f.db,manifest:f.m,identityRef:'c'.repeat(64),preflight:async()=>observation(f.m,Date.now())});assert.equal(await cloud.create(),true);assert.equal(await catalogModule.createOccurrenceApprovalCatalog({db:f.other}).approve(approval(f.m)),false);assert.equal(await cloud.close({reason:'operator_closed'}),true);}finally{f.cleanup();}
});

test('schema2 marker cannot certify incomplete schema1 guards',async()=>{
 const f=fixture();try{f.a.exec('DROP TRIGGER assistance_occurrence_transition');assert.throws(()=>f.a.exec(readFileSync(migration,'utf8')),/CHECK constraint/);assert.equal(f.a.prepare('SELECT count(*) n FROM assistance_occurrence_schema').get().n,0);assert.equal(await createOccurrenceOperations(serverOptions(f)).create(),false);}finally{f.cleanup();}
});
test('final server check rejects expiry after business and clock statements with total rollback',async()=>{
 const f=setup();try{const end=Date.now()+11000;f.m={...f.m,deadline:end,serverDeadline:end,tokenExpiresAt:end};await catalogModule.createOccurrenceApprovalCatalog({db:f.db}).approve(approval(f.m));const a=createOccurrenceOperations(serverOptions(f));await a.create();await a.list({expectedSequence:1});await a.admit({expectedSequence:2,phase:'claim'});const delayed={prepare:s=>f.db.prepare(s),batch:async ss=>{f.a.exec('BEGIN IMMEDIATE');try{const results=[];for(let i=0;i<ss.length;i++){if(i===ss.length-1)Atomics.wait(new Int32Array(new SharedArrayBuffer(4)),0,0,Math.max(0,end-10000-Date.now()+50));results.push(ss[i].execute());}f.a.exec('COMMIT');return results;}catch(e){f.a.exec('ROLLBACK');throw e;}}};assert.equal(await createOccurrenceOperations(serverOptions(f,{db:delayed})).claim({expectedSequence:3}),null);assert.equal(f.a.prepare('SELECT count(*) n FROM assistance_supervision_runs').get().n,0);assert.equal(f.a.prepare('SELECT max(sequence) n FROM assistance_occurrence_journal').get().n,3);}finally{f.cleanup();}
});
test('reserved event cannot downgrade to cloud with different occurrence and request UUIDs, revoked or active',async()=>{
 const {observation}=await import('./fixtures/occurrence-operations.mjs');
 for(const revoked of [false,true]){const f=setup();try{const c=catalogModule.createOccurrenceApprovalCatalog({db:f.db});await c.approve(approval(f.m));if(revoked)await c.revoke({occurrenceId:f.m.occurrenceId,reason:'security_denied'});const alias={...f.m,occurrenceId:crypto.randomUUID(),requestId:crypto.randomUUID()};const cloud=createOccurrenceOperations({db:f.other,manifest:alias,identityRef:'c'.repeat(64),preflight:async()=>observation(alias,Date.now())});assert.equal(await cloud.create(),false);assert.equal(await cloud.list({expectedSequence:1}),null);assert.equal(await cloud.admit({expectedSequence:2,phase:'claim'}),false);assert.equal(await cloud.claim({expectedSequence:3}),null);assert.equal(f.a.prepare('SELECT count(*) n FROM assistance_occurrences').get().n,0);assert.equal(f.a.prepare('SELECT count(*) n FROM assistance_supervision_runs').get().n,0);}finally{f.cleanup();}}
});
test('unpatched schema2 cannot approve or admit new server work',async()=>{
 const f=fixture();try{f.a.exec(readFileSync(migration,'utf8'));assert.equal(await catalogModule.createOccurrenceApprovalCatalog({db:f.db}).approve(approval(f.m)),false);assert.equal(await createOccurrenceOperations(serverOptions(f)).create(),false);}finally{f.cleanup();}
});
test('reserved requestId cannot select a different event even with another occurrence UUID',async()=>{
 const f=setup();try{await catalogModule.createOccurrenceApprovalCatalog({db:f.db}).approve(approval(f.m));const alias={...f.m,occurrenceId:crypto.randomUUID(),signal:{...f.m.signal,eventId:'f'.repeat(64),projectRef:'2'.repeat(64)}};f.a.prepare('INSERT INTO assistance_supervision_events VALUES(?,?,?,?,?,?,?)').run(alias.signal.eventId,alias.signal.projectRef,alias.signal.revision,alias.signal.kind,alias.signal.topic,alias.signal.observedAt,Date.now());const {observation}=await import('./fixtures/occurrence-operations.mjs');assert.equal(await createOccurrenceOperations({db:f.db,manifest:alias,identityRef:'c'.repeat(64),preflight:async()=>observation(alias,Date.now())}).create(),false);}finally{f.cleanup();}
});
test('migrating a historical cloud alias preserves stop only and denies new consumption',async()=>{
 const f=fixture();try{f.a.exec(readFileSync(migration,'utf8'));const {approvalColumns,approvalValues}=await import('../lib/assistance-occurrence-approvals.mjs');f.a.prepare(`INSERT INTO assistance_occurrence_approved_plans(${approvalColumns.join(',')}) VALUES(${approvalColumns.map(()=>'?').join(',')})`).run(...approvalValues(approval(f.m)));const alias={...f.m,occurrenceId:crypto.randomUUID(),requestId:crypto.randomUUID()};const {observation}=await import('./fixtures/occurrence-operations.mjs');const cloud=createOccurrenceOperations({db:f.db,manifest:alias,identityRef:'c'.repeat(64),preflight:async()=>observation(alias,Date.now()-100)});assert.equal(await cloud.create(),true,'historical pre-fence alias');f.a.exec(readFileSync('worker/operations/assistance-occurrences-v2-reservation-fence.sql','utf8'));assert.equal(await cloud.list({expectedSequence:1}),null);assert.equal(await cloud.admit({expectedSequence:2,phase:'claim'}),false);assert.equal(await cloud.close({reason:'operator_closed'}),true);assert.equal(f.a.prepare('SELECT count(*) n FROM assistance_supervision_runs').get().n,0);}finally{f.cleanup();}
});
