import test from 'node:test';
import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {Miniflare,convertV4MiniflareOptions} from 'miniflare';
import {manifest} from './fixtures/occurrence-operations.mjs';
import {qaAdministrationFixture} from './fixtures/qa-administrative-composition.mjs';
import {computeOccurrencePlanDigest} from '../lib/assistance-occurrence-digest.mjs';
import {computeAdministrativeResultDigest} from '../lib/assistance-administrative-closure-readback.mjs';
import {computeQaClosureBaselineRef,isQaProvisioningReservation} from '../lib/assistance-qa-closure-catalog.mjs';
const load=()=>import('../lib/assistance-private-qa-provisioning.mjs');
test('coherent history cannot place finalization after primary withdrawal',async()=>{
 const f=await fixture(),{createPrivateQaProvisioning}=await load();let d1;const actor=createPrivateQaProvisioning({...f.options,readInstallationD1:async()=>d1});await actor.reserve(f.creationRef);const i=await actor.beginInstallation(f.creationRef);await actor.startInstallationWrite(f.creationRef,i.intentId,1);d1=await ownInstallationD1(f,i);const receipt=await actor.finalizeInstallation(f.creationRef);assert.ok(receipt);
 f.setTime(7000);assert.equal(await actor.withdraw(f.creationRef,1),true);f.setTime(9000);assert.deepEqual(await actor.finalizationHistory(f.creationRef),receipt);
 await f.storage.transaction(async tx=>{const key='afw-private-installation-finalization/v1:'+f.ref,raw=await tx.get(key);raw.confirmedAt=8000;const {recordDigest:ignored,...body}=raw;void ignored;raw.recordDigest=await computeAdministrativeResultDigest(body);await tx.put(key,raw);});assert.equal(await actor.finalizationHistory(f.creationRef),null);
});
test('primary finalization retains one receipt and withdrawal dominates its history',async()=>{
 const f=await fixture(),{createPrivateQaProvisioning}=await load();let d1=null;
 const actor=createPrivateQaProvisioning({...f.options,readInstallationD1:async()=>structuredClone(d1)});
 await actor.reserve(f.creationRef);const i=await actor.beginInstallation(f.creationRef);
 assert.equal(await actor.finalizeInstallation(f.creationRef),null);
 await actor.startInstallationWrite(f.creationRef,i.intentId,1);
 d1=await ownInstallationD1(f,i);
 const receipt=await actor.finalizeInstallation(f.creationRef);assert.ok(receipt);
 assert.deepEqual(await actor.finalizeInstallation(f.creationRef),receipt);
 assert.deepEqual(await actor.readFinalizedInstallation(f.creationRef),receipt);
 assert.equal(await actor.withdraw(f.creationRef,1),true);
 assert.equal(await actor.readFinalizedInstallation(f.creationRef),null);
 assert.deepEqual(await actor.finalizationHistory(f.creationRef),receipt);
});
test('withdrawal while D1 observation waits prevents primary finalization',async()=>{
 const f=await fixture(),{createPrivateQaProvisioning}=await load(),original=createPrivateQaProvisioning(f.options);
 await original.reserve(f.creationRef);const i=await original.beginInstallation(f.creationRef);await original.startInstallationWrite(f.creationRef,i.intentId,1);
 const d1=await ownInstallationD1(f,i);let reached,release;const pendingRead=new Promise(resolve=>{reached=resolve;});
 const actor=createPrivateQaProvisioning({...f.options,readInstallationD1:async()=>{reached();await new Promise(resolve=>{release=resolve;});return d1;}});
 const pending=actor.finalizeInstallation(f.creationRef);await pendingRead;await original.withdraw(f.creationRef,1);release();
 assert.equal(await pending,null);assert.equal(await actor.finalizationHistory(f.creationRef),null);
});
test('lost finalization acknowledgement is reconciled without a second receipt',async()=>{
 let lost=false;const f=await fixture(storage({afterCommit:async()=>{if(lost){lost=false;throw Error('synthetic lost finalization ACK');}}})),{createPrivateQaProvisioning}=await load();let d1;
 const actor=createPrivateQaProvisioning({...f.options,readInstallationD1:async()=>d1});await actor.reserve(f.creationRef);const i=await actor.beginInstallation(f.creationRef);await actor.startInstallationWrite(f.creationRef,i.intentId,1);d1=await ownInstallationD1(f,i);lost=true;
 assert.equal(await actor.finalizeInstallation(f.creationRef),null);const receipt=await actor.finalizationHistory(f.creationRef);assert.ok(receipt);assert.deepEqual(await actor.readFinalizedInstallation(f.creationRef),receipt);
});
test('primary withdrawal during the final pins read blocks a committed receipt response',async()=>{
 const f=await fixture(),{createPrivateQaProvisioning}=await load(),original=createPrivateQaProvisioning(f.options);await original.reserve(f.creationRef);const i=await original.beginInstallation(f.creationRef);await original.startInstallationWrite(f.creationRef,i.intentId,1);const d1=await ownInstallationD1(f,i);let calls=0,reached,release;const blocked=new Promise(resolve=>{reached=resolve;});
 const actor=createPrivateQaProvisioning({...f.options,readInstallationD1:async()=>d1,readPins:async()=>{if(++calls===3){reached();await new Promise(resolve=>{release=resolve;});}return f.pins;}});
 const pending=actor.finalizeInstallation(f.creationRef);await blocked;await original.withdraw(f.creationRef,1);release();assert.equal(await pending,null);assert.ok(await actor.finalizationHistory(f.creationRef));assert.equal(await actor.readFinalizedInstallation(f.creationRef),null);
});
test('concurrent finalization preserves one receipt and expiry blocks operational reconciliation',async()=>{
 const f=await fixture(),{createPrivateQaProvisioning}=await load(),original=createPrivateQaProvisioning(f.options);await original.reserve(f.creationRef);const i=await original.beginInstallation(f.creationRef);await original.startInstallationWrite(f.creationRef,i.intentId,1);const d1=await ownInstallationD1(f,i),actors=Array.from({length:3},()=>createPrivateQaProvisioning({...f.options,readInstallationD1:async()=>d1}));
 const results=await Promise.all(actors.map(actor=>actor.finalizeInstallation(f.creationRef)));assert.ok(results.every(Boolean));assert.ok(results.every(r=>r.recordDigest===results[0].recordDigest));f.setTime(12000);assert.equal(await actors[0].readFinalizedInstallation(f.creationRef),null);assert.deepEqual(await actors[0].finalizationHistory(f.creationRef),results[0]);
});
test('foreign or revoked D1 provenance cannot finalize a primary installation',async()=>{
 for(const kind of ['foreign','revoked']){const f=await fixture(),{createPrivateQaProvisioning}=await load();let d1;const actor=createPrivateQaProvisioning({...f.options,readInstallationD1:async()=>d1});await actor.reserve(f.creationRef);const i=await actor.beginInstallation(f.creationRef);await actor.startInstallationWrite(f.creationRef,i.intentId,1);d1=await ownInstallationD1(f,i);if(kind==='foreign')d1.provenance.intentId=crypto.randomUUID();else d1.revoked=true;assert.equal(await actor.finalizeInstallation(f.creationRef),null);assert.equal(await actor.finalizationHistory(f.creationRef),null);}
});
async function ownInstallationD1(f,i){return {contract:'afw-private-installation-d1/v1',approval:f.pins.approval,revoked:false,provenance:{contract:'afw-private-installation-provenance/v1',occurrenceId:f.pins.approval.manifest.occurrenceId,intentId:i.intentId,ownerRef:f.ref,reservationSequence:1,approvalPinsDigest:i.approvalPinsDigest,approvalDigest:await computeOccurrencePlanDigest({manifest:f.pins.approval.manifest,identityRef:f.pins.approval.identityRef,admissionContract:'server-v1',approval:f.pins.approval}),deadline:i.deadline}};}

test('a coherent intent for another occurrence cannot start the primary write',async()=>{const f=await fixture(),{createPrivateQaProvisioning}=await load(),actor=createPrivateQaProvisioning(f.options);await actor.reserve(f.creationRef);const intent=await actor.beginInstallation(f.creationRef);await f.storage.transaction(async tx=>{const key='afw-private-installation-intent/v1:'+f.ref,r=await tx.get(key);r.occurrenceId='99999999-9999-4999-8999-999999999999';const {recordDigest:ignored,...body}=r;void ignored;r.recordDigest=await computeAdministrativeResultDigest(body);await tx.put(key,r);});assert.equal(await actor.readInstallationIntent(f.creationRef),null);assert.equal(await actor.startInstallationWrite(f.creationRef,intent.intentId,1),null);assert.equal((await actor.installationHistory(f.creationRef)).state,'prepared');});
test('primary withdrawal during postcommit pins read blocks dispatch, intent and reservation responses',async()=>{
 for(const operation of ['startInstallationWrite','readInstallationIntent','beginInstallation','read','reserve']){
  let active=false,calls=0,release,reached;const f=await fixture(),{createPrivateQaProvisioning}=await load(),original=createPrivateQaProvisioning(f.options);await original.reserve(f.creationRef);const intent=await original.beginInstallation(f.creationRef);const blocked=new Promise(resolve=>{reached=resolve;});const actor=createPrivateQaProvisioning({...f.options,readPins:async()=>{if(active&&++calls===3){reached();await new Promise(resolve=>{release=resolve;});}return structuredClone(f.pins);}});
  // reserve has additional in-transaction pin reads; trigger its final source
  // via the tx ACK rather than a guessed read count.
  let committed=false;const wrapped={...f.storage,transaction:async work=>{const result=await f.storage.transaction(work);committed=true;return result;}};
  const finalActor=operation==='reserve'?createPrivateQaProvisioning({...f.options,storage:wrapped,readPins:async()=>{if(committed){committed=false;reached();await new Promise(resolve=>{release=resolve;});}return structuredClone(f.pins);}}):actor;
  active=true;const pending=operation==='startInstallationWrite'?finalActor[operation](f.creationRef,intent.intentId,1):finalActor[operation](f.creationRef);await blocked;assert.equal(await original.withdraw(f.creationRef,1),true);release();assert.equal(await pending,null,operation);assert.equal((await original.installationHistory(f.creationRef)).state,'withdrawn');
 }
});
test('lost prepared ACK and competing callers reconcile one immutable intent',async()=>{let lost=false;const f=await fixture(storage({afterCommit:async()=>{if(lost){lost=false;throw Error('synthetic lost prepared ACK');}}})),{createPrivateQaProvisioning}=await load(),actor=createPrivateQaProvisioning(f.options);await actor.reserve(f.creationRef);lost=true;assert.equal(await actor.beginInstallation(f.creationRef),null);const original=await actor.installationHistory(f.creationRef);const reads=await Promise.all(Array.from({length:3},()=>createPrivateQaProvisioning(f.options).beginInstallation(f.creationRef)));assert.ok(reads.every(r=>r?.intentId===original.intentId));assert.equal(original.state,'prepared');});
test('primary installation intent is persistent, idempotent and gives no installation authority',async()=>{const f=await fixture(),{createPrivateQaProvisioning}=await load(),actor=createPrivateQaProvisioning(f.options);assert.equal(await actor.beginInstallation(f.creationRef),null);await actor.reserve(f.creationRef);const intent=await actor.beginInstallation(f.creationRef);assert.equal(intent.state,'prepared');assert.equal(intent.sequence,1);assert.equal(isQaProvisioningReservation(intent,f.ref),false);assert.deepEqual(await actor.beginInstallation(f.creationRef),intent);assert.deepEqual(await actor.readInstallationIntent(f.creationRef),intent);assert.deepEqual(await createPrivateQaProvisioning(f.options).installationHistory(f.creationRef),intent);});
test('write_started returns a dispatch permit only for the first primary transition',async()=>{const f=await fixture(),{createPrivateQaProvisioning}=await load(),actor=createPrivateQaProvisioning(f.options);await actor.reserve(f.creationRef);const intent=await actor.beginInstallation(f.creationRef);assert.equal(await actor.startInstallationWrite(f.creationRef,'11111111-1111-4111-8111-111111111111',1),null);const permit=await actor.startInstallationWrite(f.creationRef,intent.intentId,1);assert.equal(permit.contract,'afw-private-installation-dispatch/v1');assert.equal(permit.intentId,intent.intentId);assert.equal(await actor.startInstallationWrite(f.creationRef,intent.intentId,1),null);assert.equal((await actor.readInstallationIntent(f.creationRef)).state,'write_started');assert.equal((await actor.beginInstallation(f.creationRef)).state,'write_started');});
test('lost write_started ACK preserves intent without granting a repeat dispatch',async()=>{let lost=false;const f=await fixture(storage({afterCommit:async()=>{if(lost){lost=false;throw Error('synthetic lost start ACK');}}})),{createPrivateQaProvisioning}=await load(),actor=createPrivateQaProvisioning(f.options);await actor.reserve(f.creationRef);const intent=await actor.beginInstallation(f.creationRef);lost=true;assert.equal(await actor.startInstallationWrite(f.creationRef,intent.intentId,1),null);assert.equal(await actor.startInstallationWrite(f.creationRef,intent.intentId,1),null);assert.equal((await actor.installationHistory(f.creationRef)).state,'write_started');});
test('reservation withdrawal also tombstones an intent in the same primary transaction',async()=>{for(const dispatched of [false,true]){const f=await fixture(),{createPrivateQaProvisioning}=await load(),actor=createPrivateQaProvisioning(f.options);await actor.reserve(f.creationRef);const intent=await actor.beginInstallation(f.creationRef);if(dispatched)await actor.startInstallationWrite(f.creationRef,intent.intentId,1);assert.equal(await actor.withdraw(f.creationRef,1),true);const h=await actor.installationHistory(f.creationRef);assert.equal(h.intentId,intent.intentId);assert.equal(h.state,'withdrawn');assert.equal(h.sequence,dispatched?3:2);assert.equal(await actor.readInstallationIntent(f.creationRef),null);assert.equal(await actor.beginInstallation(f.creationRef),null);assert.equal(await actor.startInstallationWrite(f.creationRef,intent.intentId,1),null);}});
test('expiry and pins withdrawn at dispatch commit deny the permit while preserving intent history',async()=>{for(const mode of ['expiry','pins']){let cross=false,valid=true,f;const s=storage({afterCommit:async()=>{if(cross){cross=false;if(mode==='expiry')f.setTime(12000);else valid=false;}}});f=await fixture(s);f.options.readPins=async()=>valid?structuredClone(f.pins):null;const {createPrivateQaProvisioning}=await load(),actor=createPrivateQaProvisioning(f.options);await actor.reserve(f.creationRef);const intent=await actor.beginInstallation(f.creationRef);cross=true;assert.equal(await actor.startInstallationWrite(f.creationRef,intent.intentId,1),null);assert.equal((await actor.installationHistory(f.creationRef)).state,'write_started');assert.equal(await actor.readInstallationIntent(f.creationRef),null);}});
test('a coherent journal with different reference, digest or kind cannot authorize the persisted reservation',async()=>{
 for(const change of [e=>{e.sourceRef='1'.repeat(64);},e=>{e.contentDigest='2'.repeat(64);},e=>{e.kind='inventory';}]){
  const f=await fixture(),{createPrivateQaProvisioning}=await load(),actor=createPrivateQaProvisioning(f.options);assert.ok(await actor.reserve(f.creationRef));
  await f.storage.transaction(async tx=>{let previous=null;for(let n=1;n<=5;n++){const key='afw-private-evidence-journal/v1:entry:'+f.ref+':'+n,entry=await tx.get(key);if(n===1)change(entry.evidence);entry.previousEntryRef=previous;const {entryRef:ignored,...body}=entry;void ignored;entry.entryRef=await computeAdministrativeResultDigest(body);previous=entry.entryRef;await tx.put(key,entry);}const key='afw-private-evidence-journal/v1:head:'+f.ref,head=await tx.get(key);head.entryRef=previous;await tx.put(key,head);});
  assert.equal(await actor.read(f.creationRef),null);assert.equal(await actor.reserve(f.creationRef),null);
 }
});
test('coherent holds for another token do not satisfy the current reservation pins',async()=>{
 const f=await fixture(),{createPrivateQaProvisioning}=await load(),actor=createPrivateQaProvisioning(f.options);assert.ok(await actor.reserve(f.creationRef));
 await f.storage.transaction(async tx=>{const key='afw-private-qa-resource-reservation/v1:record:'+f.ref,held=await tx.get(key);held.resources.tokenId='99999999-9999-4999-8999-999999999999';await tx.put(key,held);await tx.put('afw-private-qa-resource-reservation/v1:owner:'+held.resources.accountId+':token:'+held.resources.tokenId,{recordRef:f.ref});});
 assert.equal(await actor.read(f.creationRef),null);assert.equal(await actor.reserve(f.creationRef),null);
});
function storage({afterCommit,onPut}={}){let values=new Map(),queue=Promise.resolve();return {get:async key=>structuredClone(values.get(key)),transaction(fn){const run=queue.then(async()=>{const next=new Map(values);const result=await fn({get:async key=>structuredClone(next.get(key)),put:async(key,value)=>{next.set(key,structuredClone(value));if(onPut)await onPut(key);}});values=next;if(afterCommit)await afterCommit();return result;});queue=run.catch(()=>{});return run;}};}
async function fixture(s=storage()){
 const m={...manifest(),startAt:1000,deadline:12000},approval={manifest:m,identityRef:'c'.repeat(64),enrollmentRef:'d'.repeat(64),serverConfigVersion:'e'.repeat(64),planRevision:1};const {registration}=await qaAdministrationFixture({createdAt:1000,closeAt:12000,expiresAt:23000});registration.contract='afw-qa-closure-approval/v2';registration.plan.occurrenceId=m.occurrenceId;registration.approvalDigest=await computeOccurrencePlanDigest({manifest:m,identityRef:approval.identityRef,admissionContract:'server-v1',approval});registration.plan.baselineRef=await computeQaClosureBaselineRef(registration);
 const cloud={threadId:'11111111-1111-4111-8111-111111111111',environmentId:'ccarenv_synthetic',cwd:'/workspace/agent-friendly-web',commandDigest:'a'.repeat(64)},provider={applicationDomain:'operations-manager.agentfriendlyweb.dev/assistance/custody/confirm',applicationAudience:'b'.repeat(64)},pins={registration,approval,cloud,provider},ref=registration.plan.baselineRef,h='e'.repeat(64),receiptRef='f'.repeat(64);
 const evidence={provider:{contract:'afw-private-provider-observation/v1',state:'observed',recordRef:ref,pinsDigest:await computeAdministrativeResultDigest({registration,approval,provider}),observedAt:5500,token:{id:registration.resources.tokenId,enabled:true,createdAt:1000,expiresAt:23000,metadataDigest:registration.identity.metadataDigest},applicationDigest:h,settingsDigest:h,schedulesDigest:h,policyDigest:h,inventory:{scope:'account-token-metadata-and-own-application-policies',tokenCount:1,policyCount:1,tokenDigest:h,policyDigest:h}},execution:{contract:'afw-private-execution-correlation/v1',state:'observed',recordRef:ref,receiptRef,pinsDigest:await computeAdministrativeResultDigest({registration,approval,cloud}),sourceRefs:{context:'b'.repeat(64),execution:'c'.repeat(64)},observedAt:5500}};
 const observation={contract:'afw-private-qa-observation/v1',state:'observed',recordRef:ref,challenge:{contract:'afw-private-custody-challenge/v1',state:'confirmed',recordRef:ref,receiptRef,issuedAt:3000,deadline:12000,consumedAt:4000}};let clock=5500,calls=0;
 return {pins,evidence,observation,ref,creationRef:registration.provisioning.creationRef,storage:s,setTime:t=>{clock=t;},calls:()=>calls,options:{storage:s,now:()=>clock,readPins:async()=>structuredClone(pins),readAdministrativeEvidence:async()=>{calls++;return structuredClone(evidence);},readChallengeObservation:async()=>structuredClone(observation)}};
}
test('private reservation binds fresh original evidence, one owner and five append-only references',async()=>{const f=await fixture(),{createPrivateQaProvisioning}=await load(),actor=createPrivateQaProvisioning(f.options),result=await actor.reserve(f.creationRef);assert.equal(isQaProvisioningReservation(result,f.ref),true);assert.deepEqual(await actor.read(f.creationRef),result);const history=await actor.history(f.creationRef);assert.equal(history.state,'reserved');assert.equal(history.evidenceCount,5);assert.equal(isQaProvisioningReservation(history,f.ref),false);assert.ok(!JSON.stringify(history).includes('client_id'));const calls=f.calls();assert.deepEqual(await actor.reserve(f.creationRef),result);assert.equal(f.calls(),calls);});
test('missing, mismatched, stale or uncorrelated sources never reserve',async()=>{for(const mutate of [f=>{f.evidence.provider=null;},f=>{f.evidence.execution=null;},f=>{f.evidence.provider.pinsDigest='0'.repeat(64);},f=>{f.evidence.execution.pinsDigest='0'.repeat(64);},f=>{f.evidence.provider.inventory.policyCount=2;},f=>{f.evidence.provider.token.metadataDigest='0'.repeat(64);},f=>{f.evidence.provider.observedAt=5600;},f=>{f.observation.challenge.receiptRef='0'.repeat(64);},f=>{f.observation.challenge.state='withdrawn';},f=>{f.options.maxAgeMs=100;f.evidence.provider.observedAt=1000;},f=>{f.setTime(12000);}]){const f=await fixture();mutate(f);const {createPrivateQaProvisioning}=await load(),actor=createPrivateQaProvisioning(f.options);assert.equal(await actor.reserve(f.creationRef),null);assert.equal(await actor.history(f.creationRef),null);}});
test('fresh source drift or withdrawal during await rolls back all ownership and journal writes',async()=>{for(const drift of [true,false]){const f=await fixture();let n=0,withdrawn=false;f.options.readPins=async()=>withdrawn?null:structuredClone(f.pins);f.options.readAdministrativeEvidence=async()=>{const e=structuredClone(f.evidence);if(n++&&drift)e.provider.settingsDigest='0'.repeat(64);if(!drift)withdrawn=true;return e;};const {createPrivateQaProvisioning}=await load(),actor=createPrivateQaProvisioning(f.options);assert.equal(await actor.reserve(f.creationRef),null);assert.equal(await actor.history(f.creationRef),null);}});
test('finite authority is not refreshed by historical evidence and withdrawal preserves permanent resource tombstones',async()=>{const f=await fixture(),{createPrivateQaProvisioning}=await load(),actor=createPrivateQaProvisioning(f.options);assert.ok(await actor.reserve(f.creationRef));f.setTime(8000);assert.equal(isQaProvisioningReservation(await actor.read(f.creationRef),f.ref),true);f.setTime(12000);assert.equal(await actor.read(f.creationRef),null);assert.equal((await actor.history(f.creationRef)).state,'reserved');assert.equal(await actor.withdraw(f.creationRef,99),false);assert.equal(await actor.withdraw(f.creationRef,1),true);assert.equal((await actor.history(f.creationRef)).state,'withdrawn');assert.equal(await actor.read(f.creationRef),null);});
test('two cases cannot acquire the same primary resources and caller mutation cannot alter persisted authority',async()=>{const s=storage(),a=await fixture(s),b=await fixture(s);b.pins.registration.provisioning.creationRef='9'.repeat(64);b.pins.registration.plan.baselineRef=await computeQaClosureBaselineRef(b.pins.registration);b.ref=b.pins.registration.plan.baselineRef;b.creationRef=b.pins.registration.provisioning.creationRef;b.evidence.provider.recordRef=b.ref;b.evidence.provider.pinsDigest=await computeAdministrativeResultDigest({registration:b.pins.registration,approval:b.pins.approval,provider:b.pins.provider});b.evidence.execution.recordRef=b.ref;b.evidence.execution.pinsDigest=await computeAdministrativeResultDigest({registration:b.pins.registration,approval:b.pins.approval,cloud:b.pins.cloud});b.observation.recordRef=b.ref;b.observation.challenge.recordRef=b.ref;const {createPrivateQaProvisioning}=await load(),aa=createPrivateQaProvisioning(a.options),bb=createPrivateQaProvisioning(b.options),results=await Promise.all([aa.reserve(a.creationRef),bb.reserve(b.creationRef)]);assert.equal(results.filter(Boolean).length,1);const winner=results[0]?aa:bb,f=results[0]?a:b;results.find(Boolean).state='changed';assert.equal((await winner.read(f.creationRef)).state,'reserved');});
test('deadline aborts source read and a late response cannot commit a reservation',async()=>{const f=await fixture();let release,signal;f.options.timeoutMs=1000;f.options.readAdministrativeEvidence=async request=>{signal=request.signal;return new Promise(resolve=>{release=resolve;});};const {createPrivateQaProvisioning}=await load(),actor=createPrivateQaProvisioning(f.options);assert.equal(await actor.reserve(f.creationRef),null);assert.equal(signal.aborted,true);release(f.evidence);await new Promise(resolve=>setTimeout(resolve,30));assert.equal(await actor.history(f.creationRef),null);});
test('expiry during commit acknowledgment denies returned authority without deleting the committed history',async()=>{let f,first=true;const s=storage({afterCommit:async()=>{if(first){first=false;f.setTime(12000);}}});f=await fixture(s);const {createPrivateQaProvisioning}=await load(),actor=createPrivateQaProvisioning(f.options);assert.equal(await actor.reserve(f.creationRef),null);assert.equal(await actor.read(f.creationRef),null);assert.equal((await actor.history(f.creationRef)).state,'reserved');});
test('freshness crossing during final writes rolls back the entire primary transaction',async()=>{let f;const s=storage({onPut:async key=>{if(key.startsWith('afw-private-qa-provisioning-record/v1:record:'))f.setTime(8000);}});f=await fixture(s);f.options.maxAgeMs=4000;const {createPrivateQaProvisioning}=await load(),actor=createPrivateQaProvisioning(f.options);assert.equal(await actor.reserve(f.creationRef),null);assert.equal(await actor.history(f.creationRef),null);});
test('lost commit response reconciles the original reservation without a second evidence batch',async()=>{let lost=true;const s=storage({afterCommit:async()=>{if(lost){lost=false;throw Error('synthetic lost ACK');}}}),f=await fixture(s),{createPrivateQaProvisioning}=await load(),actor=createPrivateQaProvisioning(f.options);assert.equal(await actor.reserve(f.creationRef),null);const calls=f.calls();assert.equal(isQaProvisioningReservation(await actor.read(f.creationRef),f.ref),true);assert.equal(isQaProvisioningReservation(await actor.reserve(f.creationRef),f.ref),true);assert.equal(f.calls(),calls);assert.equal((await actor.history(f.creationRef)).evidenceCount,5);});
test('pins withdrawn during commit acknowledgment deny returned authority while preserving primary history',async()=>{let valid=true;const s=storage({afterCommit:async()=>{valid=false;}}),f=await fixture(s);f.options.readPins=async()=>valid?structuredClone(f.pins):null;const {createPrivateQaProvisioning}=await load(),actor=createPrivateQaProvisioning(f.options);assert.equal(await actor.reserve(f.creationRef),null);assert.equal((await actor.history(f.creationRef)).state,'reserved');assert.equal(await actor.read(f.creationRef),null);});
test('native SQLite owns one complete evidence reservation through race, response loss, restart, expiry and withdrawal',async()=>{
 const a=await fixture(),b=await fixture();b.pins.registration.provisioning.creationRef='9'.repeat(64);b.pins.registration.plan.baselineRef=await computeQaClosureBaselineRef(b.pins.registration);b.ref=b.pins.registration.plan.baselineRef;b.creationRef=b.pins.registration.provisioning.creationRef;b.evidence.provider.recordRef=b.ref;b.evidence.provider.pinsDigest=await computeAdministrativeResultDigest({registration:b.pins.registration,approval:b.pins.approval,provider:b.pins.provider});b.evidence.execution.recordRef=b.ref;b.evidence.execution.pinsDigest=await computeAdministrativeResultDigest({registration:b.pins.registration,approval:b.pins.approval,cloud:b.pins.cloud});b.observation.recordRef=b.ref;b.observation.challenge.recordRef=b.ref;
 const values=Object.fromEntries(Object.entries({a,b}).map(([label,f])=>[label,{pins:f.pins,evidence:f.evidence,observation:f.observation,creationRef:f.creationRef}]));const built=await build({stdin:{resolveDir:process.cwd(),contents:`
 import {DurableObject} from 'cloudflare:workers';
 import {createPrivateQaProvisioning} from './lib/assistance-private-qa-provisioning.mjs';
 import {computeOccurrencePlanDigest} from './lib/assistance-occurrence-digest.mjs';
 const values=${JSON.stringify(values)};
 // Test-only control host, never an AFW deployed handler.
 export class OwnReservation extends DurableObject {async fetch(request){const body=await request.json(),v=values[body.label],actor=createPrivateQaProvisioning({storage:this.ctx.storage,now:()=>Number(this.env.CLOCK),readPins:async()=>v.pins,readAdministrativeEvidence:async()=>v.evidence,readChallengeObservation:async()=>v.observation,readInstallationD1:async()=>{const i=await actor.installationHistory(v.creationRef);return {contract:'afw-private-installation-d1/v1',approval:v.pins.approval,revoked:false,provenance:{contract:'afw-private-installation-provenance/v1',occurrenceId:i.occurrenceId,intentId:i.intentId,ownerRef:i.ownerRef,reservationSequence:1,approvalPinsDigest:i.approvalPinsDigest,approvalDigest:await computeOccurrencePlanDigest({manifest:v.pins.approval.manifest,identityRef:v.pins.approval.identityRef,admissionContract:'server-v1',approval:v.pins.approval}),deadline:i.deadline}};}});let result;if(body.operation==='withdraw')result=await actor.withdraw(v.creationRef,1);else if(body.operation==='startInstallationWrite')result=await actor.startInstallationWrite(v.creationRef,body.intentId,body.expectedSequence);else result=await actor[body.operation](v.creationRef);return body.loseAck?Response.json({fixture:'lost-ack'},{status:503}):Response.json(result);}}
 export default {fetch(request,env){return env.PRIMARY.get(env.PRIMARY.idFromName('one-primary')).fetch(request);}};
 `},bundle:true,write:false,format:'esm',platform:'browser',external:['cloudflare:workers']});const options={modules:true,compatibilityDate:'2026-09-07',script:built.outputFiles[0].text,bindings:{CLOCK:'5500'},durableObjects:{PRIMARY:{className:'OwnReservation',useSQLite:true}}},runtime=new Miniflare(convertV4MiniflareOptions(options));
 try{const call=async body=>{const response=await runtime.dispatchFetch('https://synthetic.invalid/',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});assert.equal(response.status,body.loseAck?503:200);return response.json();};await Promise.all(['a','b'].map(label=>call({label,operation:'reserve',loseAck:true})));const histories=await Promise.all(['a','b'].map(label=>call({label,operation:'history'})));assert.equal(histories.filter(Boolean).length,1);const label=histories[0]?'a':'b',other=label==='a'?'b':'a',original=histories.find(Boolean);assert.equal(original.evidenceCount,5);const nativeIntent=await call({label,operation:'beginInstallation'});assert.equal(nativeIntent.state,'prepared');await call({label,operation:'startInstallationWrite',intentId:nativeIntent.intentId,expectedSequence:1,loseAck:true});assert.equal(await call({label,operation:'startInstallationWrite',intentId:nativeIntent.intentId,expectedSequence:1}),null);assert.equal((await call({label,operation:'installationHistory'})).state,'write_started');await call({label,operation:'finalizeInstallation',loseAck:true});const finalization=await call({label,operation:'finalizationHistory'});assert.ok(finalization);await runtime.setOptions(convertV4MiniflareOptions({...options,bindings:{CLOCK:'8000',RESTART:'true'}}));assert.deepEqual(await call({label,operation:'history'}),original);assert.equal((await call({label,operation:'read'})).state,'reserved');assert.equal((await call({label,operation:'readInstallationIntent'})).intentId,nativeIntent.intentId);assert.deepEqual(await call({label,operation:'readFinalizedInstallation'}),finalization);await runtime.setOptions(convertV4MiniflareOptions({...options,bindings:{CLOCK:'12000',RESTART:'expired'}}));assert.equal(await call({label,operation:'read'}),null);assert.equal(await call({label,operation:'withdraw'}),true);assert.equal((await call({label,operation:'history'})).state,'withdrawn');assert.equal((await call({label,operation:'installationHistory'})).state,'withdrawn');assert.equal(await call({label,operation:'readFinalizedInstallation'}),null);assert.deepEqual(await call({label,operation:'finalizationHistory'}),finalization);await runtime.setOptions(convertV4MiniflareOptions({...options,bindings:{CLOCK:'5500',RESTART:'competitor'}}));assert.equal(await call({label:other,operation:'reserve'}),null);}finally{await runtime.dispose();}
});
