import test from 'node:test';
import assert from 'node:assert/strict';
import {qaAdministrationFixture} from './fixtures/qa-administrative-composition.mjs';
import {manifest} from './fixtures/occurrence-operations.mjs';
import {computeOccurrencePlanDigest} from '../lib/assistance-occurrence-digest.mjs';
import {computeQaClosureBaselineRef,isQaProvisioningReservation} from '../lib/assistance-qa-closure-catalog.mjs';
const load=()=>import('../lib/assistance-private-resource-holds.mjs');
async function pins(){const m={...manifest(),startAt:1000,deadline:2000},approval={manifest:m,identityRef:'c'.repeat(64),enrollmentRef:'d'.repeat(64),serverConfigVersion:'e'.repeat(64),planRevision:1};const {registration}=await qaAdministrationFixture({createdAt:1000,closeAt:2000,expiresAt:12000});registration.contract='afw-qa-closure-approval/v2';registration.plan.occurrenceId=m.occurrenceId;registration.approvalDigest=await computeOccurrencePlanDigest({manifest:m,identityRef:approval.identityRef,admissionContract:'server-v1',approval});registration.plan.baselineRef=await computeQaClosureBaselineRef(registration);return {registration,approval};}
function storage(){let values=new Map(),queue=Promise.resolve();return {get:async key=>structuredClone(values.get(key)),transaction(fn){const run=queue.then(async()=>{const copy=new Map(values);const result=await fn({get:async key=>structuredClone(copy.get(key)),put:async(key,value)=>copy.set(key,structuredClone(value))});values=copy;return result;});queue=run.catch(()=>{});return run;}};}
test('primary holds reject competing resource owner and are not provisioning authority',async()=>{const {createPrivateResourceHolds}=await load(),p=await pins(),s=storage();const other=structuredClone(p);other.registration.provisioning.creationRef='b'.repeat(64);other.registration.plan.baselineRef=await computeQaClosureBaselineRef(other.registration);const a=createPrivateResourceHolds({storage:s,readPins:async()=>p,now:()=>1500}),b=createPrivateResourceHolds({storage:s,readPins:async()=>other,now:()=>1500});const results=await Promise.all([a.reserve(p.registration.plan.baselineRef),b.reserve(other.registration.plan.baselineRef)]);assert.equal(results.filter(Boolean).length,1);const winner=results.find(Boolean);assert.equal(winner.state,'held');assert.equal(isQaProvisioningReservation(winner,winner.recordRef),false);const winningActor=results[0]?a:b,winningRef=results[0]?p.registration.plan.baselineRef:other.registration.plan.baselineRef;assert.deepEqual(await winningActor.reserve(winningRef),winner);});
test('withdraw CAS permanently retains owner and history after expiry',async()=>{const {createPrivateResourceHolds}=await load(),p=await pins(),s=storage();let time=1500;const actor=createPrivateResourceHolds({storage:s,readPins:async()=>p,now:()=>time}),ref=p.registration.plan.baselineRef;const held=await actor.reserve(ref);assert.equal(await actor.withdraw(ref,99),false);assert.equal(await actor.withdraw(ref,held.sequence),true);assert.equal(await actor.read(ref),null);assert.equal((await actor.history(ref)).state,'withdrawn');assert.equal(await actor.reserve(ref),null);time=3000;assert.equal((await actor.history(ref)).state,'withdrawn');const other=structuredClone(p);other.registration.provisioning.creationRef='b'.repeat(64);other.registration.plan.baselineRef=await computeQaClosureBaselineRef(other.registration);assert.equal(await createPrivateResourceHolds({storage:s,readPins:async()=>other,now:()=>1500}).reserve(other.registration.plan.baselineRef),null);});
test('source drift, wrong reference and closed window never reserve',async()=>{const {createPrivateResourceHolds}=await load(),p=await pins();for(const time of [999,2000,8640000000000001]){const actor=createPrivateResourceHolds({storage:storage(),readPins:async()=>p,now:()=>time});assert.equal(await actor.reserve(p.registration.plan.baselineRef),null);}let n=0;const actor=createPrivateResourceHolds({storage:storage(),readPins:async()=>{const v=structuredClone(p);if(n++)v.approval.planRevision++;return v;},now:()=>1500});assert.equal(await actor.reserve(p.registration.plan.baselineRef),null);assert.equal(await actor.history(p.registration.plan.baselineRef),null);});
test('a fresh actor cannot accept persisted reservation or withdrawal from its future',async()=>{const {createPrivateResourceHolds}=await load(),p=await pins(),s=storage(),ref=p.registration.plan.baselineRef;const original=createPrivateResourceHolds({storage:s,readPins:async()=>p,now:()=>1500});assert.ok(await original.reserve(ref));const early=createPrivateResourceHolds({storage:s,readPins:async()=>p,now:()=>1200});assert.equal(await early.history(ref),null);assert.equal(await early.read(ref),null);assert.equal(await early.reserve(ref),null);assert.equal(await early.withdraw(ref,1),false);const later=createPrivateResourceHolds({storage:s,readPins:async()=>p,now:()=>1600});assert.equal(await later.withdraw(ref,1),true);assert.equal(await original.history(ref),null);assert.equal((await later.history(ref)).state,'withdrawn');});
