import test from 'node:test';
import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {Miniflare,convertV4MiniflareOptions} from 'miniflare';
import {manifest} from './fixtures/occurrence-operations.mjs';
import {qaAdministrationFixture} from './fixtures/qa-administrative-composition.mjs';
import {computeOccurrencePlanDigest} from '../lib/assistance-occurrence-digest.mjs';
import {computeQaClosureBaselineRef,isQaProvisioningReservation} from '../lib/assistance-qa-closure-catalog.mjs';
import {createPrivateExecutionCorrelation} from '../lib/assistance-private-execution-correlation.mjs';
const load=()=>import('../lib/assistance-private-original-context-reader.mjs');
async function fixture(){
 const m={...manifest(),startAt:1000000,deadline:1020000},approval={manifest:m,identityRef:'c'.repeat(64),enrollmentRef:'d'.repeat(64),serverConfigVersion:'e'.repeat(64),planRevision:1};const {registration}=await qaAdministrationFixture({createdAt:1000000,closeAt:1020000,expiresAt:1030000});registration.contract='afw-qa-closure-approval/v2';registration.plan.occurrenceId=m.occurrenceId;registration.approvalDigest=await computeOccurrencePlanDigest({manifest:m,identityRef:approval.identityRef,admissionContract:'server-v1',approval});registration.plan.baselineRef=await computeQaClosureBaselineRef(registration);
 const threadId='11111111-1111-4111-8111-111111111111',turnId='22222222-2222-4222-8222-222222222222',callId='exec-official-context',commandItemId='exec-challenge',command='node scripts/afw-private-challenge-client.mjs confirm '+registration.plan.baselineRef+' '+m.startAt+' '+m.deadline,commandDigest=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(command))),v=>v.toString(16).padStart(2,'0')).join('');
 const pins={registration,approval,cloud:{threadId,environmentId:'ccarenv_synthetic',cwd:'/workspace/agent-friendly-web',commandDigest}},input={recordRef:registration.plan.baselineRef,turnId,callId,commandItemId};
 const original={schemaVersion:1,thread:{id:threadId,kind:'codex',hostId:'durable'},turns:[{id:turnId,status:'completed',error:null,startedAt:1001,completedAt:1005,items:[{id:callId,type:'mcpToolCall',server:'codex_apps',tool:'cloud_environment.environment_status',arguments:{},status:'completed'},{id:commandItemId,type:'commandExecution',command,cwd:pins.cloud.cwd,status:'completed',exitCode:0}]}]};
 const activity={threadId,turnId,callId,toolName:'codex_apps.cloud_environment.environment_status',arguments:{},result:{capabilities:[],connectivity:'connected',desired_phase:'running',environment_id:pins.cloud.environmentId,failure:null,network_policy:{allowed_hosts:['github.com'],effective_allowed_hosts:['github.com'],mode:'restricted',preset_allowed_hosts:[],presets:[],state:'enforced'},observations_current:true,observed_phase:'running',observed_spec_revision:'6',outbound_identities:[],provider:'cloud',runtime_variables:[],secrets:[],source_config_id:m.configId,source_config_version_id:m.publicationId,spec_revision:'6'}};let clock=1006000;const requests=[];
 return {pins,input,original,activity,setTime:t=>{clock=t;},options:{now:()=>clock,readPins:async()=>structuredClone(pins),readThread:async request=>{requests.push(request);return structuredClone(original);},readActivityOriginal:async request=>{requests.push(request);return structuredClone(activity);}},requests};
}
test('official dialog projection uses retrieval time and original turn/call order, never a fabricated call timestamp',async()=>{const f=await fixture(),{createPrivateOriginalContextReader}=await load(),result=await createPrivateOriginalContextReader(f.options).read(f.input);assert.equal(result.observedAt,1006000);assert.equal(result.turnStartedAt,1001000);assert.equal(result.turnCompletedAt,1005000);assert.equal(result.callPrecedesCommand,true);assert.equal(result.commandItemId,f.input.commandItemId);assert.equal(result.publicationId,f.pins.approval.manifest.publicationId);assert.equal(isQaProvisioningReservation(result,f.input.recordRef),false);assert.equal(f.requests.length,2);});
test('absent, unrelated, unsuccessful, incomplete or changed originals fail closed',async()=>{for(const mutate of [f=>{f.options.readActivityOriginal=async()=>null;},f=>{f.activity.callId='other';},f=>{f.original.turns[0].items.reverse();},f=>{f.original.turns[0].items[0].status='failed';},f=>{f.original.turns[0].items[0].tool='other';},f=>{f.activity.result.source_config_version_id='other';},f=>{f.activity.result.observed_spec_revision='5';},f=>{f.activity.result.network_policy.state='unknown';},f=>{f.activity.result.observations_current=false;},f=>{f.activity.result.secrets=[{value:'private'}];},f=>{f.original.thread.hostId='local';},f=>{f.original.turns[0].items[1].command+='; echo fake';},f=>{f.original.turns[0].items.push(structuredClone(f.original.turns[0].items[0]));}]){const f=await fixture();mutate(f);const {createPrivateOriginalContextReader}=await load();assert.equal(await createPrivateOriginalContextReader(f.options).read(f.input),null);}});
test('pins, expiry, freshness and descriptor changes cannot create current context',async()=>{for(const mutate of [f=>{f.setTime(1020000);},f=>{f.options.maxAgeMs=100;},f=>{let n=0;f.options.readPins=async()=>++n===1?f.pins:null;},f=>{Object.defineProperty(f.activity,'hidden',{get(){throw Error('must not invoke');}});f.options.readActivityOriginal=async()=>f.activity;}]){const f=await fixture();mutate(f);const {createPrivateOriginalContextReader}=await load();assert.equal(await createPrivateOriginalContextReader(f.options).read(f.input),null);}});
test('late official activity response is aborted and cannot reread pins',async()=>{const f=await fixture();let release,signal,pinsCalls=0;f.options.timeoutMs=1000;f.options.readPins=async()=>{pinsCalls++;return f.pins;};f.options.readActivityOriginal=async request=>{signal=request.signal;return new Promise(resolve=>{release=resolve;});};const {createPrivateOriginalContextReader}=await load();assert.equal(await createPrivateOriginalContextReader(f.options).read(f.input),null);assert.equal(signal.aborted,true);release(f.activity);await new Promise(resolve=>setTimeout(resolve,20));assert.equal(pinsCalls,1);});
test('post-turn administrative retrieval correlates by original call ordering while clocks advance',async()=>{const f=await fixture(),{createPrivateOriginalContextReader}=await load();let clock=1006000;const reader=createPrivateOriginalContextReader({...f.options,now:()=>clock}),ref=f.input.recordRef,receipt={contract:'afw-private-custody-challenge/v1',state:'confirmed',recordRef:ref,receiptRef:'f'.repeat(64),issuedAt:1003000,deadline:1020000,consumedAt:1004000};const result=await createPrivateExecutionCorrelation({now:()=>clock,readPins:f.options.readPins,readOfficialContext:async()=>{clock+=10;return reader.read(f.input);},readExecution:async()=>({source:'official-thread-command',sourceRef:'b'.repeat(64),observedAt:clock,threadId:f.pins.cloud.threadId,turnId:f.input.turnId,commandItemId:f.input.commandItemId,commandDigest:f.pins.cloud.commandDigest,cwd:f.pins.cloud.cwd,turnStartedAt:1001000,turnCompletedAt:1005000,exitCode:0,sourceRevision:f.pins.approval.manifest.sourceRevision,origin:'https://github.com/tokenizartinfo-ops/agent-friendly-web.git',checkoutClean:true,recordRef:ref,receiptRef:receipt.receiptRef}),readChallengeObservation:async()=>({contract:'afw-private-qa-observation/v1',state:'observed',recordRef:ref,challenge:receipt})}).read(ref);assert.equal(result?.state,'observed');});
test('workerd composes both original readers and rejects absent dialog, wrong receipt or call order',async()=>{
 const f=await fixture(),receipt={contract:'afw-private-custody-challenge/v1',state:'confirmed',recordRef:f.input.recordRef,receiptRef:'f'.repeat(64),issuedAt:1003000,deadline:1020000,consumedAt:1004000};const [call,command]=f.original.turns[0].items;command.output={text:JSON.stringify(receipt),truncated:false};const probes=[['head','git rev-parse HEAD',f.pins.approval.manifest.sourceRevision+'\n'],['origin','git remote get-url origin','https://github.com/tokenizartinfo-ops/agent-friendly-web.git\n'],['clean','git status --porcelain --untracked-files=all','']];const items=stage=>probes.map(([id,cmd,text])=>({id:'exec-'+stage+'-'+id,type:'commandExecution',command:cmd,cwd:f.pins.cloud.cwd,status:'completed',exitCode:0,output:{text,truncated:false}}));f.original.turns[0].items=[call,...items('before'),command,...items('after')];const values={pins:f.pins,input:f.input,original:f.original,activity:f.activity,receipt};
 const bundle=await build({stdin:{resolveDir:process.cwd(),contents:`
 import {createPrivateOriginalContextReader} from './lib/assistance-private-original-context-reader.mjs';
 import {createPrivateOriginalExecutionReader} from './lib/assistance-private-original-execution-reader.mjs';
 import {createPrivateExecutionCorrelation} from './lib/assistance-private-execution-correlation.mjs';
 import {isQaProvisioningReservation} from './lib/assistance-qa-closure-catalog.mjs';
 const v=${JSON.stringify(values)};
 export default {async fetch(request){let clock=1006000;const path=new URL(request.url).pathname,original=structuredClone(v.original);if(path==='/call-order'){const call=original.turns[0].items.shift();original.turns[0].items.push(call);}const now=()=>clock,readPins=async()=>v.pins,readThread=async()=>original,context=createPrivateOriginalContextReader({now,readPins,readThread,readActivityOriginal:async()=>path==='/dialog-missing'?null:v.activity}),execution=createPrivateOriginalExecutionReader({now,readPins,readThread}),result=await createPrivateExecutionCorrelation({now,readPins,readOfficialContext:async()=>{clock+=10;return context.read(v.input);},readExecution:async()=>execution.read({recordRef:v.input.recordRef,turnId:v.input.turnId,commandItemId:v.input.commandItemId}),readChallengeObservation:async()=>({contract:'afw-private-qa-observation/v1',state:'observed',recordRef:v.input.recordRef,challenge:path==='/receipt-wrong'?{...v.receipt,receiptRef:'0'.repeat(64)}:v.receipt})}).read(v.input.recordRef);return Response.json({result,authority:isQaProvisioningReservation(result,v.input.recordRef)});}};
 `},bundle:true,write:false,format:'esm',platform:'browser'});const runtime=new Miniflare(convertV4MiniflareOptions({modules:true,compatibilityDate:'2026-09-07',script:bundle.outputFiles[0].text}));try{const accepted=await(await runtime.dispatchFetch('https://synthetic.invalid/')).json();assert.equal(accepted.result.state,'observed');assert.equal(accepted.authority,false);for(const path of ['/dialog-missing','receipt-wrong','call-order'])assert.deepEqual(await(await runtime.dispatchFetch(new URL(path,'https://synthetic.invalid/'))).json(),{result:null,authority:false});}finally{await runtime.dispose();}
});
