import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {operationsDb} from './fixtures/operations-db.mjs';
import {recordWatchdogObservation} from '../lib/operations-watchdog-transitions.mjs';
import {admitWatchdogNotices} from '../lib/operations-watchdog-inbox.mjs';
import {reserveNotice,acknowledgeNotice} from '../lib/operations-notice-reservation.mjs';
const now=Date.parse('2026-10-05T03:00:00.000Z'),resource='afw_delegated_canary',requestId=crypto.randomUUID();
async function setup(){const s=operationsDb();for(const n of ['consumer-state','watchdog-state','watchdog-inbox','notice-reservations'])s.sqlite.exec(readFileSync(new URL(`../worker/operations/${n}.sql`,import.meta.url),'utf8'));const env={OPERATIONS_STATE_DB:s.db,AFW_OPERATIONS_NOTICES_ENABLED:'true',AFW_OPERATIONS_WATCHDOG_ENABLED:'true',AFW_OPERATIONS_PRODUCER_ENABLED:'true',AFW_OPERATIONS_WINDOW_EXPIRES_AT:new Date(now+600000).toISOString()};await recordWatchdogObservation(s.db,{paused:false,checkedAt:new Date(now).toISOString(),resources:[{resource,issues:['delivery_pending']},{resource:'afw_delegated_real_pilot',issues:[]}]},{now});await admitWatchdogNotices(env,{now});return {...s,env};}
test('reservation retries retain identity and ACK repeats retain outcome',async()=>{const s=await setup();const a=await reserveNotice(s.env,{resource,revision:1,requestId,now});assert.ok(a?.runId);assert.deepEqual(await reserveNotice(s.env,{resource,revision:1,requestId,now}),a);assert.equal(await acknowledgeNotice(s.env,a.runId,{now}), 'accepted');assert.equal(await acknowledgeNotice(s.env,a.runId,{now}), 'accepted');s.sqlite.close();});
test('pause supersedes an existing reservation rather than acknowledging old work',async()=>{const s=await setup();const a=await reserveNotice(s.env,{resource,revision:1,requestId,now});s.sqlite.exec("UPDATE operations_watchdog_state SET revision=2,condition='paused'");assert.equal(await acknowledgeNotice(s.env,a.runId,{now}), 'superseded');s.sqlite.close();});
test('concurrent requests allow one reservation; expired reservation cannot ACK or reuse old request',async()=>{const s=await setup();const result=await Promise.all([reserveNotice(s.env,{resource,revision:1,requestId,now}),reserveNotice(s.env,{resource,revision:1,requestId:crypto.randomUUID(),now})]);assert.equal(result.filter(Boolean).length,1);const a=result.find(Boolean);assert.equal(await acknowledgeNotice(s.env,a.runId,{now:now+300000}),null);assert.equal(await reserveNotice(s.env,{resource,revision:1,requestId:a.requestId,now:now+300000}),null);assert.ok(await reserveNotice(s.env,{resource,revision:1,requestId:crypto.randomUUID(),now:now+300000}));s.sqlite.close();});
test('window caps lease and closed flags/deadline deny IO',async()=>{const s=await setup();s.env.AFW_OPERATIONS_WINDOW_EXPIRES_AT=new Date(now+1000).toISOString();const a=await reserveNotice(s.env,{resource,revision:1,requestId,now});assert.equal(a.expiresAt,now+1000);assert.equal(await acknowledgeNotice(s.env,a.runId,{now:now+1000}),null);let io=0;const closed={...s.env,AFW_OPERATIONS_NOTICES_ENABLED:'false',OPERATIONS_STATE_DB:{prepare(){io++;throw Error('secret');}}};assert.equal(await reserveNotice(closed,{resource,revision:1,requestId,now}),null);assert.equal(await acknowledgeNotice(closed,a.runId,{now}),null);assert.equal(io,0);s.sqlite.close();});
test('budget and stale state block claims; storage failure is sane and transactional',async()=>{const s=await setup();s.sqlite.exec('UPDATE operations_watchdog_state SET checked_at=checked_at-1000000');assert.equal(await reserveNotice(s.env,{resource,revision:1,requestId,now}),null);s.sqlite.exec(`UPDATE operations_watchdog_state SET checked_at=${now}`);s.failBatchAt(0);await assert.rejects(()=>reserveNotice(s.env,{resource,revision:1,requestId,now}),/^Error: Notice reservation storage unavailable$/);assert.equal(s.sqlite.prepare('SELECT COUNT(*) AS n FROM operations_notice_reservations').get().n,0);s.sqlite.close();});
test('a pause at execution fences claim and malformed input fails before IO',async()=>{const s=await setup();const racing={...s.env,OPERATIONS_STATE_DB:{...s.db,batch:async statements=>{s.sqlite.exec("UPDATE operations_watchdog_state SET condition='paused',revision=2");return s.db.batch(statements);}}};assert.equal(await reserveNotice(racing,{resource,revision:1,requestId,now}),null);await assert.rejects(()=>reserveNotice(s.env,{resource:'other',revision:1,requestId,now}),/Invalid notice input/);await assert.rejects(()=>acknowledgeNotice(s.env,'bad',{now}),/Invalid notice input/);s.sqlite.close();});
test('three reservations in rolling day exhaust shared budget',async()=>{const s=await setup();for(let i=0;i<3;i++)s.sqlite.prepare('INSERT INTO operations_notice_reservations(run_id,request_id,resource,revision,reserved_at,expires_at) VALUES (?,?,?,?,?,?)').run(crypto.randomUUID(),crypto.randomUUID(),resource,1,now-2000,now-1000);assert.equal(await reserveNotice(s.env,{resource,revision:1,requestId,now}),null);s.sqlite.close();});
test('superseded ACK does not permanently suppress an unaccepted notice after freshness returns',async()=>{const s=await setup();const a=await reserveNotice(s.env,{resource,revision:1,requestId,now});s.sqlite.exec('UPDATE operations_watchdog_state SET checked_at=checked_at-1000000');assert.equal(await acknowledgeNotice(s.env,a.runId,{now}),'superseded');s.sqlite.exec(`UPDATE operations_watchdog_state SET checked_at=${now}`);assert.ok(await reserveNotice(s.env,{resource,revision:1,requestId:crypto.randomUUID(),now}));s.sqlite.close();});
