import test from 'node:test';
import assert from 'node:assert/strict';
import {operationsDb} from './fixtures/operations-db.mjs';
import {createProducerState,producerFreshness} from '../lib/operations-producer-state.mjs';
import {readFileSync} from 'node:fs';
test('producer checkpoint serializes probes, suppresses only recent confirmed health and detects silence',async()=>{
  const {db,sqlite}=operationsDb();sqlite.exec(readFileSync(new URL('../worker/operations/producer-state.sql',import.meta.url),'utf8'));
  const store=createProducerState(db);const target={resource:'afw_delegated_canary',version:'aa121311-2d88-4a2f-ad54-b52193cd1c20',expected:'closed'};
  const time=Date.parse('2026-10-04T16:00:00Z');
  const first=await store.claim(target,time);assert.ok(first);
  assert.equal(await store.claim(target,time+1),null);
  assert.equal(store.shouldDeliver(first,'recovered',time),true);
  await store.finish(first,{result:'recovered',confirmed:true},time+2);
  const second=await store.claim(target,time+3);assert.equal(store.shouldDeliver(second,'recovered',time+3),false);
  assert.equal(store.shouldDeliver(second,'failed',time+3),true);
  await store.finish(second,{result:'failed',confirmed:false},time+4);
  let row=await db.prepare('SELECT * FROM operations_probe_state').first();assert.equal(row.confirmed_at,time+2);assert.equal(row.last_result,'recovered');
  const retry=await store.claim(target,time+5);assert.equal(store.shouldDeliver(retry,'recovered',time+5),true);
  await store.finish(retry,{result:'recovered',confirmed:true},time+6);
  assert.equal(producerFreshness(row,time+5).silent,false);
  assert.equal(producerFreshness(row,time+900007).deliveryStale,true);
  const third=await store.claim(target,time+900007);assert.equal(store.shouldDeliver(third,'recovered',time+900007),true);
  await store.finish(third,{result:'failed',confirmed:true},time+900008);
  row=await db.prepare('SELECT * FROM operations_probe_state').first();assert.equal(row.last_result,'failed');
  const fourth=await store.claim({...target,expected:'available'},time+900009);assert.equal(store.shouldDeliver(fourth,'recovered',time+900009),true);
  await store.finish(fourth,{result:'recovered',confirmed:false},time+900010);
  assert.equal(producerFreshness(null,time).silent,true);
  assert.equal(producerFreshness(row,time+1800010).silent,true);
  const oldLease=await store.claim(target,time+1800011);
  const newLease=await store.claim(target,time+2100012);assert.ok(newLease);
  assert.equal(await store.finish(oldLease,{result:'recovered',confirmed:true},time+2100013),false);
  assert.equal(await store.finish(newLease,{result:'recovered',confirmed:true},time+2100014),true);
});
