'use client';
import {useRef,useState} from 'react';
type Guidance={message:{question:string;why:string};preparedAt:number;revision:number;expired:boolean;stale:boolean};
const copy={es:['Consultar orientación','Consultando…','Todavía no hay una orientación preparada.','No pude consultar. Podés volver a intentarlo.','Esta orientación pertenece a una lectura anterior. Revisemos el estado actual antes de decidir.','Es una propuesta para revisar; no cambia ni completa tus respuestas.'],en:['Check guidance','Checking…','No guidance has been prepared yet.','Could not check. You can try again.','This guidance belongs to an earlier reading. Check the current state before deciding.','This is a proposal to review; it does not change or complete your answers.'],pt:['Consultar orientação','Consultando…','Ainda não há uma orientação preparada.','Não pude consultar. Você pode tentar novamente.','Esta orientação pertence a uma leitura anterior. Verifique o estado atual antes de decidir.','É uma proposta para revisar; não altera nem completa suas respostas.']};
export function AssistanceGoalProposal({projectId,sourceId,locale,request,currentSaved}:{projectId:string;sourceId:string;locale:'es'|'en'|'pt';request:typeof fetch;currentSaved:boolean}){
 const text=copy[locale],lock=useRef(false),[state,setState]=useState('idle'),[guidance,setGuidance]=useState<Guidance|null>(null);
 async function refresh(){if(lock.current)return;lock.current=true;setState('loading');setGuidance(null);const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),3000);
 try{const response=await request(`/api/projects/${encodeURIComponent(projectId)}/assistance-proposal?source=${encodeURIComponent(sourceId)}`,{signal:controller.signal,cache:'no-store'});
 if(!response.ok||!response.headers.get('content-type')?.startsWith('application/json'))throw Error();
 const reader=response.body?.getReader();if(!reader)throw Error();let data='',size=0;const decoder=new TextDecoder();try{while(true){const part=await reader.read();if(part.done)break;size+=part.value.byteLength;if(size>4096)throw Error();data+=decoder.decode(part.value,{stream:true});}data+=decoder.decode();}finally{void reader.cancel().catch(()=>{});}
 const value=JSON.parse(data);if(Object.keys(value).length!==1||!Object.hasOwn(value,'guidance'))throw Error();const g=value.guidance;
 if(g!==null&&(!g||Object.keys(g).sort().join(',')!=='expired,message,preparedAt,revision,stale'||typeof g.expired!=='boolean'||typeof g.stale!=='boolean'||!Number.isSafeInteger(g.preparedAt)||g.preparedAt<0||!Number.isSafeInteger(g.revision)||g.revision<1||!g.message||Object.keys(g.message).sort().join(',')!=='question,why'||typeof g.message.question!=='string'||g.message.question.length>300||typeof g.message.why!=='string'||g.message.why.length>500))throw Error();
 setGuidance(g);setState('ready');}catch{setState('error');}finally{clearTimeout(timer);lock.current=false;}}
 return <section aria-live="polite"><button type="button" disabled={state==='loading'} onClick={()=>void refresh()}>{state==='loading'?text[1]:text[0]}</button>{state==='error'?<p>{text[3]}</p>:null}{state==='ready'&&!guidance?<p>{text[2]}</p>:null}{guidance?<><p>{new Date(guidance.preparedAt).toLocaleString(locale)}</p>{guidance.stale||guidance.expired||!currentSaved?<p>{text[4]}</p>:null}<p><strong>{guidance.message.question}</strong></p><p>{guidance.message.why}</p><p>{text[5]}</p></>:null}</section>;
}
