export const CONTACT_COPY = Object.freeze({
  es: {
    eyebrow: 'Continuar es opcional',
    title: 'Recibí un plan para mejorar este sitio.',
    intro: 'La auditoría ya está completa. Solo dejanos un contacto si querés transformar el resultado en prioridades concretas.',
    open: 'Recibir mi plan', close: 'Cerrar', preview: 'Revisar solicitud',
    previewNotice: 'Vista previa: nada se envía ni se guarda todavía.',
    fields: { email: 'Email', name: 'Nombre (opcional)', organization: 'Organización (opcional)', role: 'Tu relación con el sitio (opcional)', domain: 'Dominio auditado', objective: 'Qué querés conseguir' },
    objectives: { receive_plan: 'Recibir un plan priorizado', understand_results: 'Entender mejor el resultado', request_pilot: 'Evaluar un piloto', agency_partnership: 'Trabajar como agencia o partner' },
    consents: {
      requestedPlan: 'Acepto que usen estos datos para preparar y enviarme el plan solicitado.',
      commercial: 'También acepto que me contacten para conversar sobre este proyecto.',
      updates: 'Quiero recibir novedades de Agent Friendly Web.',
    },
    summary: 'Así quedaría tu solicitud', notSent: 'Todavía no fue enviada. El canal de datos reales se habilitará en un gate separado.', required: 'Necesario para solicitar el plan', optional: 'Opcional y desmarcado por defecto', edit: 'Editar datos', send: 'Confirmar y enviar', unavailable: 'Envío todavía no habilitado', sent: 'Solicitud recibida. El email todavía no se envía automáticamente.', invalid: 'Revisá el email, el dominio y el consentimiento necesario.',
    privacy: 'Cómo tratamos estos datos',
  },
  en: {
    eyebrow: 'Continuing is optional', title: 'Receive a plan to improve this website.', intro: 'The audit is already complete. Leave a contact only if you want to turn the result into concrete priorities.',
    open: 'Receive my plan', close: 'Close', preview: 'Review request', previewNotice: 'Preview: nothing is sent or stored yet.',
    fields: { email: 'Email', name: 'Name (optional)', organization: 'Organization (optional)', role: 'Your relationship to the website (optional)', domain: 'Audited domain', objective: 'What you want to achieve' },
    objectives: { receive_plan: 'Receive a prioritized plan', understand_results: 'Better understand the result', request_pilot: 'Evaluate a pilot', agency_partnership: 'Work as an agency or partner' },
    consents: { requestedPlan: 'I agree that these details may be used to prepare and send the requested plan.', commercial: 'I also agree to be contacted about this project.', updates: 'I want to receive Agent Friendly Web updates.' },
    summary: 'This is how your request would look', notSent: 'It has not been sent. The real-data channel will be enabled through a separate gate.', required: 'Required to request the plan', optional: 'Optional and unchecked by default', edit: 'Edit details', send: 'Confirm and send', unavailable: 'Sending is not enabled yet', sent: 'Request received. Email is not sent automatically yet.', invalid: 'Review the email, domain and required consent.',
    privacy: 'How these details are handled',
  },
  pt: {
    eyebrow: 'Continuar é opcional', title: 'Receba um plano para melhorar este site.', intro: 'A auditoria já está completa. Deixe um contato somente se quiser transformar o resultado em prioridades concretas.',
    open: 'Receber meu plano', close: 'Fechar', preview: 'Revisar solicitação', previewNotice: 'Prévia: nada é enviado ou armazenado ainda.',
    fields: { email: 'Email', name: 'Nome (opcional)', organization: 'Organização (opcional)', role: 'Sua relação com o site (opcional)', domain: 'Domínio auditado', objective: 'O que você quer alcançar' },
    objectives: { receive_plan: 'Receber um plano priorizado', understand_results: 'Entender melhor o resultado', request_pilot: 'Avaliar um piloto', agency_partnership: 'Trabalhar como agência ou parceiro' },
    consents: { requestedPlan: 'Aceito que estes dados sejam usados para preparar e enviar o plano solicitado.', commercial: 'Também aceito ser contatado para conversar sobre este projeto.', updates: 'Quero receber novidades da Agent Friendly Web.' },
    summary: 'Assim ficaria sua solicitação', notSent: 'Ainda não foi enviada. O canal de dados reais será habilitado em um gate separado.', required: 'Necessário para solicitar o plano', optional: 'Opcional e desmarcado por padrão', edit: 'Editar dados', send: 'Confirmar e enviar', unavailable: 'Envio ainda não habilitado', sent: 'Solicitação recebida. O email ainda não é enviado automaticamente.', invalid: 'Revise o email, o domínio e o consentimento necessário.',
    privacy: 'Como estes dados são tratados',
  },
});
