/** @type {Array<'website'|'organization'|'audience'|'languages'|'contentSources'|'control'>} */
const steps = ['website','organization','audience','languages','contentSources','control'];
export function dossierGuideStep(draft) {
  return steps.find(field => field === 'control' ? !draft[field] || draft[field] === 'unknown' : Array.isArray(draft[field]) ? !draft[field].length : !String(draft[field] || '').trim()) || 'review';
}
export const DOSSIER_GUIDE_COPY = {
  es: {title:'Vamos paso a paso',intro:'No hace falta tener todo resuelto. Podemos ordenar lo que ya sabés y dejar lo demás pendiente.',assist:'Contármelo con mis palabras',local:'Esta ayuda organiza tu texto en esta pestaña. Revisá las propuestas antes de aplicarlas; podés corregir los campos del formulario.',draft:'Los cambios propuestos están en tu borrador. Revisalos y usá Guardar cambios cuando estés listo.',steps:{website:['Empecemos por tu sitio.','Así vinculamos el trabajo con la dirección correcta.'],organization:['¿Cómo se llama tu organización?','Usaremos el nombre que nos indiques para describirla con claridad.'],audience:['¿A quién querés ayudar?','Una frase sobre esas personas nos ayuda a preparar respuestas útiles.'],languages:['¿En qué idiomas atendés?','Elegí los idiomas que realmente podés mantener actualizados.'],contentSources:['¿Qué contenido tenés a mano?','Puede ser tu web o preguntas frecuentes. Indicá lo que existe; no hace falta crear todo ahora.'],control:['¿Quién puede hacer cambios en tu sitio?','Si no lo sabés, dejalo pendiente. Lo confirmaremos antes de preparar una entrega.'],review:['Ya tenemos una base para revisar.','Comprobá los datos y el estado de guardado. Luego revisá los recursos y responsables antes de preparar la cápsula.']}},
  en: {title:'One step at a time',intro:'You do not need every answer yet. We can organize what you know and leave the rest open.',assist:'Explain it in my own words',local:'This helper organizes your text in this tab. Review suggestions before applying them; you can edit the form fields.',draft:'The proposed changes are in your draft. Review them and use Save changes when ready.',steps:{website:['Let’s start with your website.','This connects the work to the right address.'],organization:['What is your organization called?','We will use the name you provide to describe it clearly.'],audience:['Who do you want to help?','One sentence about those people helps us prepare useful answers.'],languages:['Which languages do you support?','Choose languages you can keep up to date.'],contentSources:['What content do you already have?','Your website or FAQs are a good start. Select what exists; you do not need to create everything now.'],control:['Who can change your website?','If you are unsure, leave this open. We will confirm it before preparing delivery.'],review:['We have a starting point to review.','Check the details and save status. Then review resources and responsible people before preparing the capsule.']}},
  pt: {title:'Um passo de cada vez',intro:'Você não precisa ter todas as respostas. Podemos organizar o que já sabe e deixar o resto pendente.',assist:'Contar com minhas palavras',local:'Esta ajuda organiza seu texto nesta aba. Revise as sugestões antes de aplicá-las; você pode corrigir os campos do formulário.',draft:'As alterações propostas estão no rascunho. Revise e use Salvar alterações quando estiver pronto.',steps:{website:['Vamos começar pelo seu site.','Assim vinculamos o trabalho ao endereço certo.'],organization:['Qual é o nome da sua organização?','Usaremos o nome informado para descrevê-la com clareza.'],audience:['Quem você quer ajudar?','Uma frase sobre essas pessoas nos ajuda a preparar respostas úteis.'],languages:['Em quais idiomas você atende?','Escolha idiomas que consegue manter atualizados.'],contentSources:['Que conteúdo você já tem?','Seu site ou perguntas frequentes são um bom começo. Indique o que existe; não precisa criar tudo agora.'],control:['Quem pode alterar seu site?','Se não souber, deixe pendente. Confirmaremos antes de preparar a entrega.'],review:['Já temos uma base para revisar.','Confira os dados e o estado de salvamento. Depois revise os recursos e responsáveis antes de preparar a cápsula.']}}
};
