const commonGoals = {
  es: [['discovery', 'Aparecer en respuestas y búsquedas'], ['content', 'Explicar mejor productos o servicios'], ['tools', 'Exponer APIs, MCP o skills'], ['actions', 'Permitir acciones delegadas'], ['payments', 'Preparar pagos entre agentes']],
  en: [['discovery', 'Appear in answers and search'], ['content', 'Explain products or services better'], ['tools', 'Expose APIs, MCP or skills'], ['actions', 'Enable delegated actions'], ['payments', 'Prepare agent-to-agent payments']],
  pt: [['discovery', 'Aparecer em respostas e buscas'], ['content', 'Explicar melhor produtos ou serviços'], ['tools', 'Expor APIs, MCP ou skills'], ['actions', 'Permitir ações delegadas'], ['payments', 'Preparar pagamentos entre agentes']],
};

const commonContent = {
  es: [['catalog', 'Catálogo o colección'], ['services', 'Servicios'], ['faq', 'Preguntas frecuentes'], ['documentation', 'Documentación'], ['policies', 'Políticas y condiciones'], ['tool_docs', 'APIs y herramientas']],
  en: [['catalog', 'Catalog or collection'], ['services', 'Services'], ['faq', 'Frequently asked questions'], ['documentation', 'Documentation'], ['policies', 'Policies and terms'], ['tool_docs', 'APIs and tools']],
  pt: [['catalog', 'Catálogo ou coleção'], ['services', 'Serviços'], ['faq', 'Perguntas frequentes'], ['documentation', 'Documentação'], ['policies', 'Políticas e condições'], ['tool_docs', 'APIs e ferramentas']],
};

const commonCapabilities = {
  es: [['discovery', 'Descubrimiento'], ['answerability', 'Respuestas precisas'], ['structured_data', 'Datos estructurados'], ['public_registry', 'Perfil público verificable'], ['read_only_tools', 'Herramientas de consulta'], ['delegated_actions', 'Acciones delegadas futuras']],
  en: [['discovery', 'Discovery'], ['answerability', 'Precise answers'], ['structured_data', 'Structured data'], ['public_registry', 'Verifiable public profile'], ['read_only_tools', 'Read-only tools'], ['delegated_actions', 'Future delegated actions']],
  pt: [['discovery', 'Descoberta'], ['answerability', 'Respostas precisas'], ['structured_data', 'Dados estruturados'], ['public_registry', 'Perfil público verificável'], ['read_only_tools', 'Ferramentas de consulta'], ['delegated_actions', 'Ações delegadas futuras']],
};

const commonResources = [['robots', 'robots.txt'], ['sitemap', 'sitemap.xml'], ['llms', 'llms.txt'], ['llms_full', 'llms-full.txt'], ['jsonld', 'JSON-LD'], ['openapi', 'OpenAPI'], ['mcp', 'MCP'], ['skills', 'Skills']];

export const PRIVATE_UI_COPY = Object.freeze({
  es: {
    registry: {
      eyebrow: 'Registry público y verificable', title: 'Sitios que empezaron a explicar mejor lo que son, ofrecen y permiten.',
      intro: 'Cada perfil separa lo declarado por su responsable, lo observado en recursos públicos y el control temporal del dominio verificado.',
      profiles: 'perfiles publicados', searchLabel: 'Buscar organización, dominio, sector, idioma o nivel AF', placeholder: 'Ejemplo: museo, arte, Español, AF-2', search: 'Buscar',
      results: 'resultados', disclaimer: 'Un perfil no garantiza indexación, recomendación ni calidad comercial.', verified: 'Dominio verificado', open: 'Abrir perfil',
      emptyTitle: 'No hay perfiles que coincidan.', emptyBody: 'Prueba una búsqueda más amplia o vuelve al listado completo.', all: 'Ver todos',
    },
    profile: {
      publicProfile: 'Perfil público', observedLevel: 'Nivel observado', noAudit: 'Sin auditoría guardada', ownerDeclared: 'Declarado por el owner',
      observed: 'Observado públicamente', verified: 'Dominio verificado', identityTitle: 'Identidad pública', identityBody: 'Lo que el responsable autorizó a publicar sobre el sitio.',
      siteType: 'Tipo de sitio', audiences: 'Audiencias', sectors: 'Sectores', languages: 'Idiomas', notDeclared: 'No declarado',
      capabilitiesTitle: 'Capacidades y evidencia', capabilitiesBody: 'Declarar una capacidad no equivale a haberla observado en el sitio.', declared: 'Declaradas', observedPlural: 'Observadas',
      noDeclaredCapabilities: 'Sin capacidades declaradas.', noObservation: 'No hay una observación pública guardada.', sourcesTitle: 'Fuentes públicas', sourcesBody: 'Enlaces directos y fecha asociada a cada afirmación.',
      siteIdentity: 'Identidad del sitio', method: 'Método', registered: 'Registrado', validUntil: 'Vigente hasta', notRegistered: 'No registrado', notApplicable: 'No aplica al caso curado',
      agentFormats: 'Formatos para agentes', json: 'JSON verificable', markdown: 'Markdown legible', history: 'Historial', historyText: 'Esta versión fue publicada y las nuevas versiones no borran las anteriores.',
      limitsTitle: 'Qué no significa este perfil', back: 'Registry', verifiedLabel: 'Verificado', observedLabel: 'Observado', ownerLabel: 'Declarado por el owner', curatedLabel: 'Caso curado por el owner', notObserved: 'No observado',
    },
    dossier: { privateSession: 'Sesión privada', signOut: 'Cerrar sesión', title: 'Ordena el sitio, sus contenidos y las decisiones de publicación.', intro: 'No hace falta conocer términos técnicos. El formulario guarda avances y separa lo declarado, lo verificado y lo que todavía no se publica.' },
    intake: {
      sections: [['identity', 'Identidad y contexto', 'Quién eres y qué representa el sitio.'], ['goals', 'Objetivos', 'Puedes elegir más de uno y cambiarlos después.'], ['control', 'Control técnico', 'Esto define qué mejoras pueden hacerse ahora.'], ['languages', 'Idiomas', 'En qué idiomas deben comprenderte personas y agentes.'], ['content', 'Contenido disponible', 'Marca lo que ya existe, aunque esté disperso o incompleto.'], ['capabilities', 'Capacidades y recursos', 'Define un alcance preliminar, sin habilitar escritura.'], ['publication', 'Publicación y crawlers', 'Decide cómo se descubre y usa el contenido público.'], ['governance', 'Responsables y control', 'Quién mantiene, administra DNS y aprueba cada publicación.']],
      goals: commonGoals.es, content: commonContent.es, capabilities: commonCapabilities.es, resources: commonResources,
      languages: ['Español', 'Inglés', 'Portugués', 'Italiano', 'Francés'], pageEyebrow: 'Expediente privado',
      organization: 'Organización o proyecto', website: 'Sitio web', role: 'Tu función', siteType: 'Tipo de sitio', choose: 'Elegir', audience: 'A quiénes quieres llegar',
      labels: { control: 'Qué control tienes', cms: 'Sistema de contenidos', hosting: 'Alojamiento', noSecrets: 'No ingreses contraseñas ni claves.', noSecretsBody: 'Solo necesitamos saber qué acceso existe. Las credenciales se gestionan por un canal separado y seguro.', notes: 'Notas o información desordenada', desired: 'Capacidades deseadas', proposed: 'Recursos propuestos', scope: 'Esta selección expresa un alcance para revisión. No entrega permisos, no modifica el sitio y no habilita acciones automáticas.', firstPublication: 'Primera publicación', searchPolicy: 'Política de búsqueda', trainingPolicy: 'Uso para entrenamiento', monitoring: 'Seguimiento', maintainer: 'Mantenedor actual', maintainerEmail: 'Email del mantenedor', dns: 'Proveedor DNS', approver: 'Responsable de aprobación', approverEmail: 'Email de aprobación', verify: 'Verificar dominio', verifySubtitle: 'Prueba control temporal mediante DNS o un archivo público.', createInstructions: 'Crear instrucciones', checkNow: 'Comprobar ahora', copied: 'Copiado', copyInstructions: 'Copiar instrucciones', observation: 'Observación fechada', observationSubtitle: 'Guarda una fotografía técnica saneada del sitio público.', auditSave: 'Auditar y guardar observación', contextGathered: 'Contexto reunido', decisions: 'decisiones', nextQuestion: 'Próxima pregunta', firstRoadmap: 'Primer roadmap' },
      siteTypes: [['artist', 'Artista'], ['gallery', 'Galería'], ['museum', 'Museo o archivo'], ['institution', 'Institución'], ['commerce', 'Comercio o servicio'], ['other', 'Otro']],
      controls: [['unknown', 'No lo sé'], ['origin', 'Acceso al sitio o código'], ['dns', 'Acceso al dominio o Cloudflare'], ['provider', 'Dependo de un proveedor'], ['none', 'No tengo acceso']],
      publication: [['registry_first', 'Primero en el Registry'], ['origin_first', 'Primero en el sitio original'], ['both', 'En ambos, coordinadamente'], ['review_only', 'Solo preparar y revisar']],
      searchPolicies: [['allow', 'Permitir búsqueda y asistentes'], ['limited', 'Permitir con límites declarados'], ['deny', 'No permitir por ahora']],
      trainingPolicies: [['reserve', 'Reservar: no autorizar'], ['allow', 'Autorizar contenido público'], ['case_by_case', 'Evaluar caso por caso']],
      monitoring: [['none', 'Sin seguimiento'], ['monthly', 'Revisión mensual'], ['quarterly', 'Revisión trimestral'], ['incident', 'Solo ante cambios o incidentes']],
      saveIdle: 'Los cambios se guardan automáticamente.', loading: 'Buscando un expediente anterior...', recovered: 'Expediente recuperado.', newDossier: 'Nuevo expediente. Completa los datos a tu ritmo.',
      verifyTitle: 'Verificación de dominio', verifyBody: 'Acredita control temporal del dominio sin entregar contraseñas ni conceder escritura.', auditTitle: 'Observación pública',
      capsuleTitle: 'Cápsula de implementación', capsuleBody: 'Prepara un paquete exacto y revisable sin compartir claves.',
    },
    capsule: {
      privateReview: 'Revisión privada', signOut: 'Cerrar sesión', eyebrow: 'Handoff controlado', pageTitle: 'Revisa la versión exacta antes de autorizarla.',
      pageIntro: 'Esta pantalla solo permite leer, descargar, aprobar o rechazar la cápsula. No muestra el resto del expediente y no modifica el sitio.',
      title: 'Cápsula de implementación', subtitle: 'Un paquete exacto para revisar y entregar sin compartir claves.', noWrite: 'No modifica el sitio.',
      noWriteBody: 'Preparar, descargar o aprobar esta versión no publica archivos, no abre un PR y no entra en WordPress.',
      emptyTitle: 'Primero se prepara una vista previa.', emptyBody: 'El sistema toma solo campos públicos y recursos autorizados. Los archivos que requieren fusión quedan para revisión manual.', prepare: 'Preparar vista previa',
      version: 'Versión', domain: 'Dominio', expires: 'Vence', manifest: 'Manifiesto', files: 'Archivos incluidos', packagePath: 'Dentro del paquete', operation: 'Operación', size: 'Tamaño',
      deferred: 'Recursos que requieren implementación separada', compareTitle: 'Comparar con el sitio actual', compareBody: 'Solo lee archivos públicos. No inicia sesión, no usa claves y no modifica el origen.', compare: 'Comparar con el sitio actual', compareAgain: 'Volver a consultar', differences: 'Revisar diferencias', complete: 'Comparación completa', incomplete: 'Comparación incompleta', observed: 'Observada', noOrigin: 'sin origen', diffLabel: 'Diferencias para', truncated: 'Vista acotada por seguridad. Descarga la comparación para revisar el registro disponible.', noComparable: 'No hay contenido comparable para mostrar.', downloadComparison: 'Descargar comparación',
      draftTitle: 'Preparar borrador técnico', draftBody: 'Describe archivos y rutas para revisión. No crea un PR, no hace merge y no publica.', notSent: 'No enviado', repository: 'Repositorio GitHub', baseBranch: 'Rama base', reviewer: 'Revisor humano', proposedLocation: 'Ubicación propuesta dentro del repositorio', proposedLocationBody: 'Los archivos que requieren fusión manual se guardan como propuestas separadas y nunca reemplazan contenido automáticamente.', prepareDraft: 'Preparar borrador técnico', status: 'Estado', proposedBranch: 'Rama propuesta', downloadDraft: 'Descargar borrador técnico',
      ownerApproval: 'Aprobación del owner', maintainerApproval: 'Aprobación del mantenedor', downloadJson: 'Descargar paquete JSON', openPrivate: 'Abrir revisión privada', copied: 'Enlace copiado', copyMaintainer: 'Copiar enlace para el mantenedor', newVersion: 'Preparar nueva versión', approve: 'Aprobar esta versión', reject: 'Rechazar esta versión',
      operations: { create_or_replace: 'Crear o reemplazar luego de revisar', manual_merge: 'Integrar manualmente con el archivo actual', manual_embed: 'Insertar manualmente en la página indicada' },
      statuses: { owner_approval_pending: 'Esperando aprobación del owner', maintainer_approval_pending: 'Esperando aprobación del mantenedor', approved_for_manual_handoff: 'Aprobada para entrega manual', rejected: 'Versión rechazada', expired: 'Versión vencida', empty: 'Sin cápsula preparada', approved: 'Aprobada', not_required: 'No requerida', pending: 'Pendiente' },
      comparisonStatuses: { missing: 'No existe todavía', unchanged: 'Sin cambios', changed: 'Cambio directo propuesto', manual_review_required: 'Integración manual necesaria', unavailable: 'No se pudo leer', blocked: 'Bloqueado por seguridad' },
      messages: { empty: 'Todavía no se preparó una cápsula para este expediente.', loaded: 'Esta es la última versión preparada. Revisa cada archivo antes de decidir.', previewReady: 'Vista previa lista. No se modificó el sitio.', privateLinkCopied: 'Enlace privado copiado. Solo una identidad autorizada podrá abrirlo.', privateLinkFailed: 'No se pudo copiar automáticamente. Abre la revisión y copia la URL del navegador.' },
    },
  },
  en: {
    registry: {
      eyebrow: 'Public and verifiable Registry', title: 'Websites that have started explaining what they are, offer and permit.',
      intro: 'Each profile separates owner declarations, evidence observed in public resources and time-bound verification of domain control.',
      profiles: 'published profiles', searchLabel: 'Search organization, domain, sector, language or AF level', placeholder: 'Example: museum, art, English, AF-2', search: 'Search',
      results: 'results', disclaimer: 'A profile does not guarantee indexing, recommendation or commercial quality.', verified: 'Verified domain', open: 'Open profile',
      emptyTitle: 'No matching profiles.', emptyBody: 'Try a broader search or return to the complete listing.', all: 'View all',
    },
    profile: {
      publicProfile: 'Public profile', observedLevel: 'Observed level', noAudit: 'No saved audit', ownerDeclared: 'Owner-declared', observed: 'Publicly observed', verified: 'Verified domain',
      identityTitle: 'Public identity', identityBody: 'Information the responsible owner authorized for publication.', siteType: 'Website type', audiences: 'Audiences', sectors: 'Sectors', languages: 'Languages', notDeclared: 'Not declared',
      capabilitiesTitle: 'Capabilities and evidence', capabilitiesBody: 'Declaring a capability does not mean it was observed on the website.', declared: 'Declared', observedPlural: 'Observed',
      noDeclaredCapabilities: 'No declared capabilities.', noObservation: 'No saved public observation.', sourcesTitle: 'Public sources', sourcesBody: 'Direct links and the date associated with each claim.',
      siteIdentity: 'Website identity', method: 'Method', registered: 'Recorded', validUntil: 'Valid until', notRegistered: 'Not recorded', notApplicable: 'Not applicable to the curated case',
      agentFormats: 'Formats for agents', json: 'Verifiable JSON', markdown: 'Readable Markdown', history: 'History', historyText: 'This version was published and later versions do not erase earlier ones.',
      limitsTitle: 'What this profile does not mean', back: 'Registry', verifiedLabel: 'Verified', observedLabel: 'Observed', ownerLabel: 'Owner-declared', curatedLabel: 'Owner-curated case', notObserved: 'Not observed',
    },
    dossier: { privateSession: 'Private session', signOut: 'Sign out', title: 'Organize the website, its content and publication decisions.', intro: 'No technical knowledge is required. The form saves progress and separates declarations, verification and material that is not yet public.' },
    intake: {
      sections: [['identity', 'Identity and context', 'Who you are and what the website represents.'], ['goals', 'Goals', 'Choose more than one and change them later.'], ['control', 'Technical control', 'Defines which improvements can be made now.'], ['languages', 'Languages', 'Languages in which people and agents should understand you.'], ['content', 'Available content', 'Mark what exists even when dispersed or incomplete.'], ['capabilities', 'Capabilities and resources', 'Define a preliminary scope without enabling writes.'], ['publication', 'Publishing and crawlers', 'Decide how public content is discovered and used.'], ['governance', 'Owners and control', 'Who maintains, manages DNS and approves each publication.']],
      goals: commonGoals.en, content: commonContent.en, capabilities: commonCapabilities.en, resources: commonResources,
      languages: ['Spanish', 'English', 'Portuguese', 'Italian', 'French'], pageEyebrow: 'Private dossier',
      organization: 'Organization or project', website: 'Website', role: 'Your role', siteType: 'Website type', choose: 'Choose', audience: 'Who should you reach',
      labels: { control: 'What control do you have', cms: 'Content system', hosting: 'Hosting', noSecrets: 'Do not enter passwords or keys.', noSecretsBody: 'We only need to know which access exists. Credentials belong in a separate controlled channel.', notes: 'Unstructured notes or information', desired: 'Desired capabilities', proposed: 'Proposed resources', scope: 'This selection defines a scope for review. It grants no permissions, changes no website and enables no automatic actions.', firstPublication: 'First publication', searchPolicy: 'Search policy', trainingPolicy: 'Use for training', monitoring: 'Monitoring', maintainer: 'Current maintainer', maintainerEmail: 'Maintainer email', dns: 'DNS provider', approver: 'Approval owner', approverEmail: 'Approval email', verify: 'Verify domain', verifySubtitle: 'Prove time-bound control through DNS or a public file.', createInstructions: 'Create instructions', checkNow: 'Check now', copied: 'Copied', copyInstructions: 'Copy instructions', observation: 'Dated observation', observationSubtitle: 'Save a sanitized technical snapshot of the public website.', auditSave: 'Audit and save observation', contextGathered: 'Context gathered', decisions: 'decisions', nextQuestion: 'Next question', firstRoadmap: 'First roadmap' },
      siteTypes: [['artist', 'Artist'], ['gallery', 'Gallery'], ['museum', 'Museum or archive'], ['institution', 'Institution'], ['commerce', 'Business or service'], ['other', 'Other']],
      controls: [['unknown', 'I do not know'], ['origin', 'Website or source access'], ['dns', 'Domain or Cloudflare access'], ['provider', 'I depend on a provider'], ['none', 'I have no access']],
      publication: [['registry_first', 'Registry first'], ['origin_first', 'Original website first'], ['both', 'Both, coordinated'], ['review_only', 'Prepare and review only']],
      searchPolicies: [['allow', 'Allow search and assistants'], ['limited', 'Allow with declared limits'], ['deny', 'Do not allow yet']],
      trainingPolicies: [['reserve', 'Reserve: do not authorize'], ['allow', 'Authorize public content'], ['case_by_case', 'Evaluate case by case']],
      monitoring: [['none', 'No monitoring'], ['monthly', 'Monthly review'], ['quarterly', 'Quarterly review'], ['incident', 'Changes or incidents only']],
      saveIdle: 'Changes are saved automatically.', loading: 'Looking for an existing dossier...', recovered: 'Dossier recovered.', newDossier: 'New dossier. Complete it at your own pace.',
      verifyTitle: 'Domain verification', verifyBody: 'Proves time-bound domain control without sharing passwords or granting write access.', auditTitle: 'Public observation',
      capsuleTitle: 'Implementation capsule', capsuleBody: 'Prepare an exact, reviewable package without sharing credentials.',
    },
    capsule: {
      privateReview: 'Private review', signOut: 'Sign out', eyebrow: 'Controlled handoff', pageTitle: 'Review the exact version before authorizing it.',
      pageIntro: 'This screen only allows reading, downloading, approving or rejecting the capsule. It does not expose the rest of the dossier or modify the website.',
      title: 'Implementation capsule', subtitle: 'An exact package to review and deliver without sharing credentials.', noWrite: 'It does not modify the website.',
      noWriteBody: 'Preparing, downloading or approving this version publishes no files, opens no PR and never signs in to WordPress.',
      emptyTitle: 'A preview is prepared first.', emptyBody: 'The system uses only public fields and authorized resources. Files requiring a merge remain subject to manual review.', prepare: 'Prepare preview',
      version: 'Version', domain: 'Domain', expires: 'Expires', manifest: 'Manifest', files: 'Included files', packagePath: 'Inside the package', operation: 'Operation', size: 'Size',
      deferred: 'Resources requiring separate implementation', compareTitle: 'Compare with the current website', compareBody: 'Reads public files only. It does not sign in, use credentials or modify the origin.', compare: 'Compare with current website', compareAgain: 'Check again', differences: 'Review differences', complete: 'Complete comparison', incomplete: 'Incomplete comparison', observed: 'Observed', noOrigin: 'no origin', diffLabel: 'Differences for', truncated: 'The preview is limited for safety. Download the comparison to review the available record.', noComparable: 'No comparable content to display.', downloadComparison: 'Download comparison',
      draftTitle: 'Prepare technical draft', draftBody: 'Describes files and paths for review. It creates no PR, performs no merge and publishes nothing.', notSent: 'Not sent', repository: 'GitHub repository', baseBranch: 'Base branch', reviewer: 'Human reviewer', proposedLocation: 'Proposed repository location', proposedLocationBody: 'Files requiring a manual merge are stored as separate proposals and never replace content automatically.', prepareDraft: 'Prepare technical draft', status: 'Status', proposedBranch: 'Proposed branch', downloadDraft: 'Download technical draft',
      ownerApproval: 'Owner approval', maintainerApproval: 'Maintainer approval', downloadJson: 'Download JSON package', openPrivate: 'Open private review', copied: 'Link copied', copyMaintainer: 'Copy link for maintainer', newVersion: 'Prepare new version', approve: 'Approve this version', reject: 'Reject this version',
      operations: { create_or_replace: 'Create or replace after review', manual_merge: 'Merge manually with the current file', manual_embed: 'Embed manually in the indicated page' },
      statuses: { owner_approval_pending: 'Waiting for owner approval', maintainer_approval_pending: 'Waiting for maintainer approval', approved_for_manual_handoff: 'Approved for manual handoff', rejected: 'Version rejected', expired: 'Version expired', empty: 'No capsule prepared', approved: 'Approved', not_required: 'Not required', pending: 'Pending' },
      comparisonStatuses: { missing: 'Does not exist yet', unchanged: 'No changes', changed: 'Direct change proposed', manual_review_required: 'Manual integration required', unavailable: 'Could not be read', blocked: 'Blocked for safety' },
      messages: { empty: 'No capsule has been prepared for this dossier yet.', loaded: 'This is the latest prepared version. Review every file before deciding.', previewReady: 'Preview ready. The website was not modified.', privateLinkCopied: 'Private link copied. Only an authorized identity can open it.', privateLinkFailed: 'The link could not be copied automatically. Open the review and copy the browser URL.' },
    },
  },
  pt: {
    registry: {
      eyebrow: 'Registry público e verificável', title: 'Sites que começaram a explicar melhor o que são, oferecem e permitem.',
      intro: 'Cada perfil separa declarações do owner, evidências observadas em recursos públicos e verificação temporária do controle do domínio.',
      profiles: 'perfis publicados', searchLabel: 'Buscar organização, domínio, setor, idioma ou nível AF', placeholder: 'Exemplo: museu, arte, Português, AF-2', search: 'Buscar',
      results: 'resultados', disclaimer: 'Um perfil não garante indexação, recomendação ou qualidade comercial.', verified: 'Domínio verificado', open: 'Abrir perfil',
      emptyTitle: 'Nenhum perfil correspondente.', emptyBody: 'Tente uma busca mais ampla ou volte à lista completa.', all: 'Ver todos',
    },
    profile: {
      publicProfile: 'Perfil público', observedLevel: 'Nível observado', noAudit: 'Sem auditoria salva', ownerDeclared: 'Declarado pelo owner', observed: 'Observado publicamente', verified: 'Domínio verificado',
      identityTitle: 'Identidade pública', identityBody: 'Informação que o responsável autorizou publicar.', siteType: 'Tipo de site', audiences: 'Públicos', sectors: 'Setores', languages: 'Idiomas', notDeclared: 'Não declarado',
      capabilitiesTitle: 'Capacidades e evidências', capabilitiesBody: 'Declarar uma capacidade não significa que ela foi observada no site.', declared: 'Declaradas', observedPlural: 'Observadas',
      noDeclaredCapabilities: 'Sem capacidades declaradas.', noObservation: 'Não há observação pública salva.', sourcesTitle: 'Fontes públicas', sourcesBody: 'Links diretos e data associada a cada afirmação.',
      siteIdentity: 'Identidade do site', method: 'Método', registered: 'Registrado', validUntil: 'Válido até', notRegistered: 'Não registrado', notApplicable: 'Não se aplica ao caso curado',
      agentFormats: 'Formatos para agentes', json: 'JSON verificável', markdown: 'Markdown legível', history: 'Histórico', historyText: 'Esta versão foi publicada e versões futuras não apagam as anteriores.',
      limitsTitle: 'O que este perfil não significa', back: 'Registry', verifiedLabel: 'Verificado', observedLabel: 'Observado', ownerLabel: 'Declarado pelo owner', curatedLabel: 'Caso curado pelo owner', notObserved: 'Não observado',
    },
    dossier: { privateSession: 'Sessão privada', signOut: 'Sair', title: 'Organize o site, seus conteúdos e decisões de publicação.', intro: 'Não é necessário conhecimento técnico. O formulário salva avanços e separa declarações, verificações e o que ainda não é público.' },
    intake: {
      sections: [['identity', 'Identidade e contexto', 'Quem você é e o que o site representa.'], ['goals', 'Objetivos', 'Escolha mais de um e altere depois.'], ['control', 'Controle técnico', 'Define quais melhorias podem ser feitas agora.'], ['languages', 'Idiomas', 'Idiomas em que pessoas e agentes devem compreender você.'], ['content', 'Conteúdo disponível', 'Marque o que existe mesmo disperso ou incompleto.'], ['capabilities', 'Capacidades e recursos', 'Defina um escopo preliminar sem habilitar escrita.'], ['publication', 'Publicação e crawlers', 'Decida como o conteúdo público é descoberto e usado.'], ['governance', 'Responsáveis e controle', 'Quem mantém, administra DNS e aprova cada publicação.']],
      goals: commonGoals.pt, content: commonContent.pt, capabilities: commonCapabilities.pt, resources: commonResources,
      languages: ['Espanhol', 'Inglês', 'Português', 'Italiano', 'Francês'], pageEyebrow: 'Dossiê privado',
      organization: 'Organização ou projeto', website: 'Site', role: 'Sua função', siteType: 'Tipo de site', choose: 'Escolher', audience: 'Quem você deseja alcançar',
      labels: { control: 'Qual controle você possui', cms: 'Sistema de conteúdo', hosting: 'Hospedagem', noSecrets: 'Não informe senhas ou chaves.', noSecretsBody: 'Precisamos apenas saber qual acesso existe. Credenciais usam um canal separado e controlado.', notes: 'Notas ou informações desorganizadas', desired: 'Capacidades desejadas', proposed: 'Recursos propostos', scope: 'Esta seleção define escopo para revisão. Não concede permissões, não modifica o site e não habilita ações automáticas.', firstPublication: 'Primeira publicação', searchPolicy: 'Política de busca', trainingPolicy: 'Uso para treinamento', monitoring: 'Monitoramento', maintainer: 'Mantenedor atual', maintainerEmail: 'Email do mantenedor', dns: 'Provedor DNS', approver: 'Responsável pela aprovação', approverEmail: 'Email de aprovação', verify: 'Verificar domínio', verifySubtitle: 'Comprove controle temporário por DNS ou arquivo público.', createInstructions: 'Criar instruções', checkNow: 'Verificar agora', copied: 'Copiado', copyInstructions: 'Copiar instruções', observation: 'Observação datada', observationSubtitle: 'Salve uma fotografia técnica saneada do site público.', auditSave: 'Auditar e salvar observação', contextGathered: 'Contexto reunido', decisions: 'decisões', nextQuestion: 'Próxima pergunta', firstRoadmap: 'Primeiro roadmap' },
      siteTypes: [['artist', 'Artista'], ['gallery', 'Galeria'], ['museum', 'Museu ou arquivo'], ['institution', 'Instituição'], ['commerce', 'Comércio ou serviço'], ['other', 'Outro']],
      controls: [['unknown', 'Não sei'], ['origin', 'Acesso ao site ou código'], ['dns', 'Acesso ao domínio ou Cloudflare'], ['provider', 'Dependo de um provedor'], ['none', 'Não tenho acesso']],
      publication: [['registry_first', 'Primeiro no Registry'], ['origin_first', 'Primeiro no site original'], ['both', 'Nos dois, de forma coordenada'], ['review_only', 'Somente preparar e revisar']],
      searchPolicies: [['allow', 'Permitir busca e assistentes'], ['limited', 'Permitir com limites declarados'], ['deny', 'Não permitir por enquanto']],
      trainingPolicies: [['reserve', 'Reservar: não autorizar'], ['allow', 'Autorizar conteúdo público'], ['case_by_case', 'Avaliar caso a caso']],
      monitoring: [['none', 'Sem monitoramento'], ['monthly', 'Revisão mensal'], ['quarterly', 'Revisão trimestral'], ['incident', 'Somente mudanças ou incidentes']],
      saveIdle: 'As mudanças são salvas automaticamente.', loading: 'Procurando um dossiê anterior...', recovered: 'Dossiê recuperado.', newDossier: 'Novo dossiê. Complete no seu ritmo.',
      verifyTitle: 'Verificação de domínio', verifyBody: 'Comprova controle temporário sem compartilhar senhas ou conceder escrita.', auditTitle: 'Observação pública',
      capsuleTitle: 'Cápsula de implementação', capsuleBody: 'Prepare um pacote exato e revisável sem compartilhar credenciais.',
    },
    capsule: {
      privateReview: 'Revisão privada', signOut: 'Sair', eyebrow: 'Handoff controlado', pageTitle: 'Revise a versão exata antes de autorizá-la.',
      pageIntro: 'Esta tela permite apenas ler, baixar, aprovar ou rejeitar a cápsula. Não mostra o restante do dossiê nem modifica o site.',
      title: 'Cápsula de implementação', subtitle: 'Um pacote exato para revisar e entregar sem compartilhar credenciais.', noWrite: 'Não modifica o site.',
      noWriteBody: 'Preparar, baixar ou aprovar esta versão não publica arquivos, não abre PR e não entra no WordPress.',
      emptyTitle: 'Primeiro é preparado um preview.', emptyBody: 'O sistema usa somente campos públicos e recursos autorizados. Arquivos que exigem merge ficam para revisão manual.', prepare: 'Preparar preview',
      version: 'Versão', domain: 'Domínio', expires: 'Vence', manifest: 'Manifesto', files: 'Arquivos incluídos', packagePath: 'Dentro do pacote', operation: 'Operação', size: 'Tamanho',
      deferred: 'Recursos que exigem implementação separada', compareTitle: 'Comparar com o site atual', compareBody: 'Lê somente arquivos públicos. Não faz login, não usa credenciais e não modifica a origem.', compare: 'Comparar com o site atual', compareAgain: 'Consultar novamente', differences: 'Revisar diferenças', complete: 'Comparação completa', incomplete: 'Comparação incompleta', observed: 'Observada', noOrigin: 'sem origem', diffLabel: 'Diferenças para', truncated: 'O preview é limitado por segurança. Baixe a comparação para revisar o registro disponível.', noComparable: 'Não há conteúdo comparável.', downloadComparison: 'Baixar comparação',
      draftTitle: 'Preparar rascunho técnico', draftBody: 'Descreve arquivos e rotas para revisão. Não cria PR, não faz merge e não publica.', notSent: 'Não enviado', repository: 'Repositório GitHub', baseBranch: 'Branch base', reviewer: 'Revisor humano', proposedLocation: 'Local proposto no repositório', proposedLocationBody: 'Arquivos que exigem merge manual ficam como propostas separadas e nunca substituem conteúdo automaticamente.', prepareDraft: 'Preparar rascunho técnico', status: 'Estado', proposedBranch: 'Branch proposta', downloadDraft: 'Baixar rascunho técnico',
      ownerApproval: 'Aprovação do owner', maintainerApproval: 'Aprovação do mantenedor', downloadJson: 'Baixar pacote JSON', openPrivate: 'Abrir revisão privada', copied: 'Link copiado', copyMaintainer: 'Copiar link para o mantenedor', newVersion: 'Preparar nova versão', approve: 'Aprovar esta versão', reject: 'Rejeitar esta versão',
      operations: { create_or_replace: 'Criar ou substituir após revisão', manual_merge: 'Integrar manualmente com o arquivo atual', manual_embed: 'Inserir manualmente na página indicada' },
      statuses: { owner_approval_pending: 'Aguardando aprovação do owner', maintainer_approval_pending: 'Aguardando aprovação do mantenedor', approved_for_manual_handoff: 'Aprovada para entrega manual', rejected: 'Versão rejeitada', expired: 'Versão vencida', empty: 'Sem cápsula preparada', approved: 'Aprovada', not_required: 'Não exigida', pending: 'Pendente' },
      comparisonStatuses: { missing: 'Ainda não existe', unchanged: 'Sem mudanças', changed: 'Mudança direta proposta', manual_review_required: 'Integração manual necessária', unavailable: 'Não foi possível ler', blocked: 'Bloqueado por segurança' },
      messages: { empty: 'Ainda não foi preparada uma cápsula para este dossiê.', loaded: 'Esta é a última versão preparada. Revise cada arquivo antes de decidir.', previewReady: 'Preview pronto. O site não foi modificado.', privateLinkCopied: 'Link privado copiado. Somente uma identidade autorizada poderá abri-lo.', privateLinkFailed: 'Não foi possível copiar automaticamente. Abra a revisão e copie a URL do navegador.' },
    },
  },
});

export function privateUiCopy(locale = 'es') {
  return PRIVATE_UI_COPY[locale] || PRIVATE_UI_COPY.es;
}
