export const SECTOR_CONTENT = Object.freeze({
  es: {
    locale: 'es',
    eyebrow: 'Aplicacion por sector',
    title: 'Cada organizacion necesita ser comprendida por sus propios hechos, servicios y decisiones.',
    intro: 'La misma base tecnica cambia segun el sector. Agent Friendly Web ordena lo que una persona necesita decidir y lo que un agente necesita encontrar, citar o usar sin inventar capacidades.',
    languageLabel: 'Idioma',
    sectors: [
      { audience: 'Arte, cultura y colecciones', value: 'Expone autores, obras, colecciones, procedencia, servicios y limites con fuentes verificables.', firstStep: 'Conciliar catalogo, fichas, preguntas frecuentes y politica publica antes de crear herramientas.' },
      { audience: 'Museos, galerias y archivos', value: 'Hace descubribles horarios, sedes, exposiciones, colecciones, accesibilidad y canales de consulta.', firstStep: 'Definir una fuente canonica por dato y separar informacion publica de expedientes privados.' },
      { audience: 'Municipios e instituciones', value: 'Reduce respuestas ambiguas sobre tramites, requisitos, turnos, oficinas, fechas y normativa.', firstStep: 'Versionar cada tramite con responsable, vigencia, fuente y proximo control.' },
      { audience: 'Comercios y servicios', value: 'Aclara oferta, ubicacion, disponibilidad, reservas, condiciones y contacto sin depender solo de una landing.', firstStep: 'Publicar respuestas directas y datos estructurados coherentes con la experiencia humana.' },
      { audience: 'SaaS y plataformas', value: 'Separa documentacion, APIs, seguridad, precios, limites y capacidades realmente desplegadas.', firstStep: 'Crear un catalogo verificable y marcar planned, research y deployed sin mezclarlos.' },
      { audience: 'Profesionales y estudios', value: 'Permite que agentes comprendan especialidad, jurisdiccion, alcance, evidencia y forma de contratacion.', firstStep: 'Transformar conocimiento disperso en preguntas, fuentes, casos y limites revisables.' },
    ],
    closingTitle: 'La meta no es aparecer con cualquier respuesta. Es que la respuesta correcta tenga una fuente clara.',
    closingBody: 'Empezamos por evidencia publica y medicion. Skills, MCP, A2A, plugins o pagos solo se agregan cuando existe una capacidad real, segura y autorizada.',
    auditLabel: 'Auditar mi sitio',
    measureLabel: 'Medir un antes y despues',
  },
  en: {
    locale: 'en',
    eyebrow: 'Sector applications',
    title: 'Every organization needs to be understood through its own facts, services and decisions.',
    intro: 'The same technical foundation changes by sector. Agent Friendly Web organizes what a person must decide and what an agent must discover, cite or use without inventing capabilities.',
    languageLabel: 'Language',
    sectors: [
      { audience: 'Art, culture and collections', value: 'Expose creators, works, collections, provenance, services and limits through verifiable sources.', firstStep: 'Reconcile catalogs, records, FAQs and public policy before creating tools.' },
      { audience: 'Museums, galleries and archives', value: 'Make hours, locations, exhibitions, collections, accessibility and contact channels discoverable.', firstStep: 'Define one canonical source per fact and separate public information from private records.' },
      { audience: 'Municipalities and institutions', value: 'Reduce ambiguous answers about procedures, requirements, appointments, offices, dates and rules.', firstStep: 'Version each procedure with an owner, validity date, source and next review.' },
      { audience: 'Commerce and services', value: 'Clarify offers, location, availability, bookings, terms and contact beyond a landing page.', firstStep: 'Publish direct answers and structured data aligned with the human experience.' },
      { audience: 'SaaS and platforms', value: 'Separate documentation, APIs, security, pricing, limits and actually deployed capabilities.', firstStep: 'Create a verifiable catalog and keep planned, research and deployed states distinct.' },
      { audience: 'Professionals and firms', value: 'Help agents understand expertise, jurisdiction, scope, evidence and engagement paths.', firstStep: 'Turn scattered knowledge into reviewable questions, sources, cases and limits.' },
    ],
    closingTitle: 'The goal is not any answer. It is a correct answer backed by a clear source.',
    closingBody: 'We begin with public evidence and measurement. Skills, MCP, A2A, plugins or payments are added only when a real, secure and authorized capability exists.',
    auditLabel: 'Audit my website',
    measureLabel: 'Measure before and after',
  },
  pt: {
    locale: 'pt',
    eyebrow: 'Aplicacao por setor',
    title: 'Cada organizacao precisa ser compreendida por seus proprios fatos, servicos e decisoes.',
    intro: 'A mesma base tecnica muda conforme o setor. Agent Friendly Web organiza o que uma pessoa deve decidir e o que um agente precisa encontrar, citar ou usar sem inventar capacidades.',
    languageLabel: 'Idioma',
    sectors: [
      { audience: 'Arte, cultura e colecoes', value: 'Expoe autores, obras, colecoes, proveniencia, servicos e limites com fontes verificaveis.', firstStep: 'Conciliar catalogos, fichas, perguntas frequentes e politica publica antes de criar ferramentas.' },
      { audience: 'Museus, galerias e arquivos', value: 'Torna descobriveis horarios, sedes, exposicoes, colecoes, acessibilidade e canais de contato.', firstStep: 'Definir uma fonte canonica por dado e separar informacao publica de registros privados.' },
      { audience: 'Municipios e instituicoes', value: 'Reduz respostas ambiguas sobre procedimentos, requisitos, turnos, escritorios, datas e normas.', firstStep: 'Versionar cada procedimento com responsavel, vigencia, fonte e proxima revisao.' },
      { audience: 'Comercio e servicos', value: 'Esclarece oferta, localizacao, disponibilidade, reservas, condicoes e contato alem de uma landing page.', firstStep: 'Publicar respostas diretas e dados estruturados coerentes com a experiencia humana.' },
      { audience: 'SaaS e plataformas', value: 'Separa documentacao, APIs, seguranca, precos, limites e capacidades realmente implantadas.', firstStep: 'Criar um catalogo verificavel e manter planned, research e deployed separados.' },
      { audience: 'Profissionais e escritorios', value: 'Permite compreender especialidade, jurisdicao, escopo, evidencias e forma de contratacao.', firstStep: 'Transformar conhecimento disperso em perguntas, fontes, casos e limites revisaveis.' },
    ],
    closingTitle: 'A meta nao e aparecer com qualquer resposta. E ter a resposta correta apoiada por uma fonte clara.',
    closingBody: 'Comecamos com evidencia publica e medicao. Skills, MCP, A2A, plugins ou pagamentos so entram quando existe uma capacidade real, segura e autorizada.',
    auditLabel: 'Auditar meu site',
    measureLabel: 'Medir antes e depois',
  },
});
